Repository microsoft/msquic, pull requests merged in 2020-11, with the labels that each got.

#956 Update Per-Processor Socket IOCTL to Correct Name
  src/platform/datapath_winuser.c
Labels: OS: Windows (User)

#955 Use Separate Thread for RPS Tests
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
  scripts/rps.ps1
  src/perf/lib/HpsClient.cpp
  src/perf/lib/HpsClient.h
  src/perf/lib/PerfCommon.h
  src/perf/lib/RpsClient.cpp
  src/perf/lib/RpsClient.h
Labels: Area: Performance

#957 Upload perf dumps and results on failure, and fix stack trace print
  .azure/templates/run-performance.yml
  scripts/performance-helper.psm1
Labels: Area: Performance

#959 Simplify the WPA Code
  src/tools/wpa/ETWTraceEvent.cs
  src/tools/wpa/IQuicEventContext.cs
  src/tools/wpa/QuicEventDataProcessor.cs
  src/tools/wpa/QuicEventSourceParser.cs
  src/tools/wpa/SourceDataCookers/BaseSourceCooker.cs
  src/tools/wpa/SourceDataCookers/EventStatsCooker.cs
  src/tools/wpa/Tables/EventStats.cs
Labels: Area: Performance

#961 Disable Distribution Stage for Feature Branches
  .azure/azure-pipelines.ci.yml
Labels: Area: Pipeline

#962 Fix leak in timerwheel on resize
  src/core/timer_wheel.c
Labels: Area: Core, bug

#963 Initial WPA Plugin Support
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-wpa.yml
  msquic.wpa.datasource.sln
  src/tools/wpa/DataModel/QuicEtwEvent.cs
  src/tools/wpa/DataModel/QuicEventBase.cs
  src/tools/wpa/Properties/launchSettings.json
  src/tools/wpa/QuicEtwSource.cs
  src/tools/wpa/QuicEventCooker.cs
  src/tools/wpa/QuicEventDataSource.csproj
  src/tools/wpa/QuicEventParser.cs
  src/tools/wpa/QuicEventProcessor.cs
  src/tools/wpa/Tables/QuicEventStatsTable.cs
Labels: Area: Performance

#966 Fix incorrect alloc size for mitls HP Key
  src/platform/tls_mitls.c
Labels: TLS: miTLS, bug

#967 Implement complete pool tags
  src/core/api.c
  src/core/binding.c
  src/core/cid.h
  src/core/configuration.c
  src/core/connection.c
  src/core/crypto.c
  src/core/crypto_tls.c
  src/core/library.c
  src/core/library.h
  src/core/listener.c
  src/core/lookup.c
  src/core/loss_detection.c
  src/core/operation.c
  src/core/packet.c
  src/core/range.c
  src/core/recv_buffer.c
  src/core/registration.c
  src/core/send.c
  src/core/send_buffer.c
  src/core/timer_wheel.c
  src/core/unittest/TicketTest.cpp
  src/core/unittest/TransportParamTest.cpp
  src/core/worker.c
  src/inc/quic_platform.h
  src/inc/quic_platform_linux.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/perf/bin/appmain.cpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/RpsClient.cpp
  src/perf/lib/RpsClient.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
  src/platform/cert_capi.c
  src/platform/datapath_linux.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/hashtable.c
  src/platform/platform_linux.c
  src/platform/platform_winuser.c
  src/platform/storage_winkernel.c
  src/platform/storage_winuser.c
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
  src/platform/unittest/DataPathTest.cpp
  src/platform/unittest/TlsTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/tools/attack/attack.cpp
  src/tools/attack/packet_writer.cpp
  src/tools/ip/server/quicipserver.cpp
Labels: Area: Security

#971 Encode Object Type in Custom OpCodes
  src/manifest/MsQuicEtw.man
Labels: Area: Logging, Area: Performance

#973 WPA Plugin - Worker Table Support
  .editorconfig
  src/tools/wpa/DataModel/QuicActivityData.cs
  src/tools/wpa/DataModel/QuicEtwEvent.cs
  src/tools/wpa/DataModel/QuicEtwEventPayload.cs
  src/tools/wpa/DataModel/QuicEvent.cs
  src/tools/wpa/DataModel/QuicEventBase.cs
  src/tools/wpa/DataModel/QuicEventPayload.cs
  src/tools/wpa/DataModel/QuicObjectSet.cs
  src/tools/wpa/DataModel/QuicState.cs
  src/tools/wpa/DataModel/QuicWorker.cs
  src/tools/wpa/QuicEventCooker.cs
  src/tools/wpa/QuicEventDataSource.csproj
  src/tools/wpa/QuicEventParser.cs
  src/tools/wpa/QuicEventProcessor.cs
  src/tools/wpa/Tables/QuicEventStatsTable.cs
  src/tools/wpa/Tables/QuicWorkerTable.cs
Labels: Area: Logging, Area: Performance

#974 Add support for embedding pull tags in windows user mode alloc
  src/core/cid.h
  src/core/connection.c
  src/platform/platform_winuser.c
  src/platform/tls_mitls.c
  src/platform/unittest/TlsTest.cpp
Labels: Area: Core, bug

#976 WPA Connection Table Support
  src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
  src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
  src/tools/wpa/DataModel/QuicActivityData.cs
  src/tools/wpa/DataModel/QuicConnection.cs
  src/tools/wpa/DataModel/QuicData.cs
  src/tools/wpa/DataModel/QuicEtwEventPayload.cs
  src/tools/wpa/DataModel/QuicEvent.cs
  src/tools/wpa/DataModel/QuicEventPayload.cs
  src/tools/wpa/DataModel/QuicObjectSet.cs
  src/tools/wpa/DataModel/QuicState.cs
  src/tools/wpa/DataModel/QuicWorker.cs
  src/tools/wpa/QuicEventParser.cs
  src/tools/wpa/Tables/QuicConnectionTable.cs
  src/tools/wpa/Tables/QuicEventStatsTable.cs
  src/tools/wpa/Tables/QuicWorkerActivityTable.cs
Labels: Area: Logging, Area: Performance

#978 A few more WPA code quality cleanups
  .editorconfig
  src/tools/wpa/DataModel/QuicConnection.cs
  src/tools/wpa/DataModel/QuicObjectSet.cs
  src/tools/wpa/DataModel/QuicState.cs
  src/tools/wpa/DataModel/QuicWorker.cs
  src/tools/wpa/QuicEventCooker.cs
  src/tools/wpa/QuicEventDataSource.csproj
Labels: Area: Logging, Area: Performance

#980 Remove Unsafe library in favor of unsafe block.
  src/tools/wpa/DataModel/QuicEventPayload.cs
  src/tools/wpa/QuicEventDataSource.csproj
Labels: Area: Logging, Area: Performance

#979 WPA Execution Table
  src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
  src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
  src/tools/wpa/DataModel/QuicConnection.cs
  src/tools/wpa/DataModel/QuicData.cs
  src/tools/wpa/DataModel/QuicEvent.cs
  src/tools/wpa/DataModel/QuicEventPayload.cs
  src/tools/wpa/Tables/QuicExecutionTable.cs
Labels: Area: Logging, Area: Performance

#981 Switch to using EventData backing memory directly
  src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
Labels: Area: Logging, Area: Performance

#982 WPA Network Tables
  src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
  src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
  src/tools/wpa/DataModel/QuicConnection.cs
  src/tools/wpa/DataModel/QuicData.cs
  src/tools/wpa/DataModel/QuicEventPayload.cs
  src/tools/wpa/Tables/QuicRttTable.cs
  src/tools/wpa/Tables/QuicThroughputTable.cs
  src/tools/wpa/Tables/QuicTxWindowsTable.cs
Labels: Area: Logging, Area: Performance

#984 Finish Porting over WPA Plugin Code
  scripts/build.ps1
  scripts/prepare-package.ps1
  src/tools/CMakeLists.txt
  src/tools/etwlib/CMakeLists.txt
  src/tools/etwlib/MsQuicEventCollection.h
  src/tools/etwlib/ObjectSet.h
  src/tools/etwlib/QuicEventCollection.cpp
  src/tools/etwlib/QuicEvents.h
  src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
  src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
  src/tools/wpa/DataModel/QuicConnection.cs
  src/tools/wpa/DataModel/QuicData.cs
  src/tools/wpa/DataModel/QuicEventPayload.cs
  src/tools/wpa/DataModel/QuicState.cs
  src/tools/wpa/DataModel/QuicStream.cs
  src/tools/wpa/DataModel/QuicWorker.cs
  src/tools/wpa/Tables/QuicApiTable.cs
  src/tools/wpa/Tables/QuicConnectionTable.cs
  src/tools/wpa/Tables/QuicExecutionTable.cs
  src/tools/wpa/Tables/QuicRttTable.cs
  src/tools/wpa/Tables/QuicSchedulingTable.cs
  src/tools/wpa/Tables/QuicThroughputTable.cs
  src/tools/wpa/Tables/QuicTxBlockedTable.cs
  src/tools/wpa/Tables/QuicTxWindowsTable.cs
  src/tools/wpa/Tables/QuicWorkerActivityTable.cs
Labels: Area: Logging, Area: Performance

#986 Move the Plugin Code Around
  .azure/templates/build-config-dbgext.yml
  .azure/templates/build-config-wpa.yml
  msquic.windbg.sln
  msquic.wpa.sln
  src/plugins/dbg/analyze.cpp
  src/plugins/dbg/binding.cpp
  src/plugins/dbg/configuration.cpp
  src/plugins/dbg/connection.cpp
  src/plugins/dbg/dbg.vcxproj
  src/plugins/dbg/dump.cpp
  src/plugins/dbg/handle.cpp
  src/plugins/dbg/library.cpp
  src/plugins/dbg/listener.cpp
  src/plugins/dbg/packet.cpp
  src/plugins/dbg/quic.def
  src/plugins/dbg/quic_GalleryManifest.xml
  src/plugins/dbg/quicdbg.cpp
  src/plugins/dbg/quicdbg.h
  src/plugins/dbg/quictypes.h
  src/plugins/dbg/readme.md
  src/plugins/dbg/registration.cpp
  src/plugins/dbg/stream.cpp
  src/plugins/dbg/worker.cpp
  src/plugins/wpa/DataModel/ETW/QuicEtwEvent.cs
  src/plugins/wpa/DataModel/ETW/QuicEtwEventPayload.cs
  src/plugins/wpa/DataModel/QuicConnection.cs
  src/plugins/wpa/DataModel/QuicData.cs
  src/plugins/wpa/DataModel/QuicDatapath.cs
  src/plugins/wpa/DataModel/QuicEvent.cs
  src/plugins/wpa/DataModel/QuicEventPayload.cs
  src/plugins/wpa/DataModel/QuicObjectSet.cs
  src/plugins/wpa/DataModel/QuicState.cs
  src/plugins/wpa/DataModel/QuicStream.cs
  src/plugins/wpa/DataModel/QuicWorker.cs
  src/plugins/wpa/Properties/launchSettings.json
  src/plugins/wpa/QuicEtwSource.cs
  src/plugins/wpa/QuicEventCooker.cs
  src/plugins/wpa/QuicEventDataSource.csproj
  src/plugins/wpa/QuicEventParser.cs
  src/plugins/wpa/QuicEventProcessor.cs
  src/plugins/wpa/Tables/QuicApiTable.cs
  src/plugins/wpa/Tables/QuicConnectionTable.cs
  src/plugins/wpa/Tables/QuicDataBatchingTable.cs
  src/plugins/wpa/Tables/QuicExecutionTable.cs
  src/plugins/wpa/Tables/QuicRttTable.cs
  src/plugins/wpa/Tables/QuicSchedulingTable.cs
  src/plugins/wpa/Tables/QuicThroughputTable.cs
  src/plugins/wpa/Tables/QuicTxBlockedTable.cs
  src/plugins/wpa/Tables/QuicTxWindowsTable.cs
  src/plugins/wpa/Tables/QuicWorkerActivityTable.cs
Labels: Area: Logging, Area: Performance

#988 Add LibrarySendRetryStateUpdated Event
  src/core/library.c
  src/core/library.h
  src/core/lookup.c
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/plugins/wpa/DataModel/QuicEvent.cs
  src/tools/etw/quicetw.h
Labels: Area: Core, Area: Logging

#989 WPA Stream Lifetime Table
  src/plugins/wpa/DataModel/QuicConnection.cs
  src/plugins/wpa/DataModel/QuicState.cs
  src/plugins/wpa/DataModel/QuicStream.cs
  src/plugins/wpa/Tables/QuicStreamLifetime.cs
Labels: Area: Logging, Area: Performance

#987 Release 1.0 Forking Soon
  README.md
  docs/Support.md
Labels: Area: Documentation

#933 Pad Path Challenges for MTU
  src/core/loss_detection.c
  src/core/path.c
  src/core/path.h
  src/core/send.c
  src/core/send.h
  src/manifest/clog.sidecar
Labels: Area: Core, Area: Protocol Updates

#992 Split out the Plugins to Separate Pipeline
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.plugins.yml
Labels: Area: Pipeline

#993 Clean up a Couple TODOs
  src/core/connection.c
  src/core/connection.h
  src/inc/quic_platform_dispatch.h
  src/inc/quic_trace.h
  src/platform/datapath_winuser.c
  src/platform/platform_linux.c
Labels: Area: Core

#994 Add Datapath Binding Lifetime Events
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/datapath_linux.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/plugins/wpa/DataModel/QuicDatapath.cs
  src/plugins/wpa/DataModel/QuicEvent.cs
Labels: Area: Logging

#999 Fix Typo
  docs/BUILD.md
Labels: Area: Documentation, external

#1000 Update Docker image version.
  .azure/azure-pipelines.ci.yml
Labels: Area: Build, Area: Pipeline

#998 Add a minimum version to cmake, and add notes in the readme how to update
  CMakeLists.txt
  docs/BUILD.md
Labels: Area: Build, Area: Documentation

#1001 Fix SpicQuic verification failures during Code Coverage
  src/core/connection.c
Labels: Area: Stress, Area: Testing

#1002 Force an update to the OpenSSL cache.
  .azure/templates/build-config-user.yml
Labels: TLS: OpenSSL

#1003 Fix StartExecutable returning multiple values under AppVerifier
  scripts/run-executable.ps1
Labels: Area: Testing

#972 Complete ChaCha20-Poly1305 support.
  .azure/azure-pipelines.ci.yml
  src/manifest/MsQuic.wprp
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
Labels: TLS: Schannel

#990 Fail build if throughput up test has a 5% or more performance drop
  .azure/azure-pipelines.perf.yml
  .azure/templates/run-performance.yml
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance, Area: Pipeline

#1006 Move Plugin Solutions
  .azure/templates/build-config-dbgext.yml
  .azure/templates/build-config-wpa.yml
  src/plugins/dbg/dbg.vcxproj
  src/plugins/msquic.windbg.sln
  src/plugins/msquic.wpa.sln
  src/plugins/wpa/Properties/launchSettings.json
  src/plugins/wpa/QuicEventDataSource.csproj
Labels: Area: Pipeline

#1005 Reorganize Documentation
  README.md
  docs/FAQ.md
  docs/Platforms.md
  docs/Release.md
Labels: Area: Documentation

#1008 Mark perf failures as failing on Azure
  .azure/templates/run-performance.yml
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
Labels: Area: Performance

#1007 Add extra logging to interop client to investigate failures.
  src/manifest/clog.sidecar
  src/tools/interop/CMakeLists.txt
  src/tools/interop/interop.cpp
  src/tools/interop/interop.h
Labels: Area: Logging

#1009 Move Editor Config Files
  src/.config/dotnet-tools.json
  src/.editorconfig
Labels: Area: Build

#1021 Initial Command Line Wrapper for WPA Plugin
  src/plugins/msquic.wpa.sln
  src/plugins/wpacmd/Program.cs
  src/plugins/wpacmd/QuicEtw.csproj
Labels: Area: Logging, Area: Performance

#1023 Fix C11 mode being set on windows.
  src/inc/CMakeLists.txt
Labels: Area: Build, OS: Windows (User)

#1025 Update Contributing Message for Release 1.0 branch
  README.md
Labels: Area: Documentation

#1026 Update to Version 1.1
  .azure/azure-pipelines.ci.yml
  .azure/templates/create-package.yml
  src/inc/msquic.ver
Labels: Area: Build, Area: Pipeline

#1020 Add SSLKEYLOGFILE support to quicinterop client
  CMakeLists.txt
  Dockerfile
  scripts/build.ps1
  scripts/run_endpoint.sh
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/crypto.h
  src/core/crypto_tls.c
  src/inc/msquichelper.h
  src/inc/msquicp.h
  src/inc/quic_tls.h
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
Labels: Area: Interop, TLS: OpenSSL

#1027 Fix Datagram Receive setting not working in some instances.
  scripts/interop.ps1
  src/core/connection.c
  src/core/datagram.c
  src/core/datagram.h
Labels: Area: Core, Area: Interop, bug

#1032 Fix outputting SSLKEYLOGFILE in QNS
  scripts/run_endpoint.sh
Labels: Area: Interop, bug

#1029 Fix the key string for TestName
  src/perf/lib/quicmain.cpp
Labels: Area: Performance, external

#1033 Enable CodeQL on Release and Feature Branches
  .github/workflows/codeql-analysis.yml
Labels: Area: Pipeline

#1038 State Build Requirements at the Top
  docs/BUILD.md
Labels: Area: Build, Area: Documentation

#1036 Refactoring WPA Plugin
  src/plugins/wpa/DataModel/ETW/QuicEtwDataReader.cs
  src/plugins/wpa/DataModel/ETW/QuicEtwEvent.cs
  src/plugins/wpa/DataModel/ETW/QuicEtwEventPayload.cs
  src/plugins/wpa/DataModel/QuicConnection.cs
  src/plugins/wpa/DataModel/QuicDatapath.cs
  src/plugins/wpa/DataModel/QuicEvent.cs
  src/plugins/wpa/DataModel/QuicEventPayload.cs
  src/plugins/wpa/DataModel/QuicEvents.cs
  src/plugins/wpa/DataModel/QuicState.cs
  src/plugins/wpa/DataModel/QuicStream.cs
  src/plugins/wpa/DataModel/QuicWorker.cs
  src/plugins/wpa/QuicEventCooker.cs
  src/plugins/wpa/QuicEventParser.cs
  src/plugins/wpa/Tables/QuicStreamLifetime.cs
  src/plugins/wpacmd/Program.cs
Labels: Area: Logging, Area: Performance

#1041 Lots of WPA Improvements
  src/plugins/wpa/DataModel/QuicConnection.cs
  src/plugins/wpa/DataModel/QuicData.cs
  src/plugins/wpa/DataModel/QuicDatapath.cs
  src/plugins/wpa/DataModel/QuicState.cs
  src/plugins/wpa/DataModel/QuicWorker.cs
  src/plugins/wpa/QuicEventParser.cs
  src/plugins/wpa/Tables/QuicConnectionTable.cs
  src/plugins/wpa/Tables/QuicExecutionTable.cs
  src/plugins/wpa/Tables/QuicNetworkTable.cs
  src/plugins/wpa/Tables/QuicRttTable.cs
  src/plugins/wpa/Tables/QuicSchedulingTable.cs
  src/plugins/wpa/Tables/QuicThroughputTable.cs
  src/plugins/wpa/Tables/QuicTxBlockedTable.cs
  src/plugins/wpa/Tables/QuicTxWindowsTable.cs
  src/plugins/wpa/Tables/QuicWorkerActivityTable.cs
  src/plugins/wpacmd/Program.cs
Labels: Area: Logging, Area: Performance

#1042 Add printout of total time executing to quicinterop
  src/tools/interop/interop.cpp
Labels: Area: Interop

#1045 Fix Windows Kernel Build
  src/core/library.h
Labels: Area: Build, OS: Windows (Kernel)

#1046 Cherry-Pick PR #1045 to Release/1.0
  src/core/library.h
Labels: Area: Build, OS: Windows (Kernel)

#1049 Fix invalid traceline decode for datapath creation
  src/manifest/clog.sidecar
  src/manifest/msquic.clog.cs
  src/plugins/wpa/DataModel/ETW/QuicEtwDataReader.cs
Labels: Area: Logging

#1048 QuicPerf Throughput Improvements
  scripts/emulated-performance.ps1
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
Labels: Area: Performance

#1050 Use clog 0.1.9
  docs/BUILD.md
  scripts/install-powershell-docker.sh
  scripts/prepare-machine.ps1
Labels: Area: Build, Area: Logging, Area: Pipeline

#1051 Increase HPS threshold to 40%
  scripts/RemoteTests.json
Labels: Area: Performance

#1052 Make QNS templates use latest ubuntu image
  .azure/templates/run-qns.yml
Labels: Area: Build, Area: Interop, Area: Pipeline

#1053 WanPerf Pipeline
  .azure/azure-pipelines.wanperf.yml
  .azure/templates/build-config-user.yml
  .azure/templates/build-config-winkernel.yml
  .azure/templates/run-wanperf.yml
  scripts/emulated-performance.ps1
  scripts/prepare-machine.ps1
Labels: Area: Build, Area: Performance, Area: Pipeline

#1047 Pacing Improvements
  src/core/congestion_control.c
  src/core/quicdef.h
Labels: Area: Core, Area: Performance

#1055 Pacing Improvements (#1047) CP into 1.0 release
  src/core/congestion_control.c
  src/core/quicdef.h
Labels: Area: Core, Area: Performance

#1058 WanPerf: Logging and Pacing
  .azure/azure-pipelines.wanperf.yml
  .azure/templates/run-wanperf.yml
  .azure/templates/upload-test-artifacts.yml
  scripts/emulated-performance.ps1
  scripts/log.ps1
  src/manifest/MsQuic.wprp
Labels: Area: Performance, Area: Pipeline

#1059 Fix windows build to build with conformant preprocessor
  CMakeLists.txt
  src/inc/CMakeLists.txt
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/inc/quic_trace.h
Labels: Area: Build, OS: Windows (Kernel), OS: Windows (User)

#1060 WanPerf: BDP Ratio
  .azure/azure-pipelines.wanperf.yml
  .azure/templates/run-wanperf.yml
  scripts/emulated-performance.ps1
Labels: Area: Performance, Area: Pipeline

#1062 Add WanPerf to CI
  .azure/azure-pipelines.ci.yml
Labels: Area: Performance, Area: Pipeline

#1061 Support OpenSSL on Win32 and Arm windows platforms
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  src/platform/tls_openssl.c
Labels: Area: Build, OS: Windows (User), TLS: OpenSSL

#1066 Use the Same CWND Min for Congestion Events
  src/core/congestion_control.c
Labels: Area: Core, Area: Performance

#1067 Use the Same CWND Min for Congestion Events (#1066)
  src/core/congestion_control.c
Labels: Area: Core, Area: Performance
