Repository microsoft/msquic, pull requests merged in 2020-05, with the labels that each got.

#352 Fix Race Condition Crash
  src/core/lookup.c
Labels: bug

#47 Support FIFO and Round Robin Priority Schemes
  .azure/templates/build-config-winkernel.yml
  src/core/connection.c
  src/core/connection.h
  src/core/quicdef.h
  src/core/send.c
  src/inc/msquic.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/QuicTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
Labels: Area: Protocol Updates

#361 Add Test Interface for Datapath Filtering
  src/core/binding.c
  src/core/connection.c
  src/core/library.c
  src/core/library.h
  src/core/packet_builder.c
  src/core/send.c
  src/core/send.h
  src/inc/msquicp.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/QuicTest.cpp
  src/test/lib/TestAbstractionLayer.h
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestListener.h
  src/test/lib/precomp.h
Labels: Area: Testing

#329 Unreliable Datagram Support
  CMakeLists.txt
  docs/api/DatagramSend.md
  docs/api/QUIC_API_TABLE.md
  src/core/CMakeLists.txt
  src/core/api.c
  src/core/api.h
  src/core/connection.c
  src/core/connection.h
  src/core/core.kernel.vcxproj
  src/core/crypto.c
  src/core/crypto_tls.c
  src/core/datagram.c
  src/core/datagram.h
  src/core/frame.c
  src/core/frame.h
  src/core/inline.c
  src/core/library.c
  src/core/loss_detection.c
  src/core/operation.h
  src/core/packet_builder.c
  src/core/packet_builder.h
  src/core/precomp.h
  src/core/quicdef.h
  src/core/send.c
  src/core/send.h
  src/core/sent_packet_metadata.h
  src/core/session.c
  src/core/settings.c
  src/core/settings.h
  src/core/stream_send.c
  src/core/transport_params.h
  src/core/unittest/SpinFrame.cpp
  src/inc/msquic.h
  src/inc/quic_trace.h
  src/manifest/MsQuicEtw.man
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/QuicTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
  src/tools/dbg/packet.cpp
  src/tools/dbg/quictypes.h
  src/tools/ping/PingConnection.cpp
  src/tools/ping/PingConnection.h
  src/tools/ping/PingStream.cpp
  src/tools/ping/PingStream.h
  src/tools/ping/QuicPing.cpp
  src/tools/ping/QuicPing.h
  src/tools/siduck/CMakeLists.txt
  src/tools/siduck/siduck.cpp
Labels: Area: Protocol Updates

#372 Update Build Docs for CMake Specific Instructions
  docs/BUILD.md
  docs/TEST.md
Labels: Area: Documentation

#379 Support NoProcDump Mode for Windows Test Script
  .azure/scripts/run-gtest.ps1
  scripts/test.ps1
Labels: Area: Testing

#382 Refactor Test Code
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/BasicTest.cpp
  src/test/lib/CMakeLists.txt
  src/test/lib/DataTest.cpp
  src/test/lib/DatagramTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Testing

#383 Update AZP build datestamp to use ISO 8601-like date format
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
Labels: Area: Build

#386 Interop Server Instructions
  docs/InteropServerSetup.md
  src/tools/interopserver/InteropServer.cpp
Labels: Area: Documentation

#390 Create Explicit Error Codes for Interop Server Request Failures
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
Labels: App: quicinterop

#389 Fix No Idle Timeout TP Bug
  src/core/settings.c
  src/tools/interop/interop.cpp
Labels: App: quicinterop, bug

#391 Fix Bug in fread Call in Interop Server
  src/tools/interopserver/InteropServer.cpp
Labels: App: quicinterop, bug

#392 Add Random Loss to SpinQuic
  .azure/templates/run-spinquic.yml
  src/core/stream.c
  src/core/stream_send.c
  src/manifest/MsQuic.wprp
  src/tools/spin/spinquic.cpp
Labels: App: spinquic

#302 Enable Address Sanitizer for Linux
  .azure/azure-pipelines.ci.yml
  src/core/api.c
Labels: OS: Ubuntu, help wanted

#393 Get SpinQuic Running Clean
  .azure/scripts/run-executable.ps1
  src/core/ack_tracker.c
  src/core/ack_tracker.h
  src/core/connection.c
  src/core/crypto.c
  src/core/loss_detection.c
  src/core/packet_builder.c
  src/core/sent_packet_metadata.c
  src/core/sent_packet_metadata.h
  src/core/session.c
  src/platform/tls_openssl.c
  src/platform/tls_stub.c
  src/tools/dbg/packet.cpp
  src/tools/dbg/quictypes.h
  src/tools/spin/spinquic.cpp
Labels: App: spinquic, bug

#398 Remove Merge Sections from Kernel Mode
  src/bin/winkernel/msquic.kernel.vcxproj
Labels: OS: Windows Kernel Mode

#400 Don't Accept Retry after ACK
  src/core/connection.c
Labels: App: spinquic

#401 Add SpinQuic support for DatagramSend, and other settings parameters
  src/core/datagram.c
  src/tools/spin/spinquic.cpp
Labels: App: spinquic

#403 More SpinQuic Features and Associated Fixes
  .gitattributes
  src/core/api.c
  src/core/datagram.c
  src/core/send.c
  src/core/send.h
  src/core/stream_send.c
  src/inc/quic_trace.h
  src/tools/dbg/connection.cpp
  src/tools/dbg/dump.cpp
  src/tools/dbg/quic.def
  src/tools/dbg/quic_GalleryManifest.xml
  src/tools/dbg/quicdbg.h
  src/tools/dbg/quictypes.h
  src/tools/dbg/worker.cpp
  src/tools/spin/spinquic.cpp
Labels: App: spinquic

#407 Small Refactor of Build Files
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  .azure/scripts/install-procdump.ps1
  .azure/scripts/run-executable.ps1
  .azure/scripts/run-gtest.ps1
  .azure/templates/run-bvt-int.yml
  .azure/templates/run-bvt.yml
  .gitignore
  CMakeLists.txt
  docs/BUILD.md
  scripts/build.ps1
  scripts/prepare-machine.ps1
  scripts/test.ps1
  src/bin/winkernel/msquic.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
  src/tools/dbg/dbg.vcxproj
Labels: Area: Build

#405 Adds Several Performance Related Fixes
  src/core/connection.c
  src/core/inline.c
  src/core/quicdef.h
  src/core/registration.c
  src/core/registration.h
  src/tools/ping/QuicPing.cpp
Labels: Area: Performance

#406 Add Build Support for PGO
  CMakeLists.txt
  scripts/build.ps1
Labels: Area: Performance

#409 Add Initial PGO File
  CMakeLists.txt
  src/bin/winuser/msquic.pgd
Labels: Area: Performance

#411 Fix race condition in Ping tests
  src/test/lib/TestStream.cpp
Labels: Area: Testing, bug

#412 Improve Output when CDB.exe is Missing
  .azure/scripts/run-executable.ps1
  .azure/scripts/run-gtest.ps1
Labels: Area: Build

#415 Fix leak in QuicStreamSendFlush
  src/core/stream_send.c
Labels: App: spinquic, bug

#417 Don't Use App Closed until 1-RTT Keys
  src/core/connection.c
Labels: App: spinquic, bug

#418 Only Change Partitions for New Paths
  src/core/connection.c
Labels: Area: Performance

#420 Allow a Single Partition Update per Path
  src/core/connection.c
  src/core/path.h
Labels: Area: Performance

#424 Fix cmake builds in Ninja
  CMakeLists.txt
Labels: Area: Build

#426 Add flags and queue check to QuicDatagramValidate
  src/core/connection.h
  src/core/datagram.c
  src/core/inline.c
Labels: App: spinquic

#430 Use CMAKE_STATIC_LIBRARY_SUFFIX for openssl
  CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/unittest/CMakeLists.txt
Labels: Area: Build, TLS: OpenSSL

#429 Update Windows Kernel Build Flags
  src/bin/winkernel/msquic.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, OS: Windows Kernel Mode

#431 Disallow in-source builds
  CMakeLists.txt
Labels: Area: Build

#434 Disable String Pooling for Kernel Mode
  src/bin/winkernel/msquic.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, OS: Windows Kernel Mode

#433 Make CMake build compatible with more platforms
  CMakeLists.txt
  src/platform/CMakeLists.txt
Labels: Area: Build, OS: Ubuntu

#435 Reset Datagram SendFlag when writing last datagram and out of buffer
  src/core/datagram.c
Labels: App: spinquic, bug
