Repository microsoft/msquic, pull requests merged in 2020-06, with the labels that each got.

#442 Add More Kernel Mode Compiler Options
  src/bin/winkernel/msquic.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, OS: Windows Kernel Mode

#443 Remove flags that can't be sent during congestion control without allowance
  src/core/send.c
Labels: App: spinquic, bug

#439 Don't Explicitly Target a WDK Version
  src/bin/winkernel/msquic.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, OS: Windows Kernel Mode

#447 Fix Send Flags used for Packet Building
  src/core/packet_builder.c
  src/core/send.c
Labels: App: spinquic, bug

#449 Update Badge to Public Location
  README.md
Labels: Area: Build

#445 Hide all exports on linux platforms from libmsquic.so
  src/bin/CMakeLists.txt
  src/bin/linux/exports.txt
  src/core/unittest/CMakeLists.txt
  src/test/bin/CMakeLists.txt
Labels: Area: Build, OS: Ubuntu

#450 Add -d2epilogunwindrequirev2 Compiler Flag
  src/bin/winkernel/msquic.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, OS: Windows Kernel Mode

#441 Tests Wait Longer with Random Loss
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
Labels: Area: Testing, bug

#453 Fix Newly Found Leaks
  src/core/unittest/SpinFrame.cpp
  src/platform/unittest/TlsTest.cpp
  src/test/lib/ApiTest.cpp
Labels: Area: Testing, bug

#457 Increase Azure Pipelines Timeout for BVTs
  .azure/templates/run-bvt-int.yml
  .azure/templates/run-bvt.yml
Labels: Area: Testing

#458 Move datapath shutdown to occur before connection cleanup
  src/core/library.c
Labels: App: spinquic, bug

#456 Fix incorrect SAL annocation on linux QuicDataPathUninitialize
  src/platform/datapath_linux.c
Labels: OS: Ubuntu

#455 Don't call DisableThreadLibraryCalls with static CRT
  src/bin/winuser/dllmain.c
  src/bin/winuser_fuzz/dllmain.c
Labels: OS: Windows User Mode, bug

#459 Improve Azure Pipeline Job Names
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-dbgext.yml
  .azure/templates/build-config-user.yml
  .azure/templates/build-config-winkernel.yml
  .azure/templates/run-bvt-int.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-quicinterop.yml
  .azure/templates/run-spinquic.yml
Labels: Area: Build

#465 Supress deprecation warning for ExInitializeWorkItem in kernel mode
  src/platform/storage_winkernel.c
Labels: Area: Build, OS: Windows Kernel Mode

#463 Workaround for LTTng Duplicate Tracepoint
  .azure/azure-pipelines.ci.yml
  src/bin/linux/exports.txt
  src/bin/linux/init.c
  src/platform/platform_linux.c
  src/platform/unittest/CMakeLists.txt
  src/tools/attack/CMakeLists.txt
Labels: Area: Build, OS: Ubuntu

#454 Add support for building in UWP mode
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-user.yml
  CMakeLists.txt
  scripts/build.ps1
  src/bin/CMakeLists.txt
  src/inc/quic_platform_winuser.h
  src/platform/datapath_winuser.c
  src/tools/attack/CMakeLists.txt
  src/tools/ping/QuicPing.cpp
Labels: Area: Build, OS: Windows User Mode

#467 Build DLL only for UWP
  .azure/azure-pipelines.ci.yml
Labels: Area: Build

#471 Add folder support to CMake
  CMakeLists.txt
  src/bin/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/unittest/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/unittest/CMakeLists.txt
  src/test/bin/CMakeLists.txt
  src/test/lib/CMakeLists.txt
  src/tools/attack/CMakeLists.txt
  src/tools/etw/CMakeLists.txt
  src/tools/etwlib/CMakeLists.txt
  src/tools/interop/CMakeLists.txt
  src/tools/interopserver/CMakeLists.txt
  src/tools/ping/CMakeLists.txt
  src/tools/post/CMakeLists.txt
  src/tools/reach/CMakeLists.txt
  src/tools/sample/CMakeLists.txt
  src/tools/siduck/CMakeLists.txt
  src/tools/spin/CMakeLists.txt
  src/tools/void/CMakeLists.txt
Labels: Area: Build

#474 Wait for all connections to be freed during registration close
  src/core/connection.c
  src/core/registration.c
  src/core/registration.h
  src/core/session.c
Labels: bug

#469 Draft-28 Support
  docs/InteropServerSetup.md
  scripts/interop.ps1
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/core/crypto_tls.c
  src/core/packet.c
  src/core/packet.h
  src/core/packet_builder.c
  src/core/transport_params.h
  src/core/unittest/TransportParamTest.cpp
  src/inc/quic_versions.h
  src/platform/tls_stub.c
  src/test/lib/HandshakeTest.cpp
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/post/post.cpp
  src/tools/reach/reach.cpp
Labels: Area: Protocol Updates

#470 Moves linux platform functions in public header to be inlined
  src/inc/msquic_linux.h
  src/platform/inline.c
  src/platform/platform_linux.c
Labels: Area: Build, OS: Ubuntu

#475 Add support for cmake installs
  CMakeLists.txt
  src/bin/CMakeLists.txt
  src/bin/msquic-config.cmake.in
  src/inc/msquic.h
  src/inc/msquic_winuser.h
Labels: Area: Build

#479 Adds Various Improvements to Interop Tool
  scripts/interop.ps1
  src/tools/interop/interop.cpp
  src/tools/interop/interop.h
Labels: App: quicinterop

#486 Correctly Send & Validate Retry Source CID
  src/core/connection.c
  src/core/connection.h
  src/tools/dbg/quictypes.h
Labels: App: quicinterop, bug

#481 Add configuration surface for resumption and 0-RTT for server.
  src/core/connection.c
  src/core/connection.h
  src/core/quicdef.h
  src/core/session.c
  src/core/settings.c
  src/core/settings.h
  src/inc/msquic.h
Labels: Area: Protocol Updates

#493 Update Interop Servers
  src/tools/interop/interop.cpp
Labels: App: quicinterop

#483 Clean up worker pools before closing any leftover quic sessions
  .azure/templates/run-spinquic.yml
  scripts/spin.ps1
  src/core/session.c
  src/tools/spin/spinquic.cpp
Labels: App: spinquic, bug

#494 Implement Draft 29 Support
  docs/api/QUIC_STATUS.md
  src/core/binding.c
  src/core/connection.c
  src/core/crypto.c
  src/core/frame.h
  src/core/packet.c
  src/core/packet.h
  src/core/packet_builder.c
  src/core/quicdef.h
  src/inc/msquic_linux.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/inc/msquichelper.h
  src/inc/quic_versions.h
  src/platform/unittest/CryptTest.cpp
  src/test/lib/TestListener.cpp
  src/tools/etw/quicetw.h
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/post/post.cpp
  src/tools/reach/reach.cpp
Labels: Area: Protocol Updates

#452 New External Contribution Rules
  .github/CONTRIBUTING.md
  README.md
Labels: Area: Documentation

#491 Change strncat to strcat in QuicPlatFreeSelfSignedCert to fix compiling on linux
  src/platform/selfsign_openssl.c
Labels: Area: Build, OS: Ubuntu, external

#461 Build QNS interop image
  .dockerignore
  Dockerfile
  run_endpoint.sh
Labels: Area: Build, external

#495 [Linux] Move from si_family in the union to sockaddr;
  src/inc/msquic_linux.h
  src/platform/datapath_linux.c
  src/platform/platform_linux.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/ping/QuicPing.cpp
Labels: Area: Build, OS: Ubuntu

#489 Add base support for regression testing
  .azure/azure-pipelines.ci.yml
  .azure/scripts/publish-performance-results.ps1
  .azure/templates/publish-performance.yml
  .azure/templates/run-performance.yml
  scripts/performance.ps1
  src/tools/ping/QuicPing.cpp
Labels: Area: Performance

#492 Resumption ticket generation/parsing logic
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/crypto.h
  src/core/quicdef.h
  src/inc/quic_tls.h
  src/inc/quic_trace_lttng.h
  src/manifest/MsQuicEtw.man
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
  src/platform/unittest/TlsTest.cpp
  src/tools/attack/packet_writer.cpp
Labels: Area: Protocol Updates

#498 Skip component governance detection for perf results
  .azure/templates/publish-performance.yml
  .azure/templates/run-performance.yml
Labels: Area: Build

#480 Fixes and Documentation for PGO
  .gitattributes
  CMakeLists.txt
  docs/PGO.md
  src/bin/winuser/msquic.pgd
  src/bin/winuser/pgo_x64/msquic.pgd
Labels: Area: Build, Area: Performance

#502 Fix data published to file
  scripts/performance.ps1
Labels: Area: Performance

#501 Don't Exclude run_endpoint.sh in Docker
  .dockerignore
Labels: Area: Build

#500 Improve/Expand QUIC Status Codes
  .azure/templates/run-bvt-int.yml
  .azure/templates/run-bvt.yml
  src/core/connection.c
  src/core/frame.h
  src/inc/msquic_linux.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/test/lib/HandshakeTest.cpp
Labels: Area: API, Area: Build

#504 Fix cmake dependencies for ETW generation
  CMakeLists.txt
Labels: Area: Build, OS: Windows Kernel Mode, OS: Windows User Mode

#506 Fix Version Negotiation Packet
  src/core/binding.c
Labels: App: quicinterop, bug

#505 Switch to using SQL database for performance results rather then files
  .azure/scripts/publish-performance-results.ps1
  .azure/templates/publish-performance.yml
  .azure/templates/run-performance.yml
  scripts/performance.ps1
Labels: Area: Performance

#509 Refactor Test Datapath Hooks
  src/core/binding.c
  src/core/connection.c
  src/core/library.c
  src/core/library.h
  src/core/quicdef.h
  src/inc/msquicp.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/driver.cpp
  src/test/lib/DatagramTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
Labels: Area: Testing

#283 Implement path validation timeout
  src/core/connection.c
  src/core/loss_detection.c
  src/core/path.h
Labels: Area: Protocol Updates

#512 Fix builds on non glibc based linux platforms
  src/platform/CMakeLists.txt
  src/platform/datapath_linux.c
  src/platform/platform_linux.c
Labels: Area: Build, OS: Ubuntu

#513 Test Refactoring and Improvements
  .azure/templates/run-bvt-int.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-spinquic.yml
  scripts/interop.ps1
  scripts/spin.ps1
  scripts/test.ps1
  src/inc/msquic_linux.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/platform/inline.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/BasicTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/DatagramTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
Labels: Area: Testing

#510 Add Database Server ASP.NET Core Source Code
  .config/dotnet-tools.json
  .editorconfig
  src/perf/QuicPerformanceDataServer.sln
  src/perf/dbserver/Controllers/PerformanceController.cs
  src/perf/dbserver/Data/PerformanceContext.cs
  src/perf/dbserver/Models/Db/DbPlatform.cs
  src/perf/dbserver/Models/Db/DbTest.cs
  src/perf/dbserver/Models/Db/DbTestRecord.cs
  src/perf/dbserver/Models/Db/TestResult.cs
  src/perf/dbserver/Models/IAuthorizable.cs
  src/perf/dbserver/Models/PlatformCreate.cs
  src/perf/dbserver/Models/TestCreate.cs
  src/perf/dbserver/Models/TestPublishResult.cs
  src/perf/dbserver/Models/TestPublishResultWithTime.cs
  src/perf/dbserver/Models/TestRecord.cs
  src/perf/dbserver/Program.cs
  src/perf/dbserver/Properties/launchSettings.json
  src/perf/dbserver/Properties/serviceDependencies.MsQuicPerformanceResults - Web Deploy.json
  src/perf/dbserver/Properties/serviceDependencies.json
  src/perf/dbserver/Properties/serviceDependencies.local.json
  src/perf/dbserver/QuicPerformanceDataServer.csproj
  src/perf/dbserver/Startup.cs
  src/perf/dbserver/appsettings.Development.json
  src/perf/dbserver/appsettings.json
  src/perf/dbserver/scripts/CreatePlatform.ps1
  src/perf/dbserver/scripts/CreateTest.ps1
Labels: Area: Performance

#516 Update DockerFile to Install Noninteractive
  Dockerfile
Labels: Area: Build

#517 Run perf tests on hosted system
  .azure/azure-pipelines.ci.yml
  .azure/scripts/install-build-artifacts.ps1
  .azure/templates/run-performance-int.yml
  scripts/performance.ps1
Labels: Area: Performance

#523 Allow Zero-Length Stream Sends with FIN Flag
  src/core/api.c
  src/core/stream_send.c
  src/tools/interopserver/InteropServer.cpp
Labels: App: quicinterop, bug

#520 Expand Perf Testing
  .azure/azure-pipelines.ci.yml
  .azure/templates/publish-performance.yml
  .azure/templates/run-bvt-int.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-performance-int.yml
  .azure/templates/run-performance.yml
  .azure/templates/run-quicinterop.yml
  .azure/templates/run-spinquic.yml
Labels: Area: Performance

#521 Add Database support for storing machines
  src/perf/dbserver/Controllers/PerformanceController.cs
  src/perf/dbserver/Data/PerformanceContext.cs
  src/perf/dbserver/Models/Db/DbMachine.cs
  src/perf/dbserver/Models/Db/DbTestRecord.cs
Labels: Area: Performance

#525 Add Support for PGO Azure Pipeline
  .azure/azure-pipelines.pgo.yml
  .azure/templates/run-performance-int.yml
  scripts/build.ps1
  scripts/performance.ps1
  src/bin/winuser/pgo_x64/msquic.pgd
  src/bin/winuser/pgo_x86/msquic.pgd
Labels: Area: Performance

#527 Fix Main Build Status Link
  README.md
Labels: Area: Build, Area: Documentation

#529 Force disable logging for CMake versions older then 3.6
  CMakeLists.txt
Labels: Area: Build, OS: Ubuntu

#531 Perf Improvement for OpenSSL Header Key
  src/platform/tls_openssl.c
Labels: Area: Performance, TLS: OpenSSL

#533 Allow datapath hook failure happen in spinquic
  src/tools/spin/spinquic.cpp
Labels: App: spinquic, OS: Ubuntu, OS: Windows User Mode

#535 Use port 4433 for performance testing
  scripts/performance.ps1
Labels: Area: Performance, OS: Ubuntu

#508 0-RTT Server TLS implementation
  src/core/api.c
  src/core/connection.c
  src/core/crypto.c
  src/core/quicdef.h
  src/core/session.c
  src/core/settings.c
  src/core/settings.h
  src/inc/quic_tls.h
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
  src/tools/interopserver/InteropServer.h
  src/tools/ping/PingConnection.cpp
  src/tools/ping/PingConnection.h
  src/tools/ping/Server.cpp
  src/tools/sample/sample.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Protocol Updates

#524 Enable building on Azure for Raspberry Pi with a cross compiler
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-user-container.yml
  CMakeLists.txt
  cmake/toolchains/arm-pi-gnueabihf.toolchain.cmake
  cmake/toolchains/arm.toolchain.cmake
  cmake/toolchains/gnu.toolchain.cmake
  scripts/build.ps1
Labels: Area: Build, OS: Ubuntu

#536 Improvements to the Perf Script
  .azure/templates/run-performance-int.yml
  .azure/templates/run-performance.yml
  scripts/performance.ps1
Labels: Area: Performance

#541 Dump Results on Error
  scripts/performance.ps1
Labels: Area: Performance

#538 Move All Scripts to Top Level Scripts Folder
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  .azure/templates/create-package.yml
  .azure/templates/download-artifacts.yml
  .azure/templates/publish-performance.yml
  scripts/install-build-artifacts.ps1
  scripts/integrate-branch.ps1
  scripts/interop.ps1
  scripts/prepare-package.ps1
  scripts/publish-performance-results.ps1
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
  scripts/spin.ps1
  scripts/sync-mirror.ps1
  scripts/test.ps1
Labels: Area: Build

#543 Fix Break in Perf Publish Script
  scripts/publish-performance-results.ps1
Labels: Area: Performance

#544 Customizable Performance Pipeline
  .azure/azure-pipelines.perf.yml
  .azure/azure-pipelines.pgo.yml
  .azure/templates/build-config-user.yml
  scripts/performance.ps1
Labels: Area: Build, Area: Performance

#545 Fixes Leaks on Send Path
  src/core/packet_builder.c
  src/core/send.c
  src/core/sent_packet_metadata.c
  src/core/sent_packet_metadata.h
Labels: bug

#547 Update PGO Files
  src/bin/winuser/pgo_x64/msquic.pgd
  src/bin/winuser/pgo_x86/msquic.pgd
Labels: Area: Performance

#548 Azure Pipeline for Building and Publishing Docker Image
  .azure/azure-pipelines.docker.yml
Labels: Area: Build

#549 Performance Stability Improvements
  scripts/performance.ps1
Labels: Area: Performance

#550 Fix minor stub bug
  src/platform/tls_stub.c
Labels: TLS: Stub

#551 Fix TLS handshake test failures in Schannel and OpenSSL.
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
Labels: bug

#552 Add cmake changes necessary for Darwin builds
  CMakeLists.txt
  src/platform/CMakeLists.txt
Labels: OS: macOS

#554 Fix accidentally added no-inline and no-omit-frame-pointer flags on unix
  CMakeLists.txt
Labels: bug

#553 Migration Tests and Fixes
  src/core/connection.c
  src/core/send.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestAbstractionLayer.h
  src/test/lib/TestHelpers.h
Labels: Area: Protocol Updates, Area: Testing

#540 Enable Application Verifier on Windows BVTs.
  .azure/templates/run-bvt-int.yml
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
  scripts/test.ps1
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#556 Increase Internal BVT timeout to 90 minutes
  .azure/templates/run-bvt-int.yml
Labels: Area: Testing

#555 Improve Loopback Perf Results
  scripts/performance.ps1
  src/platform/datapath_winuser.c
Labels: Area: Performance

#563 Fix WPR Profile XML
  scripts/performance.ps1
Labels: Area: Performance

#564 Standardize Container Builds
  .azure/templates/build-config-user-container.yml
  scripts/install-powershell.sh
  scripts/prepare-machine.ps1
Labels: Area: Build, OS: Ubuntu

#565 Disable APIPA Interface for Loopback Test Perf
  scripts/performance.ps1
Labels: Area: Performance

#567 Allow QuicPing server to specify number of connections allowed before shutting down
  scripts/performance.ps1
  src/tools/ping/Client.cpp
  src/tools/ping/PingConnection.cpp
  src/tools/ping/PingConnection.h
  src/tools/ping/QuicPing.cpp
  src/tools/ping/QuicPing.h
  src/tools/ping/Server.cpp
Labels: Area: Performance
