Repository microsoft/msquic, pull requests merged in 2020-08, with the labels that each got.

#590 Fully Enable CLOG (LTTng) for Linux
  CMakeLists.txt
  Dockerfile
  scripts/install-powershell-docker.sh
  scripts/log.ps1
  scripts/prepare-machine.ps1
  src/core/CMakeLists.txt
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/core/listener.c
  src/core/packet.c
  src/core/unittest/CMakeLists.txt
  src/inc/quic_trace.h
  src/inc/quic_trace_lttng.h
  src/inc/quic_trace_manifested_etw.h
  src/manifest/clog.sidecar
  src/manifest/msquic.clog_config
  src/perf/bin/CMakeLists.txt
  src/perf/lib/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/datapath_linux.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/platform_linux.c
  src/platform/unittest/CMakeLists.txt
  src/test/bin/CMakeLists.txt
  src/test/lib/CMakeLists.txt
Labels: Area: Logging

#672 Remove Skip Event
  src/core/connection.c
  src/manifest/clog.sidecar
Labels: Area: Logging

#677 Track Received ECN Counts
  src/core/ack_tracker.c
  src/core/ack_tracker.h
  src/core/connection.c
  src/core/frame.c
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/platform/datapath_linux.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Protocol Updates

#678 Refactor MsQuic CLOG Types
  src/core/binding.c
  src/core/connection.c
  src/core/listener.c
  src/core/packet.c
  src/manifest/clog.sidecar
  src/manifest/msquic.clog.cs
  src/manifest/msquic.clog_config
  src/platform/datapath_linux.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Logging

#671 Finish switching clog to a dynamic tracepoint provider
  scripts/install-powershell-docker.sh
  scripts/prepare-machine.ps1
  src/bin/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/unittest/CMakeLists.txt
  src/perf/bin/CMakeLists.txt
  src/perf/lib/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/unittest/CMakeLists.txt
  src/test/bin/CMakeLists.txt
  src/test/lib/CMakeLists.txt
Labels: Area: Logging

#680 Fix Comment for QUIC_SEND_FLAG_START
  src/inc/msquic.h
Labels: Area: Documentation

#681 Converge Internal BVT Pipeline
  .azure/azure-pipelines-int.ci.yml
  .azure/templates/run-bvt-int.yml
Labels: Area: Pipeline

#682 Add back in mechanism to completely skip clog.
  CMakeLists.txt
  src/bin/CMakeLists.txt
  src/bin/linux/traceprovider.c
  src/inc/quic_trace.h
  src/inc/quic_trace_lttng.h
Labels: Area: Build, Area: Logging

#685 ECN Send Path Abstraction
  src/core/ack_tracker.c
  src/core/binding.c
  src/core/packet_builder.c
  src/inc/quic_datapath.h
  src/platform/datapath_linux.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/attack/attack.cpp
Labels: Area: Protocol Updates

#686 Perf Refactoring
  src/inc/quic_driver_main.h
  src/perf/bin/appmain.cpp
  src/perf/bin/drvmain.cpp
  src/perf/lib/PerfCommon.h
  src/perf/lib/PerfHelpers.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
  src/perf/lib/ThroughputServer.cpp
  src/perf/lib/ThroughputServer.h
  src/perf/lib/quicmain.cpp
Labels: Area: Performance

#683 Out of tree building fixes
  CMakeLists.txt
Labels: Area: Build, external

#688 Refactor the openssl build.
  CMakeLists.txt
Labels: Area: Build, TLS: OpenSSL, external

#691 Refactored Perf Code
  scripts/RemoteTests.json
  src/inc/msquichelper.h
  src/perf/bin/appmain.cpp
  src/perf/lib/PerfBase.h
  src/perf/lib/PerfCommon.h
  src/perf/lib/PerfHelpers.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
  src/perf/lib/ThroughputServer.cpp
  src/perf/lib/ThroughputServer.h
  src/perf/lib/quicmain.cpp
Labels: Area: Performance

#693 Switch all C++ new in kernel mode to nothrow new
  src/inc/msquic.hpp
  src/perf/bin/drvmain.cpp
  src/perf/lib/PerfHelpers.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/quicmain.cpp
  src/test/bin/winkernel/driver.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/DatagramTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/TestStream.cpp
  src/test/lib/TestStream.h
Labels: Area: Build, OS: Windows Kernel Mode

#695 Fix Schannel TLS alerts not being read correctly.
  .azure/azure-pipelines.ci.yml
  scripts/log.ps1
  scripts/ping.ps1
  scripts/run-executable.ps1
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: TLS: Schannel, bug

#684 Fix build with clang under Linux
  CMakeLists.txt
  src/inc/msquic.hpp
  src/inc/quic_var_int.h
  src/perf/lib/PerfHelpers.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
  src/perf/lib/ThroughputServer.cpp
  src/platform/tls_openssl.c
  src/test/lib/DataTest.cpp
  src/test/lib/DrillDescriptor.cpp
  src/test/lib/DrillDescriptor.h
  src/test/lib/EventTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestListener.cpp
  src/test/lib/TestStream.cpp
Labels: Area: Build, external

#697 Fix some minor perf script bugs
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Build, Area: Performance

#700 Update Docker Build for CLOG Dependencies
  Dockerfile
Labels: Area: Logging

#689 With some fixes, we can remove "-Wno-unused-value"
  CMakeLists.txt
  src/core/unittest/FrameTest.cpp
  src/inc/quic_platform_linux.h
  src/perf/lib/CMakeLists.txt
  src/platform/datapath_linux.c
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
  src/tools/ping/PingConnection.cpp
Labels: Area: Build, external

#676 Add ECN support to the Linux datapath
  .azure/azure-pipelines.ci.yml
  src/core/unittest/CMakeLists.txt
  src/platform/datapath_linux.c
  src/platform/unittest/CMakeLists.txt
  src/platform/unittest/DataPathTest.cpp
  src/test/bin/CMakeLists.txt
Labels: OS: Ubuntu, external

#675 QUIC Network Simulation Logging Support
  Dockerfile
  scripts/install-powershell-docker.sh
  scripts/run_endpoint.sh
Labels: Area: Logging, Area: Pipeline

#699 Cleanup Logging Script Args
  scripts/interop.ps1
  scripts/log.ps1
  scripts/ping.ps1
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
  scripts/spin.ps1
  scripts/test.ps1
Labels: Area: Logging

#701 Add option to run clang-tidy and cppcheck
  CMakeLists.txt
Labels: Area: Build

#702 Add sidechannel to perf runner to enable stopping the tests safely internally
  scripts/performance-helper.psm1
  scripts/performance.ps1
  src/inc/msquic.hpp
  src/perf/bin/appmain.cpp
Labels: Area: Performance

#703 Add RPS into perf test suite
  scripts/RemoteTests.json
Labels: Area: Performance

#705 Fix compilation with VS 16.7
  src/core/connection.c
  src/core/listener.c
  src/core/lookup.c
  src/core/sent_packet_metadata.c
  src/platform/datapath_winkernel.c
  src/platform/hashtable.c
Labels: Area: Build, bug

#707 Some improvements to docker interop logging
  scripts/run_endpoint.sh
Labels: Area: Build, Area: Logging, Area: Pipeline

#706 Add siduck handler to interop server
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
Labels: App: quicinterop

#713 Add inc and warnings to perf binary
  src/perf/bin/CMakeLists.txt
  src/perf/bin/appmain.cpp
Labels: Area: Build

#715 Add assertions to enqueue connection operation to help solve 698
  src/core/connection.c
Labels: bug

#710 Integrate clog 0.1.6
  scripts/generate_kernel_clog.bat
  scripts/install-powershell-docker.sh
  scripts/prepare-machine.ps1
  src/core/crypto_tls.c
  src/manifest/clog.sidecar
  src/platform/platform_winuser.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/test/bin/winkernel/driver.cpp
Labels: Area: Logging

#714 Onboard clang into build scripts and CI
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-user.yml
  scripts/build.ps1
Labels: Area: Build, Area: Pipeline, OS: Ubuntu

#717 Interop Client Siduck Support
  scripts/log.ps1
  src/tools/CMakeLists.txt
  src/tools/interop/interop.cpp
  src/tools/interop/interop.h
  src/tools/siduck/CMakeLists.txt
  src/tools/siduck/siduck.cpp
Labels: App: quicinterop

#718 Apply warning flags to tools and fix issues
  CMakeLists.txt
  src/core/unittest/FrameTest.cpp
  src/tools/CMakeLists.txt
  src/tools/attack/attack.cpp
  src/tools/attack/packet_writer.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
  src/tools/ping/Client.cpp
  src/tools/ping/PingConnection.cpp
  src/tools/ping/PingStream.cpp
  src/tools/post/post.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Build, external

#724 Use processor count for PerProc structures instead of partition count.
  src/core/connection.c
  src/core/library.c
  src/core/library.h
  src/core/packet_space.c
Labels: bug

#712 More sanitizers
  CMakeLists.txt
  src/core/binding.c
  src/core/connection.h
  src/core/frame.c
  src/core/library.c
  src/core/library.h
  src/core/packet.h
  src/core/range.c
  src/core/send.c
  src/core/send.h
  src/inc/CMakeLists.txt
  src/inc/msquic_linux.h
  src/inc/quic_hashtable.h
  src/inc/quic_platform.h
  src/inc/quic_platform_linux.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/inc/quic_var_int.h
  src/inc/quic_versions.h
  src/platform/datapath_linux.c
  src/platform/toeplitz.c
Labels: Area: Build, OS: Ubuntu, external

#720 Fix Underflow for PostedBytes
  src/core/stream_send.c
Labels: App: spinquic, bug

#725 QNS Runner Pipeline
  .azure/azure-pipelines.qns.yml
  .azure/templates/run-qns.yml
Labels: App: quicinterop, Area: Pipeline

#726 Add Docker to Main Pipeline
  .azure/azure-pipelines.ci.yml
Labels: Area: Pipeline

#728 Add Dependency Support for Run QNS Template
  .azure/azure-pipelines.ci.yml
  .azure/templates/run-qns.yml
Labels: Area: Pipeline

#729 Update to clog 0.1.7
  scripts/install-powershell-docker.sh
  scripts/prepare-machine.ps1
  src/manifest/clog.sidecar
Labels: Area: Logging

#732 Fix trace decoder for CLOG
  src/manifest/clog.sidecar
  src/manifest/msquic.clog.cs
Labels: Area: Logging, bug

#733 Increase QNS Timeout to 25 min
  .azure/templates/run-qns.yml
Labels: App: quicinterop, Area: Pipeline

#736 Enable GitHub Code Scanning
  .github/workflows/codeql-analysis.yml
Labels: Area: Build, Area: Pipeline

#737 Fix For Loop Type Comparison Issues
  .github/workflows/codeql-analysis.yml
  src/core/frame.c
  src/core/library.c
Labels: bug

#738 Fix use after free in error condition in QuicConnAlloc
  src/core/connection.c
Labels: bug

#739 Set processor affinity before processor ideal proc in kernel mode
  src/inc/quic_platform_winkernel.h
Labels: OS: Windows Kernel Mode, bug

#740 Filter out failing ECT tests on internal pipeline
  .azure/azure-pipelines-int.ci.yml
Labels: Area: Testing, bug

#744 Fix invalid ptr in QuicBindingInitialize OOM Scenario
  src/core/binding.c
Labels: TLS: OpenSSL, TLS: Schannel, TLS: miTLS, bug

#745 Fix Datagram buffer resulting in a null deref in an OOM scenario
  src/platform/datapath_linux.c
Labels: OS: Ubuntu, bug

#748 More codeql
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
  src/core/unittest/SpinFrame.cpp
  src/core/unittest/VarIntTest.cpp
  src/platform/unittest/TlsTest.cpp
Labels: Area: Security

#747 Fix QuicConnAlloc OOM freeing invalid pointer
  src/core/connection.c
Labels: bug

#749 Fix Cleanup Bug in Binding
  src/core/binding.c
Labels: bug

#750 Integrate Latest QNS Pull Option
  .azure/azure-pipelines.ci.yml
  .azure/templates/run-qns.yml
Labels: App: quicinterop, Area: Pipeline

#751 Windows Usermode Datapath ECN Implementation
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  src/platform/datapath_winuser.c
Labels: OS: Windows User Mode

#723 Create initial performance counters.
  scripts/build.ps1
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/crypto.c
  src/core/datagram.c
  src/core/inline.c
  src/core/library.c
  src/core/library.h
  src/core/listener.c
  src/core/loss_detection.c
  src/core/operation.c
  src/core/packet.c
  src/core/packet_builder.c
  src/core/packet_builder.h
  src/core/stream.c
  src/core/stream_recv.c
  src/core/stream_send.c
  src/core/worker.c
  src/inc/msquic.h
  src/inc/msquichelper.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/unittest/TlsTest.cpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/tools/etw/library.c
  src/tools/etw/quicetw.h
  src/tools/etw/trace.c
  src/tools/etwlib/QuicEvents.h
  src/tools/spin/spinquic.cpp
Labels: Area: Logging, Area: Performance

#760 Fix Bad TLS Events
  src/manifest/clog.sidecar
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
Labels: Area: Logging

#761 Fix Incorrect numa node initialization with 2 numa nodes but 1 group
  src/inc/quic_platform_winuser.h
  src/platform/platform_winuser.c
Labels: OS: Windows User Mode, bug

#765 Add RPS Helper Script
  scripts/rps.ps1
Labels: Area: Performance

#768 Use Correct Size for Irp
  src/platform/datapath_winkernel.c
Labels: OS: Windows Kernel Mode, bug

#766 Clean up Logs on Failure
  scripts/log.ps1
  scripts/run-gtest.ps1
Labels: Area: Logging, Area: Testing

#767 Combine loopback and remote performance runs into a single script.
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.perf.yml
  .azure/templates/run-performance.yml
  scripts/build.ps1
  scripts/performance.ps1
  src/bin/winuser/pgo_x64/msquic.pgd
  src/bin/winuser/pgo_x86/msquic.pgd
Labels: Area: Performance

#769 Fix Abortive Stream Tests leaking a stream on the remote side.
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#770 Update kernel mode PGO file
  src/bin/winkernel/pgo_x64/msquic.pgd
Labels: OS: Windows Kernel Mode

#771 Remove a few unnecessary logs
  src/core/packet_builder.c
  src/platform/datapath_linux.c
Labels: Area: Logging

#774 Make Timeout Configurable in QNS Pipeline
  .azure/azure-pipelines.qns.yml
  .azure/templates/run-qns.yml
Labels: Area: Interop, Area: Pipeline

#764 Fix unaligned read and write ASAN error in stub TLS
  scripts/build.ps1
  src/platform/tls_stub.c
Labels: TLS: Stub

#776 Fix Thread Create Failure Crash
  src/core/timer_wheel.c
  src/core/worker.c
  src/inc/quic_platform_winkernel.h
  src/perf/bin/drvmain.cpp
Labels: OS: Windows (Kernel), bug

#779 Add .NET Core instructions to BUILD.md
  docs/BUILD.md
Labels: Area: Documentation

#775 Set affinity in kernel mode for RPS client
  src/inc/quic_platform_linux.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/perf/lib/RpsClient.cpp
Labels: Area: Performance, OS: Windows (Kernel), OS: Windows (User)

#781 Increase Perf Timeout
  .azure/azure-pipelines.perf.yml
  .azure/templates/run-performance.yml
Labels: Area: Performance

#762 Add Release Info for v1.0
  README.md
  docs/Support.md
Labels: Area: Documentation

#785 Perf Protocol Refactor
  scripts/RemoteTests.json
  src/perf/lib/CMakeLists.txt
  src/perf/lib/PerfCommon.h
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/RpsClient.cpp
  src/perf/lib/RpsClient.h
  src/perf/lib/RpsServer.cpp
  src/perf/lib/RpsServer.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
  src/perf/lib/ThroughputServer.cpp
  src/perf/lib/ThroughputServer.h
  src/perf/lib/perflib.kernel.vcxproj
  src/perf/lib/quicmain.cpp
Labels: Area: Performance

#784 Fix unaligned write in QuicDatagramSendComplete
  src/core/datagram.c
Labels: Area: Core, bug

#782 Switch CFLAGS based on CMAKE_BUILD_TYPE
  CMakeLists.txt
  src/core/crypto_tls.c
  src/inc/CMakeLists.txt
  src/perf/lib/ThroughputClient.cpp
  src/platform/hashtable.c
Labels: Area: Build, external

#786 Close remote stream in stream shutdown for abortive tests
  src/test/lib/DataTest.cpp
Labels: Area: Testing, bug

#787 Fix issues with perf test matrix
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance

#789 Throw Away Connections from Bad Initial Packets
  src/core/connection.c
  src/core/connection.h
  src/manifest/clog.sidecar
Labels: Area: Core, bug

#790 Remove Packet Number from Packet Drop Events
  src/core/packet.c
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/tools/etw/quicetw.h
  src/tools/etw/trace.c
Labels: Area: Core, Area: Logging

#791 Limit number of cores in RPS Client test, fix RPS thread out of range bug
  src/perf/lib/RpsClient.cpp
Labels: Area: Performance, bug

#793 Add vpid and vtid to lttng logs
  scripts/log.ps1
  scripts/run_endpoint.sh
Labels: Area: Logging, OS: Ubuntu
