Repository microsoft/msquic, pull requests merged in 2021-05, with the labels that each got.

#1536 Increase BVT timeout
  .azure/templates/run-bvt.yml
Labels: Area: Testing

#1539 Increase linux regression thresholds
  scripts/RemoteTests.json
Labels: Area: Performance, OS: Ubuntu

#1538 Log exception if a failure occurs in BVT run
  scripts/run-gtest.ps1
Labels: Area: Testing

#1540 Simplify Test Scripts
  .azure/templates/run-bvt.yml
  scripts/run-gtest.ps1
  scripts/test.ps1
Labels: Area: Pipeline, Area: Testing

#1537 Add support for randomly failing memory allocations to SpinQuic.
  CMakeLists.txt
  scripts/build.ps1
  scripts/spin.ps1
  src/core/binding.c
  src/core/library.c
  src/core/listener.c
  src/core/lookup.c
  src/core/stream.c
  src/inc/msquichelper.h
  src/inc/msquicp.h
  src/inc/quic_platform.h
  src/platform/hashtable.c
  src/platform/platform_internal.h
  src/platform/platform_posix.c
  src/platform/platform_winkernel.c
  src/platform/platform_winuser.c
  src/tools/spin/spinquic.cpp
Labels: Area: Testing

#1543 Fix crypto buffer drain when switching to 1-RTT keys.
  src/core/crypto.c
Labels: Area: Core, bug

#1547 Fix Handshake Stall Bug
  src/core/loss_detection.c
  src/core/packet_builder.c
Labels: Area: Core, Bug: Core

#1551 Add exit code debugging to kernel mode test runs
  scripts/run-gtest.ps1
Labels: Area: Testing

#1550 Only compile in RSS support on linux if CBPF macro is found
  src/platform/datapath_epoll.c
Labels: Area: Build, OS: Ubuntu

#1554 Increase BVT Timeout to 60 Minutes
  .azure/templates/run-bvt.yml
Labels: Area: Performance, Area: Testing

#1545 Refactor/Improve MsQuic.hpp Header
  src/inc/msquic.hpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#1556 Fix unused variable error if CBPF macro does not exist
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu

#1557 Fix Handshake Stall Bug (#1547)
  src/core/loss_detection.c
  src/core/packet_builder.c
Labels: Bug: Core

#1548 Properly update the start point of the current key phase to decide old or new encryption keys
  src/core/connection.c
  src/core/crypto.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Core, Bug: Core

#1559 Switch kernel mode BVT's back to Full.Light logging
  .azure/azure-pipelines.ci.yml
Labels: Area: Testing, OS: Windows (Kernel)

#1564 Read commit url in try for perf previous data results
  scripts/performance-helper.psm1
Labels: Area: Performance, Area: Pipeline

#1562 Use correct random loss args parameter for key update random loss test
  src/test/bin/quic_gtest.cpp
Labels: Area: Testing

#1568 Only check stateless reset CID against non-retired CIDs
  src/core/connection.c
Labels: Area: Core

#1541 Fix more SpinQuic random allocation failure bugs
  .azure/templates/run-spinquic.yml
  scripts/run-executable.ps1
  scripts/spin.ps1
  src/core/cid.h
  src/core/connection.c
  src/core/crypto.c
  src/core/library.c
  src/core/loss_detection.c
  src/core/loss_detection.h
  src/core/packet_builder.c
  src/core/send.c
  src/core/stream.c
  src/core/stream_set.c
  src/core/stream_set.h
  src/platform/datapath_winuser.c
  src/platform/platform_winuser.c
  src/platform/tls_openssl.c
  src/plugins/dbg/quictypes.h
  src/plugins/dbg/worker.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Core, Area: Stress, Area: Testing

#1573 Reenable Tests with OpenSSL
  .azure/azure-pipelines.ci.yml
Labels: Area: Pipeline, Area: Testing, TLS: OpenSSL

#1576 Add Slow Receiver Test
  src/inc/msquic.hpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#1577 Fix Bug in Allocation Failure Path of OnPacketSent
  src/core/loss_detection.c
  src/core/sent_packet_metadata.h
Labels: Area: Core, Bug: Core

#1578 Check Version against App Configured
  src/core/crypto.c
  src/core/crypto.h
  src/core/unittest/TicketTest.cpp
Labels: Area: Core, Bug: Core

#1579 Onboard SpinQuic Alloc Failure to CI
  .azure/azure-pipelines.ci.yml
  src/core/cid.h
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/inline.c
  src/core/loss_detection.c
  src/core/path.c
  src/core/path.h
  src/core/send.c
Labels: Area: Pipeline, Area: Stress, Area: Testing

#1580 Increase Throughput Perf Threshold to 10%
  scripts/RemoteTests.json
Labels: Area: Performance, Area: Pipeline

#1581 Add Stream Shutdown Complete Flag
  src/core/stream.c
  src/inc/msquic.h
  src/manifest/clog.sidecar
Labels: Area: API

#1583 Add error code hex values to msquic public headers
  src/inc/msquic_posix.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
Labels: Area: Documentation

#1572 Add support receiving different API Table Versions
  docs/API.md
  docs/api/MsQuicClose.md
  docs/api/MsQuicOpen.md
  docs/api/MsQuicOpenVersion.md
  src/bin/darwin/exports.txt
  src/bin/linux/exports.txt
  src/bin/winkernel/msquic.src
  src/bin/winkernel/msquicpriv.src
  src/bin/winuser/msquic.def
  src/bin/winuser_fuzz/msquic_fuzz.def
  src/core/library.c
  src/core/precomp.h
  src/inc/msquic.h
Labels: Area: API

#1587 Switch test error status messages from dec to hex
  src/test/lib/TestConnection.cpp
Labels: Area: Testing

#1584 Add test to fail every Nth allocation.
  src/core/library.c
  src/core/send.c
  src/inc/msquic.hpp
  src/platform/platform_posix.c
  src/platform/platform_winkernel.c
  src/platform/platform_winuser.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Stress, Area: Testing

#1589 Disable nth allocation failure test on linux
  .azure/azure-pipelines.ci.yml
Labels: Area: Testing, OS: Ubuntu, OS: macOS

#1590 Fail interop tests in CI if interop crashes
  .azure/templates/run-quicinterop.yml
  scripts/interop.ps1
Labels: Area: Interop, Area: Pipeline

#1591 Fix validation shutdown test to not deref null
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing, OS: macOS

#1593 Run release mode tests in CI
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  scripts/test.ps1
  src/inc/msquicp.h
  src/test/bin/quic_gtest.cpp
  src/test/lib/DatagramTest.cpp
Labels: Area: Testing

#1595 Fix pool used for internal CI builds
  .azure/azure-pipelines-int.ci.yml
Labels: Area: Pipeline

#1585 Disable pool allocator when memory allocation failures are enabled.
  src/core/crypto.c
  src/core/library.c
  src/core/packet_builder.c
  src/core/send.c
  src/inc/msquic.hpp
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winuser.h
  src/test/bin/quic_gtest.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Stress, Area: Testing

#1597 Port Release Testing to 1.1
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.qns.yml
  .azure/templates/create-package.yml
  scripts/test.ps1
  src/inc/msquic.ver
  src/test/bin/quic_gtest.cpp
  src/test/lib/DatagramTest.cpp
Labels: Area: Pipeline, Area: Testing, OS: Windows (Kernel), OS: Windows (User)

#1598 Actually Run Kernel Tests for Release
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  src/test/bin/quic_gtest.cpp
Labels: Area: Pipeline, Area: Testing, OS: Windows (Kernel)

#1600 API Doc: StreamOpen
  docs/api/RegistrationOpen.md
  docs/api/StreamOpen.md
Labels: Area: Documentation

#1607 API Doc: StreamShutdown
  docs/api/StreamShutdown.md
Labels: Area: Documentation

#1602 API Doc: StreamSend
  docs/api/StreamSend.md
Labels: Area: Documentation

#1601 API Doc: StreamStart
  docs/Streams.md
  docs/api/StreamStart.md
Labels: Area: Documentation

#1609 Reenable Alloc Failures in CI
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  src/core/send.c
  src/tools/spin/spinquic.cpp
Labels: Area: Pipeline, Area: Stress, Area: Testing

#1599 Document TAT usage
  docs/Diagnostics.md
  docs/images/tat.png
  docs/tat/default.tat
  docs/tat/packets.tat
Labels: Area: Documentation

#1613 SpinQuic: Pend some receives and try resuming them.
  src/tools/spin/spinquic.cpp
Labels: Area: Stress, Area: Testing

#1614 SpinQuic: Add partial receive support.
  src/core/crypto.c
  src/core/send.c
  src/tools/spin/spinquic.cpp
Labels: Area: Stress, Area: Testing

#1617 Fix typos in BUILD.md
  docs/BUILD.md
Labels: Area: Build

#1618 Tweak EstimatedWnd calc in QuicCongestionControlGetSendAllowance
  src/core/congestion_control.c
Labels: Area: Core, Area: Performance

#1620 TSG: Why is this API Failing?
  docs/Diagnostics.md
  docs/TSG.md
Labels: Area: Documentation

#1621 Improve Handling of Ephemeral Port Reuse Scenario
  src/core/library.c
  src/manifest/clog.sidecar
Labels: Area: Core

#1622 API Doc: StreamClose
  docs/api/StreamClose.md
Labels: Area: Documentation

#1624 Fix Typo in StreamClose.md
  docs/api/StreamClose.md
Labels: Area: Documentation

#1623 Add Link to List of Good First Issues
  README.md
Labels: Area: Documentation

#1625 Add ConnectionOpen docs.
  docs/api/ConnectionOpen.md
Labels: Area: Documentation

#1626 TSG: Application Data Blocked
  docs/TSG.md
  docs/images/tx-blocked-state.png
Labels: Area: Documentation

#1628 Expand ConnectionStart doc.
  docs/api/ConnectionStart.md
Labels: Area: Documentation

#1629 Expand ConnectionShutdown doc.
  docs/api/ConnectionShutdown.md
Labels: Area: Documentation

#1630 Documentation
  README.md
  docs/BUILD.md
  docs/TEST.md
Labels: Area: Documentation

#1635 More TEST.md
  docs/TEST.md
Labels: Area: Documentation, Area: Testing

#1638 Expand ConnectionClose doc.
  docs/api/ConnectionClose.md
Labels: Area: Documentation

#1639 Add TAT Filter for API Failures
  docs/TSG.md
  docs/tat/api.tat
Labels: Area: Documentation

#1640 Add Some ... to Test.md
  docs/TEST.md
Labels: Area: Documentation

#1641 Refactor settings to be a separate document from deployment.
  docs/Deployment.md
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
Labels: Area: Documentation

#1588 Send ACK Frequency Updates
  src/core/connection.c
  src/core/connection.h
  src/core/loss_detection.c
  src/core/send.c
  src/core/send.h
  src/core/sent_packet_metadata.h
  src/manifest/clog.sidecar
Labels: Area: Core, Area: Performance

#1642 Define constant for max connection close reason phrase length.
  src/core/connection.c
  src/core/quicdef.h
Labels: Area: Core

#1643 Expand listener documentation.
  docs/API.md
  docs/Settings.md
  docs/api/ConnectionClose.md
  docs/api/ConnectionSetConfiguration.md
  docs/api/GetParam.md
  docs/api/ListenerClose.md
  docs/api/ListenerOpen.md
  docs/api/ListenerStart.md
  docs/api/ListenerStop.md
  docs/api/QUIC_SETTINGS.md
  docs/api/SetParam.md
Labels: Area: Documentation

#1646 Fix Windows User Mode Build Breaks from VS v16.10 Update
  src/inc/quic_platform.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
Labels: Area: Build, OS: Windows (User)

#1649 One More arm64 WinUser Build Fix
  src/inc/quic_platform_winuser.h
Labels: Area: Build, OS: Windows (User)

#1655 Fix grammar
  docs/api/StreamOpen.md
Labels: Area: Documentation, external

#1656 Add workaround for Kernel Mode builds using wrong CRT
  src/inc/msquic.hpp
  src/inc/quic_platform.h
  src/perf/bin/drvmain.cpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/Tcp.cpp
  src/perf/lib/ThroughputClient.cpp
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/bin/winkernel/driver.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Build

#1653 Copy Handshake Sizes in Statistics
  src/core/connection.c
Labels: Area: API, Area: Core

#1645 Refactor POSIX Error Codes
  src/inc/msquic_posix.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/tools/sample/sample.cpp
Labels: OS: Ubuntu, OS: macOS

#1657 Cherry pick VS 16.10 build updates to 1.1
  src/inc/msquic.hpp
  src/inc/quic_platform.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/perf/bin/drvmain.cpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/Tcp.cpp
  src/perf/lib/ThroughputClient.cpp
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/bin/winkernel/driver.cpp
Labels: Area: Build

#1658 Cherry pick VS 16.10 build updates to 1.0
  src/inc/msquic.hpp
  src/inc/quic_platform.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/perf/bin/drvmain.cpp
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/bin/winkernel/driver.cpp
Labels: Area: Build

#1651 Ignore how the transports shutdown in key update random loss test
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing

#1659 cast byte arrays in prep to move to manifested ETW; this change was m…
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/core/library.c
  src/core/listener.c
  src/core/packet.c
  src/core/version_neg.c
  src/inc/quic_trace.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Logging

#1661 fix a few non-obvious mistakes in quic where the durable ID's conflic…
  src/core/connection.c
  src/core/send.c
  src/core/stream_send.c
  src/manifest/clog.sidecar
  src/perf/bin/drvmain.cpp
  src/platform/datapath_winkernel.c
Labels: Area: Logging
