Repository microsoft/msquic, pull requests merged in 2021-02, with the labels that each got.

#1205 FAQ for Linux Handle Limit Issue
  docs/Diagnostics.md
Labels: Area: Documentation

#1206 Fix missing field initializer in TlsTest
  src/platform/unittest/TlsTest.cpp
Labels: Area: Testing, bug

#1208 Refactor Certificate Received Code Paths
  .azure/azure-pipelines.ci.yml
  src/core/connection.c
  src/core/crypto.c
  src/inc/msquic.h
  src/inc/quic_tls.h
  src/manifest/clog.sidecar
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
  src/platform/unittest/TlsTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: TLS: OpenSSL, TLS: Schannel, TLS: Stub, TLS: miTLS

#1207 Add Logs and Fix TCP Perf Code
  .azure/azure-pipelines.periodic.yml
  .azure/azure-pipelines.wanperf.yml
  .azure/templates/run-wanperf.yml
  scripts/emulated-performance.ps1
  src/manifest/clog.sidecar
  src/perf/lib/PerfServer.cpp
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
Labels: Area: Logging, Area: Performance, bug

#1210 Fix Emulated Perf Reorder Bug
  scripts/emulated-performance.ps1
Labels: Area: Performance, bug

#1209 Improve Random Loss Test Cases
  src/inc/msquic.hpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing, bug

#1212 Performance Branch Changes for RPS Latency
  powershell/generate-graphs.ps1
Labels: Area: Performance

#1211 RPS Latency Test Case
  scripts/RemoteTests.json
Labels: Area: Performance, Area: Pipeline

#1214 Add Linux performance testing
  .azure/azure-pipelines.ci.yml
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance, Area: Pipeline, OS: Ubuntu

#1173 Version Negotiation Extension
  .azure/templates/run-bvt.yml
  docs/Versions.md
  src/core/CMakeLists.txt
  src/core/binding.c
  src/core/binding.h
  src/core/configuration.c
  src/core/connection.c
  src/core/connection.h
  src/core/core.kernel.vcxproj
  src/core/crypto.c
  src/core/crypto.h
  src/core/crypto_tls.c
  src/core/frame.h
  src/core/library.c
  src/core/library.h
  src/core/precomp.h
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/transport_params.h
  src/core/unittest/CMakeLists.txt
  src/core/unittest/TransportParamTest.cpp
  src/core/unittest/VersionNegExtTest.cpp
  src/core/version_neg.c
  src/core/version_neg.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/quic_platform.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/manifest/msquic.clog.cs
  src/manifest/msquic.clog_config
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
  src/tools/etw/quicetw.h
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/ping/PingConnection.cpp
  src/tools/sample/sample.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Protocol Updates

#1221 Remove Unnecessary Semicolons
  src/inc/msquic.h
Labels: Area: Build

#1222 Tweak Low Volume Events
  src/core/connection.c
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
Labels: Area: Logging, Area: Performance

#1217 Add support for RSS on linux
  scripts/performance-helper.psm1
  src/inc/quic_platform_linux.h
  src/perf/lib/RpsClient.cpp
  src/perf/lib/RpsClient.h
  src/perf/lib/quicmain.cpp
  src/platform/datapath_linux.c
  src/platform/platform_linux.c
Labels: Area: Performance, OS: Ubuntu

#1225 Fix incorrect struct being used for custom cert validation tests
  src/test/bin/quic_gtest.cpp
Labels: Area: Testing, bug

#1227 Telemetry Assert Events
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  scripts/build.ps1
  src/bin/winkernel/msquic.kernel.vcxproj
  src/bin/winkernel/msquicpriv.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/inc/quic_platform_linux.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/platform/platform_winkernel.c
  src/platform/tls_stub.c
Labels: Area: Logging

#1229 Fix Test Code Leak on Failure
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#1230 Fix leak in TransportParameterTest for VNE.
  src/core/unittest/TransportParamTest.cpp
Labels: Area: Testing, bug

#1226 macOS Support
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-user.yml
  CMakeLists.txt
  scripts/build.ps1
  scripts/install-build-artifacts.ps1
  scripts/interop.ps1
  scripts/log.ps1
  scripts/prepare-machine.ps1
  scripts/spin.ps1
  scripts/test.ps1
  scripts/update-sidecar.ps1
  src/bin/CMakeLists.txt
  src/bin/darwin/exports.txt
  src/core/unittest/CMakeLists.txt
  src/inc/msquic.h
  src/inc/msquic_posix.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/manifest/clog.sidecar
  src/manifest/msquic.clog_config
  src/perf/lib/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/platform_internal.h
  src/platform/platform_posix.c
  src/platform/storage_posix.c
  src/platform/unittest/CMakeLists.txt
  src/platform/unittest/CryptTest.cpp
Labels: OS: macOS

#1231 Fix calling memset or memcpy with 0 length and null pointer
  src/test/lib/TestStream.h
Labels: Area: Testing, OS: Ubuntu, OS: Windows (Kernel), OS: Windows (User), OS: macOS, bug

#1233 Fix distribution of linux binaries
  scripts/package-distribution.ps1
  src/inc/msquic_posix.h
Labels: OS: Ubuntu

#1236 Fix stub tls stateless key generation
  src/platform/tls_stub.c
Labels: TLS: Stub

#1235 Fix lookup debug helpers to use correct variables
  src/core/lookup.c
Labels: Area: Build

#1239 CXPLAT_TEL_ASSERT Log Only
  src/core/connection.c
  src/core/connection.h
  src/core/library.c
  src/core/library.h
  src/core/registration.c
  src/core/registration.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/plugins/dbg/quictypes.h
Labels: Area: Logging

#1238 Support Spurious Congestion Event
  .azure/azure-pipelines.wanperf.yml
  src/core/congestion_control.c
  src/core/congestion_control.h
  src/core/loss_detection.c
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
Labels: Area: Core, Area: Performance

#1243 Client Certificate Support for Schannel
  CMakeLists.txt
  src/inc/msquic.h
  src/inc/msquichelper.h
  src/inc/quic_platform.h
  src/perf/bin/appmain.cpp
  src/platform/selfsign_capi.c
  src/platform/selfsign_openssl.c
  src/platform/selfsign_stub.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
  src/test/bin/quic_gtest.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: API, TLS: Schannel

#1093 Support Password Protected Certificate Files
  .azure/templates/build-config-user.yml
  CMakeLists.txt
  src/inc/msquic.h
  src/platform/cert_capi.c
  src/platform/tls_openssl.c
  src/tools/sample/sample.cpp
Labels: Area: Security, TLS: OpenSSL

#1241 Add support for querying handshake info
  .azure/azure-pipelines.ci.yml
  src/inc/msquic.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: Area: API, TLS: OpenSSL, TLS: Schannel

#1248 New Stream Start Flag for Shutdown on Failure
  src/core/stream.c
  src/inc/msquic.h
  src/test/lib/ApiTest.cpp
Labels: Area: API

#1250 Stream Trace to Verbose
  src/core/stream_recv.c
  src/manifest/clog.sidecar
Labels: Area: Logging

#1228 Periodically Snap-shot Performance Counters
  src/core/inline.c
  src/core/library.c
  src/core/library.h
  src/core/timer_wheel.c
  src/core/timer_wheel.h
  src/core/worker.c
  src/inc/quic_platform_posix.h
  src/platform/inline.c
Labels: Area: Logging

#1244 Add more bad-case testing of Resumption Tickets
  src/core/crypto.c
  src/core/unittest/TicketTest.cpp
  src/manifest/clog.sidecar
Labels: Area: Core, Area: Testing

#1255 Update Deployment.md
  docs/Deployment.md
Labels: Area: Documentation, external

#1253 Fix Client Certificate Test
  src/platform/selfsign_capi.c
Labels: Area: Testing

#1263 Fix memory leak in ResumptionTicketTest
  src/core/unittest/TicketTest.cpp
Labels: Area: Testing, bug

#1265 Windows build with openssl option requires perl
  docs/BUILD.md
Labels: Area: Documentation, external

#1269 Move pthread asserts away from being inline
  src/platform/platform_posix.c
Labels: OS: Ubuntu, OS: macOS

#1259 fix posix QuicAddrToString
  src/inc/msquic_posix.h
  src/platform/unittest/CMakeLists.txt
  src/platform/unittest/PlatformTest.cpp
Labels: Area: Testing

#1257 fix compilation on macOS with XCode 11.5
  src/platform/datapath_kqueue.c
Labels: Area: Build, OS: macOS

#1272 Add QUIC_STATUS_STREAM_LIMIT_REACHED
  docs/api/QUIC_STATUS.md
  src/core/stream_set.c
  src/inc/msquic_posix.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/inc/msquichelper.h
  src/test/lib/ApiTest.cpp
Labels: Area: API, Area: Core

#1271 Switch assert for validation pending in validation complete to a TEL assert
  src/core/crypto.c
Labels: Area: Core

#1273 Signal condition variable in CxPlatEventSet while holding lock
  src/platform/platform_posix.c
Labels: OS: Ubuntu, OS: macOS

#1261 prepare-machine: Detect default PS and warn dev to install the latest
  scripts/prepare-machine.ps1
Labels: Area: Build

#1254 Add unreachable support to datapath_kqueue, add synchronous case to datapath_epoll
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
Labels: OS: Ubuntu, OS: macOS

#1275 Rename CxPlatPlat to CxPlat
  src/inc/msquichelper.h
  src/inc/quic_platform.h
  src/perf/bin/appmain.cpp
  src/platform/selfsign_capi.c
  src/platform/selfsign_openssl.c
  src/platform/selfsign_stub.c
  src/platform/unittest/TlsTest.cpp
  src/test/bin/quic_gtest.cpp
  src/tools/spin/spinquic.cpp
Labels: bug

#1258 Add support for validating certificates in openssl using the windows cert store
  src/inc/msquic.h
  src/inc/quic_cert.h
  src/inc/quic_platform.h
  src/inc/quic_platform_winuser.h
  src/platform/cert_capi.c
  src/platform/cert_capi_openssl.c
  src/platform/cert_openssl.c
  src/platform/cert_stub.c
  src/platform/datapath_winuser.c
  src/platform/platform_winuser.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
Labels: TLS: OpenSSL

#1277 More Periodic Perf Data
  .azure/azure-pipelines.periodic.yml
  scripts/FullRunRPS.json
Labels: Area: Performance

#1278 Don't affinitize datapath threads on macOS
  src/platform/datapath_kqueue.c
Labels: OS: macOS

#1260 improve datapath on macOS
  .azure/azure-pipelines.ci.yml
  src/inc/msquic_posix.h
  src/inc/quic_platform_posix.h
  src/platform/datapath_kqueue.c
Labels: OS: macOS

#1276 Fix CRYPTO fragmentation handshake failure on client
  src/inc/quic_platform.h
  src/manifest/clog.sidecar
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: TLS: Schannel, bug

#1281 Use no wait flag when cancelling lttng
  scripts/log.ps1
Labels: Area: Logging, OS: Ubuntu

#1283 Add MacOS Interop
  .azure/azure-pipelines.ci.yml
  src/tools/interop/interop.cpp
Labels: Area: Pipeline, OS: macOS

#1262 Add Kernel mode test for client certificates.
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  src/inc/quic_driver_helpers.h
  src/perf/bin/appmain.cpp
  src/perf/bin/drvmain.cpp
  src/perf/bin/perfioctls.h
  src/platform/selfsign_capi.c
  src/platform/tls_schannel.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/BasicTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/DatagramTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/QuicDrill.cpp
Labels: Area: Security, OS: Windows (Kernel), TLS: Schannel

#1213 New Session Ticket Encryption Key API
  CMakeLists.txt
  src/core/configuration.c
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/quic_tls.h
  src/platform/CMakeLists.txt
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: API, TLS: OpenSSL, TLS: Schannel, TLS: Stub, TLS: miTLS

#1280 Implement UDP send buffering support in Linux
  src/platform/datapath_epoll.c
  src/platform/platform_posix.c
Labels: Area: Performance, OS: Ubuntu

#1274 Loss Detection Immediately
  src/core/loss_detection.c
  src/core/loss_detection.h
  src/core/packet_builder.c
  src/core/path.c
Labels: Area: Core, bug

#1204 Port Control Protocol Support
  src/core/binding.c
  src/inc/quic_datapath.h
  src/inc/quic_pcp.h
  src/inc/quic_platform.h
  src/perf/lib/quicmain.cpp
  src/platform/CMakeLists.txt
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/pcp.c
  src/platform/platform.kernel.vcxproj
  src/platform/platform_internal.h
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/CMakeLists.txt
  src/tools/attack/attack.cpp
  src/tools/pcp/CMakeLists.txt
  src/tools/pcp/pcp.cpp
Labels: Area: Protocol Updates

#995 Add Delay Send API Flag
  src/core/api.c
  src/core/loss_detection.c
  src/core/send.c
  src/core/send.h
  src/core/stream.c
  src/core/stream.h
  src/core/stream_recv.c
  src/core/stream_send.c
  src/inc/msquic.h
  src/perf/lib/RpsClient.cpp
  src/perf/lib/RpsClient.h
  src/plugins/dbg/quictypes.h
  src/test/lib/ApiTest.cpp
  src/test/lib/EventTest.cpp
Labels: Area: API, Area: Core, Area: Performance

#1288 Fix a Few Casting Errors
  src/core/congestion_control.c
  src/inc/quic_platform_posix.h
  src/platform/inline.c
Labels: OS: Ubuntu, OS: macOS

#1289 Start adding support for arm64 builds on macOS
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  scripts/build.ps1
  src/platform/platform_posix.c
Labels: Area: Build, OS: macOS

#1292 Remove OpenSSL interface folder in build
  CMakeLists.txt
Labels: Area: Build

#1279 Add UDP receive batching support to linux datapath
  src/platform/datapath_epoll.c
Labels: Area: Performance, OS: Ubuntu

#1293 Remove Unnecessary Outstanding Send Counter
  src/platform/datapath_winkernel.c
Labels: Area: Performance, OS: Windows (Kernel)

#1296 Add TLS Overview
  docs/TLS.md
Labels: Area: Documentation

#1298 Add script to merge macos binaries
  scripts/merge-darwin.ps1
Labels: Area: Build, OS: macOS

#1294 Ensure pended sends get added to correct queue
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
Labels: OS: Ubuntu, OS: macOS, bug

#1301 API Documentation Improvements
  docs/API.md
  docs/api/ConnectionSendResumptionTicket.md
  docs/api/ConnectionSetConfiguration.md
  docs/api/QUIC_API_TABLE.md
  src/inc/msquic.h
Labels: Area: Documentation
