Repository microsoft/msquic, pull requests merged in 2021-06, with the labels that each got.

#1665 Move AZP Setup to Docs
  docs/AZP.md
Labels: Area: Documentation

#1664 Correctly Write Out Version
  src/core/library.c
Labels: Area: Core

#1666 Enable TLS Secrets Support for Windows Kernel
  src/core/core.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
Labels: OS: Windows (Kernel)

#1563 Add DPLPMTUD support
  src/core/CMakeLists.txt
  src/core/binding.c
  src/core/configuration.c
  src/core/connection.c
  src/core/connection.h
  src/core/core.kernel.vcxproj
  src/core/crypto.c
  src/core/datagram.c
  src/core/inline.c
  src/core/library.c
  src/core/loss_detection.c
  src/core/mtu_discovery.c
  src/core/mtu_discovery.h
  src/core/packet_builder.c
  src/core/path.c
  src/core/path.h
  src/core/precomp.h
  src/core/quicdef.h
  src/core/send.c
  src/core/send.h
  src/core/sent_packet_metadata.h
  src/core/settings.c
  src/core/settings.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/plugins/dbg/connection.cpp
  src/plugins/dbg/packet.cpp
  src/plugins/dbg/quictypes.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/CMakeLists.txt
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/MtuTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Core

#1671 Remove feature branches from automatically building in CI
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.plugins.yml
  .azure/templates/post-process-performance.yml
  .azure/templates/post-process-periodic-performance.yml
  .github/workflows/codeql-analysis.yml
Labels: Area: Build, Area: Pipeline

#1670 Set has random loss flag for key update test
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing

#1672 Fix CI build from removing feature build
  .azure/templates/post-process-performance.yml
Labels: Area: Pipeline

#1669 TSG: Debugging API Deadlocks
  docs/TSG.md
  src/core/api.c
  src/core/api.h
  src/core/registration.c
  src/core/registration.h
  src/inc/msquic.h
Labels: Area: Documentation

#1674 Document Known Issue for Previous Releases
  docs/Release.md
Labels: Area: Documentation

#1673 Reduce minimum MTU to 1248
  src/core/mtu_discovery.c
  src/core/quicdef.h
  src/test/lib/MtuTest.cpp
Labels: Area: Core

#1676 Release Notes for v1.4
  docs/Release.md
Labels: Area: Documentation

#1677 Update main to v1.5
  .azure/azure-pipelines.qns.yml
  .azure/templates/create-package.yml
  src/inc/msquic.ver
Labels: Area: Core

#1679 Update ConnectionStart docs to use QUIC specific address family macro
  docs/api/ConnectionStart.md
Labels: Area: Documentation

#1678 Add macOS error codes to msquic_posix.h
  src/inc/msquic_posix.h
Labels: OS: macOS

#1650 Add helper script for grabbing build config and artifact directory for local machine
  scripts/build.ps1
  scripts/get-buildconfig.ps1
  scripts/spin.ps1
  scripts/test.ps1
Labels: Area: Build

#1682 Misc Docs Improvements
  .github/CONTRIBUTING.md
  README.md
  docs/FAQ.md
Labels: Area: Documentation

#1683 Properly allow default parameters for get-buildconfig
  scripts/get-buildconfig.ps1
Labels: Area: Build

#1684 Remove Assert in CxPlatSendDataFinalizeSendBuffer
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winuser.c
Labels: OS: Ubuntu, OS: Windows (User), OS: macOS

#1686 Decrement Ref Count before Uninitializing Binding
  src/core/library.c
Labels: Area: Core

#1689 Don't allow stream to be enabled when stop sending has been set
  src/core/stream_recv.c
  src/tools/spin/spinquic.cpp
Labels: Area: Core, Area: Stress

#1690 Increase Try Count for Test Force Functions
  src/test/lib/TestConnection.cpp
Labels: Area: Testing

#1693 Fix PeerAccpeted Flag for Start Complete Event
  src/core/stream.c
  src/test/lib/EventTest.cpp
Labels: Area: API, Area: Core, Bug: Core

#1692 add basic packaging script
  scripts/make-packages.sh
Labels: Area: Pipeline

#1699 Fix ConnectionOpen link
  docs/api/ConnectionStart.md
Labels: Area: Documentation

#1694 Test sign drivers for kernel mode testing.
  .azure/templates/run-bvt.yml
  scripts/prepare-machine.ps1
  scripts/run-gtest.ps1
Labels: Area: Testing

#1704 Run Distribution Stage on PRs
  .azure/azure-pipelines.ci.yml
Labels: Area: Pipeline

#1705 Fix release kernel BVT by enabling test signing.
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
Labels: Area: Testing, Bug: Test/Tool

#1706 Switch uses of min and max to CXPLAT_MIN and CXPLAT_MAX
  src/core/congestion_control.c
  src/core/connection.c
  src/core/connection.h
  src/core/library.c
  src/core/loss_detection.c
  src/core/mtu_discovery.c
  src/core/packet.h
  src/core/stream.c
  src/core/stream_recv.c
  src/core/stream_set.c
  src/inc/msquichelper.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/perf/bin/appmain.cpp
  src/perf/lib/PerfServer.cpp
  src/platform/unittest/TlsTest.cpp
  src/test/lib/TestStream.cpp
Labels: OS: Ubuntu, OS: macOS

#1652 Fix Client Cert Tests (Windows Kernel)
  src/platform/tls_schannel.c
  src/test/bin/quic_gtest.cpp
Labels: OS: Windows (Kernel), TLS: Schannel

#1695 create Linux packages from package-distribution.ps1
  .azure/templates/build-distribution.yml
  scripts/make-packages.sh
  scripts/package-distribution.ps1
  scripts/prepare-machine.ps1
Labels: Area: Build, Area: Pipeline

#1707 Add Load Balancing Tests
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/library.c
  src/core/listener.c
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/msquicp.h
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
  src/tools/spin/spinquic.cpp
Labels: Area: Testing

#1712 Fix kernel perf finally script
  scripts/performance.ps1
Labels: Area: Performance, OS: Windows (Kernel)

#1608 Zero Length Send + QUIC_SEND_FLAG_START
  src/core/stream_send.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/EventTest.cpp
Labels: Area: API, Area: Core

#1718 Make stateless reset token generation per-processor.
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/library.c
  src/core/library.h
  src/core/send.c
Labels: Area: Performance

#1724 Fix QUIC_SETTINGS Size Validation Logic
  src/core/configuration.c
  src/core/connection.c
  src/core/settings.c
  src/core/settings.h
Labels: Area: Core, Bug: Core

#1723 Setting for Binding Stateless Operations
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
  src/core/binding.c
  src/core/quicdef.h
  src/core/settings.c
  src/inc/msquic.h
  src/manifest/clog.sidecar
Labels: Area: API, Area: Core, Area: Documentation

#1725 Remove registry accessable force bugcheck
  src/core/stream.c
Labels: Area: Core

#1729 change -Ofast to -O3
  CMakeLists.txt
  docs/BUILD.md
Labels: Area: Build, OS: Ubuntu, external

#1741 Update LB Test to Handle Addr In Use Failures
  src/inc/msquic.hpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing, Bug: Test/Tool

#1752 Switch sample to be built in C instead of C++
  src/tools/sample/CMakeLists.txt
  src/tools/sample/sample.c
Labels: Area: Build

#1739 Fix socket cleanup on allocation failure in kqueue and epoll datapaths
  .azure/azure-pipelines.ci.yml
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winuser.c
Labels: Bug: Platform, OS: Ubuntu, OS: macOS

#1753 Add documentation for QUIC_CREDENTIAL_CONFIG
  docs/api/QUIC_CREDENTIAL_CONFIG.md
Labels: Area: Documentation

#1755 Free DefaultCompatibilityList on initialization failure
  src/core/library.c
  src/tools/spin/spinquic.cpp
Labels: Bug: Core

#1754 Correct direction of pthread affinity logs
  src/platform/platform_posix.c
Labels: OS: Ubuntu, OS: macOS

#1751 Local UDP Port Sharing for Connected Sockets (Linux only)
  CMakeLists.txt
  src/core/binding.c
  src/core/library.c
  src/inc/msquic.hpp
  src/inc/quic_datapath.h
  src/platform/datapath_epoll.c
  src/platform/platform_internal.h
  src/platform/unittest/DataPathTest.cpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/tools/lb/loadbalancer.cpp
Labels: Area: Core, OS: Ubuntu

#1759 More SpinQuic Parallelization
  src/tools/spin/spinquic.cpp
Labels: Area: Stress

#1763 Replace #include <> for Local Headers
  src/core/injection.c
  src/inc/msquichelper.h
  src/inc/msquicp.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/inc/quic_tls.h
  src/perf/lib/PerfHelpers.h
  src/perf/lib/Tcp.h
  src/platform/cert_capi.c
  src/platform/cert_capi_openssl.c
  src/platform/platform_internal.h
  src/platform/selfsign_capi.c
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/bin/winkernel/driver.cpp
  src/test/lib/QuicDrill.cpp
  src/test/lib/TestAbstractionLayer.h
  src/test/lib/precomp.h
  src/tools/attack/attack.cpp
  src/tools/attack/packet_writer.cpp
  src/tools/etw/object_set.h
  src/tools/etw/quicetw.h
  src/tools/interop/interop.h
  src/tools/interopserver/InteropServer.h
  src/tools/ip/quicip.h
  src/tools/ip/server/quicipserver.cpp
  src/tools/lb/loadbalancer.cpp
  src/tools/pcp/pcp.cpp
  src/tools/post/post.cpp
  src/tools/reach/reach.cpp
  src/tools/sample/sample.c
  src/tools/spin/spinquic.cpp
Labels: Area: Build

#1758 Switch Param Id's to not be overlapping
  src/core/api.c
  src/inc/msquic.h
  src/inc/msquicp.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
Labels: Area: API

#1765 Ignore Retry packets when connection is shutting down.
  src/core/connection.c
Labels: Bug: Core

#1742 Expand TLS configuration testing
  CMakeLists.txt
  src/inc/msquic.h
  src/inc/quic_cert.h
  src/platform/cert_capi.c
  src/platform/cert_capi_openssl.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: Area: Testing

#1748 Refactor Library Load
  src/bin/linux/init.c
  src/bin/winkernel/driver.c
  src/bin/winuser/dllmain.c
  src/bin/winuser_fuzz/dllmain.c
  src/core/library.c
  src/core/library.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/perf/bin/drvmain.cpp
  src/platform/inline.c
  src/platform/platform_internal.h
  src/platform/platform_winkernel.c
  src/test/bin/winkernel/driver.cpp
Labels: Area: Core

#1772 Fix compilation on newer windows SDKs
  src/inc/quic_platform_winuser.h
  src/platform/datapath_winuser.c
Labels: Area: Build

#1773 Support local traces in QuicTrace
  src/plugins/trace/exe/Program.cs
Labels: Area: Logging

#1775 Fix compilation on newer windows SDKs (1.0) (#1772)
  src/inc/quic_platform_winuser.h
  src/platform/datapath_winuser.c
Labels: Area: Build, Backport

#1774 Fix compilation on newer windows SDKs (1.1) (#1772)
  src/inc/quic_platform_winuser.h
  src/platform/datapath_winuser.c
Labels: Area: Build, Backport

#1446 Add initial static library support
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  docs/BUILD.md
  scripts/build.ps1
  src/bin/CMakeLists.txt
  src/bin/static/empty.c
  src/core/CMakeLists.txt
  src/core/unittest/CMakeLists.txt
  src/inc/msquic.h
  src/perf/bin/CMakeLists.txt
  src/perf/lib/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/unittest/CMakeLists.txt
  src/test/bin/CMakeLists.txt
  src/test/lib/CMakeLists.txt
  src/tools/CMakeLists.txt
  src/tools/spin/spinquic.cpp
  submodules/CMakeLists.txt
Labels: Area: Build, external

#1777 Update spec link in TLS docs
  docs/TLS.md
Labels: Area: Documentation

#1780 Don't Apply Min Idle Timeout During Handshake
  src/core/connection.c
Labels: Area: Core

#1781 Fix incorrect assert in QuicPathRemove
  src/core/path.c
Labels: Area: Testing

#1782 Add Version for Log and Dump Debugging
  src/core/library.c
  src/core/library.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvents.cs
Labels: Area: Core, Area: Logging

#1784 Fix IDE folder prefix option
  CMakeLists.txt
Labels: Area: Build
