Repository microsoft/msquic, pull requests merged in 2021-04, with the labels that each got.

#1415 Support Ninja generator on Windows
  CMakeLists.txt
  src/inc/msquic_winuser.h
  src/inc/quic_platform_winuser.h
  src/platform/platform_internal.h
Labels: Area: Build, external

#1419 Fix generator changes not working for clean openssl builds
  .azure/templates/build-config-user.yml
  CMakeLists.txt
Labels: Area: Build, TLS: OpenSSL

#1422 Properly handle IPv4 addresses in Invoke-EtwTraceCollection
  scripts/Invoke-EtwTraceCollection.ps1
Labels: Area: Logging

#1366 Client Certificate validation
  scripts/prepare-machine.ps1
  src/inc/msquic_posix.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/inc/quic_platform.h
  src/platform/cert_capi.c
  src/platform/selfsign_capi.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
Labels: Area: Testing, TLS: Schannel

#1423 Add document discussing FIPS mode and MsQuic.
  docs/FIPS.md
Labels: Area: Documentation

#1425 Fixes Zero Length Mem Copy
  src/core/stream_send.c
Labels: Area: Core

#1421 Prevent spuriously re-invoking make on OpenSSL targets during incremental builds
  .azure/templates/build-config-user.yml
  CMakeLists.txt
  submodules/CMakeLists.txt
Labels: Area: Build, external

#1429 Add support for UWP OpenSSL builds.
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  src/tools/etw/main.c
  submodules/CMakeLists.txt
Labels: Area: Build, OS: Windows (User), TLS: OpenSSL

#1427 Always treat macOS as a single core platform
  src/platform/platform_posix.c
Labels: OS: macOS

#1424 Reduce the size of the receive packet queue
  src/core/quicdef.h
Labels: Area: Performance

#1430 Support Cipher Suite Allow List
  src/inc/msquic.h
  src/inc/quic_platform.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: Area: API, TLS: OpenSSL, TLS: Schannel

#1438 Remove Async TLS Support
  src/core/connection.c
  src/core/crypto.c
  src/core/crypto.h
  src/core/operation.h
  src/inc/quic_tls.h
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
  src/tools/attack/packet_writer.cpp
Labels: Area: Core, TLS: OpenSSL, TLS: Schannel

#1439 Disable async fiber support for openssl UWP
  .azure/templates/build-config-user.yml
  submodules/CMakeLists.txt
Labels: OS: Windows (User), TLS: OpenSSL

#1431 Enable ChaCha20-Poly1305 for OpenSSL
  CMakeLists.txt
  scripts/run_endpoint.sh
  src/inc/msquic.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
  src/tools/interop/interop.cpp
  src/tools/interop/interop.h
Labels: TLS: OpenSSL

#1444 pass CA certificates to SSLCtx when provided by pkcs12
  src/platform/tls_openssl.c
Labels: TLS: OpenSSL

#1445 Add support for TCP run during performance testing
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
Labels: Area: Performance

#1449 Default to send buffering off in secnetpert
  scripts/RemoteTests.json
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
Labels: Area: Performance

#1448 Always send data through the datapath thread
  src/core/binding.c
  src/core/binding.h
  src/core/packet_builder.c
  src/inc/quic_datapath.h
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/pcp.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/attack/attack.cpp
Labels: Area: Performance, OS: Ubuntu, OS: Windows (User)

#1451 Use worker ideal processor rather then connection partition ID for send.
  src/core/binding.c
  src/core/binding.h
  src/core/packet_builder.c
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Performance, OS: Windows (Kernel), OS: Windows (User)

#1452 Provide UWP implementations of GetProcessorCount functions
  src/inc/quic_platform_winuser.h
  src/platform/platform_winuser.c
Labels: OS: Windows (User)

#1454 Hardcode timer resolution call for UWP apps
  src/inc/quic_platform_winuser.h
Labels: OS: Windows (User)

#1456 Tune QUIC_MAX_RECEIVE_QUEUE_COUNT to be ideal for both kernel and user mode
  src/core/quicdef.h
Labels: Area: Performance, OS: Windows (Kernel)

#1457 Switch from NtQueryTimerResolution to GetSystemTimeAdjustment
  src/inc/quic_platform_winuser.h
Labels: OS: Windows (User)

#1458 Add Name to SecNetPerf Registrations
  src/perf/lib/HpsClient.h
  src/perf/lib/PerfServer.h
  src/perf/lib/RpsClient.h
  src/perf/lib/ThroughputClient.h
Labels: Area: Performance

#1450 API proposal for portable certificate verification
  CMakeLists.txt
  src/core/connection.c
  src/inc/msquic.h
  src/inc/quic_tls.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: Area: API

#1462 Refactor Trace Rundown to Remove from Tools/Tests
  src/core/library.c
  src/inc/quic_trace.h
  src/perf/bin/appmain.cpp
  src/perf/bin/drvmain.cpp
  src/platform/platform_posix.c
  src/platform/platform_winkernel.c
  src/platform/platform_winuser.c
  src/platform/unittest/main.cpp
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/driver.cpp
  src/tools/etw/main.c
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/ip/server/quicipserver.cpp
  src/tools/ping/QuicPing.cpp
  src/tools/post/post.cpp
  src/tools/reach/reach.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Logging

#1466 Skip publishing test results for codecoverage tasks
  .azure/templates/upload-test-artifacts.yml
Labels: Area: Testing

#1460 Disable UDP Send Queuing (Temporarily)
  src/platform/datapath_winuser.c
Labels: Area: Performance, OS: Windows (User)

#1470 Create and Start msquicpriv from secnetperf
  src/perf/bin/appmain.cpp
Labels: Area: Performance

#1467 Initial Trouble Shooting Guide
  README.md
  docs/Diagnostics.md
  docs/TSG.md
Labels: Area: Documentation

#1471 Add stats logging option to perf, log debug output to file
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
  scripts/performance.ps1
  src/perf/lib/PerfHelpers.h
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
Labels: Area: Performance

#1473 Add Connection Shutdown to TSG
  docs/TSG.md
Labels: Area: Documentation

#1472 Add perf stats to server side
  scripts/performance.ps1
Labels: Area: Performance

#1474 Enable UDP Send Queuing for Schannel User Mode
  CMakeLists.txt
Labels: Area: Performance

#1476 Refactor Perf Data Format
  assets/summary/data.commits.js.in
  assets/summary/data.js.in
  assets/summary/dataView.js
  assets/summary/detailedCharts.js
  assets/summary/latestData.js
  assets/summary/main/data.commits.js
  assets/summary/main/data.js
  assets/summary/nibanks/spurious-congestion-event/data.periodicrps.js
  assets/summary/nibanks/spurious-congestion-event/data.periodicwan.js
  assets/summary/release/1.1/data.commits.js
  assets/summary/summaryCharts.js
  commits.html
  detailed.html
  index.html
  powershell/generate-graphs.ps1
  rps.html
  wanperf.html
Labels: Area: Performance

#1477 Enable valid alpn length tests on schannel
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
Labels: Area: Testing, TLS: Schannel

#1478 Support running tests without administrator
  scripts/run-gtest.ps1
  scripts/test.ps1
Labels: Area: Testing

#1480 Reduce number of loops in RandomParitionId tests.
  src/core/unittest/PartitionTest.cpp
Labels: Area: Testing, OS: Ubuntu, OS: macOS

#1481 Add TSG Section for RSS Related Issues
  docs/Diagnostics.md
  docs/TSG.md
  docs/images/rss-debug-1.png
  docs/images/rss-debug-2.png
  docs/images/rss-debug-3.png
Labels: Area: Documentation

#1482 Add CPU Columns to WPA Plugin
  src/plugins/wpa/DataModel/QuicData.cs
  src/plugins/wpa/DataModel/QuicWorker.cs
  src/plugins/wpa/Tables/QuicDataBatchingTable.cs
  src/plugins/wpa/Tables/QuicWorkerActivityTable.cs
Labels: Area: Performance

#1483 If queued sends are enabled, ALWAYS send on datapath
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), bug

#1484 Clean up UDP Network Tables
  src/plugins/wpa/Tables/QuicDataBatchingTable.cs
Labels: Area: Performance

#1485 More WPA Clean up
  docs/TSG.md
  src/plugins/wpa/Tables/QuicDataBatchingTable.cs
  src/plugins/wpa/Tables/QuicWorkerActivityTable.cs
Labels: Area: Documentation, Area: Performance

#1487 Remove dispatch table from linux datapath and platform
  src/inc/quic_platform_dispatch.h
  src/platform/datapath_epoll.c
  src/platform/platform_posix.c
Labels: OS: Ubuntu

#1486 Add CPU Bottleneck Analysis to TSG
  docs/TSG.md
  docs/images/cpu-debug-1.png
  docs/images/cpu-debug-2.png
  docs/images/cpu-debug-3.png
  docs/images/cpu-debug-4.png
  docs/images/cpu-debug-5.png
  docs/images/cpu-debug-6.png
  docs/images/cpu-debug-7.png
  docs/images/cpu-debug-8.png
Labels: Area: Documentation

#1492 fix encoding collision issues
  src/inc/quic_driver_helpers.h
  src/perf/bin/drvmain.cpp
Labels: Area: Logging

#1497 Use correct TLS alert code for QUIC_ERROR_CRYPTO_USER_CANCELED
  src/core/frame.h
Labels: Area: Core, bug

#1493 QuicTrace Refactor
  src/plugins/trace/exe/Program.cs
Labels: Area: Logging, Area: Performance

#1499 Add Unhealthy Worker Check to Report Command
  src/plugins/trace/dll/DataModel/QuicConnection.cs
  src/plugins/trace/dll/DataModel/QuicEvents.cs
  src/plugins/trace/dll/DataModel/QuicTimeStats.cs
  src/plugins/trace/dll/DataModel/QuicWorker.cs
  src/plugins/trace/exe/Program.cs
Labels: Area: Logging

#1498 Remove Unused QuicPing Tool
  scripts/ping.ps1
  src/tools/CMakeLists.txt
  src/tools/ping/CMakeLists.txt
  src/tools/ping/Client.cpp
  src/tools/ping/PingConnection.cpp
  src/tools/ping/PingConnection.h
  src/tools/ping/PingStream.cpp
  src/tools/ping/PingStream.h
  src/tools/ping/QuicPing.cpp
  src/tools/ping/QuicPing.h
  src/tools/ping/Server.cpp
  src/tools/ping/readme.md
Labels: Area: Build

#1500 Upgrade QuicTrace to .NET 5
  src/plugins/trace/exe/Program.cs
  src/plugins/trace/exe/QuicTrace.csproj
Labels: Area: Logging

#1502 Support Custom Local Address for SecNetPerf Server
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/SecNetPerfMain.cpp
Labels: Area: Performance

#1447 Transport Close logging improvement
  src/core/binding.c
  src/core/binding.h
  src/core/listener.c
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/manifest/msquic.clog.cs
  src/manifest/msquic.clog_config
  src/plugins/trace/dll/DataModel/QuicEvents.cs
Labels: Area: Logging

#1504 Enhance performance logging capabilities
  .azure/azure-pipelines.perf.yml
  .azure/templates/run-performance.yml
  scripts/log.ps1
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Logging, Area: Performance

#1508 Update SAL annotation for ConnectionStart
  docs/api/ConnectionStart.md
  src/core/api.c
  src/core/api.h
  src/inc/msquic.h
  src/inc/quic_sal_stub.h
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
Labels: Area: Core

#1511 Various Test and MsQuic.hpp Improvements
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  src/inc/msquic.hpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/platform/unittest/CryptTest.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
Labels: Area: Testing

#1501 Run kernel mode perf tests with a kernel mode client
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance

#1513 StreamShutdown with Pending Receive
  src/core/stream_recv.c
  src/inc/msquic.hpp
  src/perf/bin/appmain.cpp
  src/perf/lib/RpsClient.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Core, bug

#1516 Deliver Shutdown Complete on Recv of Reset
  src/core/stream_recv.c
  src/inc/msquic.hpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Core, bug

#1517 Backport Stream Receive Abort Fixes to 1.1
  src/core/stream_recv.c
Labels: Area: Core, bug

#1521 Execute StreamShutdown Inline on Callbacks
  src/core/api.c
  src/core/stream_recv.c
Labels: Area: API, Area: Core

#1523 Release Notes for upcoming prerelease/1.3
  docs/Release.md
Labels: Area: Documentation

#1527 Update main to v1.4
  .azure/azure-pipelines.qns.yml
  .azure/templates/create-package.yml
  src/inc/msquic.ver
Labels: Area: Build

#1528 Ignore Zero-Length Receive Events in Tests
  src/test/lib/ApiTest.cpp
Labels: Area: Testing

#1529 Refactor Sent Packet Metadata Stream Ref Counting
  src/core/inline.c
  src/core/packet_builder.h
  src/core/sent_packet_metadata.c
  src/core/stream.h
  src/core/stream_send.c
Labels: Area: Core, Area: Performance

#1530 Updated User Mode PGO
  src/bin/winuser/pgo_x64/msquic.pgd
  src/bin/winuser/pgo_x86/msquic.pgd
Labels: Area: Build, Area: Performance

#1532 Special case targets in HPS tests
  scripts/RemoteTests.json
  src/perf/lib/HpsClient.cpp
  src/perf/lib/HpsClient.h
Labels: Area: Performance

#1488 Add support for Address Sanitizer in Windows (Dynamic Linkage only)
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  scripts/build.ps1
  src/bin/CMakeLists.txt
  src/core/CMakeLists.txt
  src/platform/CMakeLists.txt
Labels: Area: Build, Area: Testing

#1533 Use same RNG seed for TCP vs. QUIC random loss WAN tests.
  .azure/azure-pipelines.wanperf.yml
  .azure/templates/run-wanperf.yml
  scripts/emulated-performance.ps1
Labels: Area: Performance, Area: Testing

#1535 Average the last 5 results of runs for performance comparison
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance
