Repository microsoft/msquic, pull requests merged in 2021-03, with the labels that each got.

#1302 Reduce Max Pacing Window
  src/core/congestion_control.c
Labels: Area: Performance

#1299 Inline allocate event objects on posix
  src/core/worker.h
  src/inc/msquic.hpp
  src/inc/quic_platform_posix.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/inline.c
  src/platform/platform_posix.c
Labels: Area: Performance, OS: Ubuntu, OS: macOS

#1303 Small buffer optimize tls negotiated ALPN
  .azure/azure-pipelines-int.ci.yml
  .azure/azure-pipelines.ci.yml
  src/core/binding.c
  src/core/crypto.c
  src/inc/quic_tls.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Core, Area: Performance

#1306 Enable SAL for platform component on Windows User Mode
  src/inc/quic_driver_helpers.h
  src/inc/quic_platform_winuser.h
  src/inc/quic_storage.h
  src/platform/CMakeLists.txt
  src/platform/datapath_winuser.c
  src/platform/platform_winuser.c
  src/platform/selfsign_capi.c
  src/platform/storage_winkernel.c
  src/platform/storage_winuser.c
  src/platform/tls_mitls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/tls_stub.c
  src/tools/interopserver/InteropServer.cpp
Labels: Area: Build

#1305 Initial ACK Frequency Support
  src/core/ack_tracker.c
  src/core/connection.c
  src/core/connection.h
  src/core/crypto_tls.c
  src/core/frame.c
  src/core/frame.h
  src/core/transport_params.h
  src/core/unittest/SpinFrame.cpp
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/inc/quic_sal_stub.h
  src/manifest/clog.sidecar
Labels: Area: Core, Area: Protocol Updates

#1309 Rev Build Cache
  .azure/templates/build-config-user.yml
Labels: Area: Build, Area: Pipeline

#1311 Fixes for clang-cl
  src/core/stream.h
  src/inc/quic_crypt.h
  src/inc/quic_platform_winuser.h
  src/perf/bin/drvmain.cpp
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/tls_schannel.c
  src/test/bin/winkernel/control.cpp
  src/test/lib/KArray.h
  src/tools/sample/sample.cpp
Labels: Area: Build

#1314 Fix Frame Type Encoding Issues
  src/core/connection.c
  src/core/frame.c
  src/core/frame.h
  src/core/sent_packet_metadata.h
  src/core/unittest/SpinFrame.cpp
  src/core/unittest/main.h
  src/manifest/clog.sidecar
  src/plugins/dbg/quictypes.h
Labels: Area: Core, bug

#1317 Force medians to be sorted by number
  scripts/performance-helper.psm1
Labels: Area: Performance

#1321 Reduce batching counts for sends
  src/core/quicdef.h
  src/perf/lib/PerfServer.h
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Performance

#1323 Reduce batching counts for sends (#1321)
  .azure/azure-pipelines.qns.yml
  .azure/templates/create-package.yml
  src/core/quicdef.h
  src/inc/msquic.ver
  src/perf/lib/PerfServer.h
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Performance

#1322 Reduce batching counts for sends (#1321)
  .azure/azure-pipelines.ci.yml
  .azure/templates/create-package.yml
  src/core/quicdef.h
  src/inc/msquic.ver
  src/perf/lib/PerfServer.h
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Performance

#1325 Configure Schannel to Always Use Session Tickets for Resumption
  .azure/azure-pipelines.ci.yml
  src/platform/tls_schannel.c
Labels: OS: Windows (Kernel), OS: Windows (User), TLS: Schannel

#1320 Use system libcrypto
  .azure/azure-pipelines.ci.yml
  .azure/templates/download-artifacts.yml
  .azure/templates/run-bvt.yml
  CMakeLists.txt
  scripts/build.ps1
  scripts/test.ps1
Labels: TLS: OpenSSL

#1331 Fix interop reading out of range when running all tests
  src/tools/interop/interop.cpp
Labels: Area: Interop

#1332 Fix version update script to update QNS file as well
  scripts/update-version.ps1
Labels: Area: Build

#1333 Update PGO binaries
  src/bin/winuser/pgo_x64/msquic.pgd
  src/bin/winuser/pgo_x86/msquic.pgd
Labels: Area: Build, Area: Performance

#1334 Fix version update script to update QNS file as well (#1332)
  scripts/update-version.ps1
Labels: Area: Build

#1336 Fix interop reading out of range when running all tests (#1331)
  src/tools/interop/interop.cpp
Labels: Area: Interop

#1337 Add WANPerf previous result comparisons
  .azure/azure-pipelines.periodic.yml
  scripts/emulated-performance.ps1
  scripts/performance-helper.psm1
Labels: Area: Performance

#1339 Fix issues with M1 mac build and running.
  CMakeLists.txt
  src/platform/platform_posix.c
Labels: Area: Build, OS: macOS

#1342 Fix TLS Secrets Support Flag
  CMakeLists.txt
Labels: Area: Build

#1346 Update lttng to 2.12 on release/1.1
  .github/workflows/codeql-analysis.yml
  docs/BUILD.md
  scripts/prepare-machine.ps1
Labels: Area: Build, OS: Ubuntu

#1341 essential fixes to build on Silicon Mac
  src/inc/quic_platform_posix.h
  src/test/bin/quic_gtest.cpp
Labels: OS: macOS

#1340 Add GSO support to epoll datapath
  src/manifest/clog.sidecar
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: OS: Ubuntu

#1359 quicipserver now prints out usage information when supplied with incorrect args.
  src/tools/ip/server/quicipserver.cpp
Labels: external

#1362 Change Test Cert Password to placeholder
  scripts/prepare-machine.ps1
Labels: Area: Testing

#1363 Make WAN Perf Previous Results Failure Resilient
  scripts/emulated-performance.ps1
Labels: Area: Performance, Area: Pipeline

#1364 Expose Revocation Schannel Flags
  src/inc/msquic.h
  src/platform/tls_schannel.c
Labels: TLS: Schannel

#1347 Rename SendContext and Datagram from datpath to SendData and Buffer
  src/core/binding.c
  src/core/binding.h
  src/core/packet_builder.c
  src/core/packet_builder.h
  src/core/send.c
  src/inc/msquicp.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/pcp.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/test/lib/TestHelpers.h
  src/tools/attack/attack.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Core, OS: Ubuntu, OS: Windows (Kernel), OS: Windows (User), OS: macOS

#1354 Switch to 43 packet receive batch size
  src/platform/datapath_epoll.c
Labels: Area: Performance, OS: Ubuntu

#1368 Rename quicperf to netsecperf
  docs/PGO.md
  msquic.kernel.sln
  scripts/FullRunRPS.json
  scripts/RemoteTests.json
  scripts/TcpTests.json
  scripts/emulated-performance.ps1
  scripts/performance-helper.psm1
  scripts/rps.ps1
  src/perf/bin/CMakeLists.txt
  src/perf/bin/appmain.cpp
  src/perf/bin/drvmain.cpp
  src/perf/bin/secnetperfdriver.kernel.vcxproj
  src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
  src/perf/lib/CMakeLists.txt
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/perflib.kernel.vcxproj
Labels: Area: Performance

#1361 More Configuration Documentation
  docs/api/ConfigurationClose.md
  docs/api/ConfigurationLoadCredential.md
  docs/api/ConfigurationOpen.md
  docs/api/ConnectionStart.md
  docs/api/QUIC_CREDENTIAL_CONFIG.md
  docs/api/QUIC_SETTINGS.md
Labels: Area: Documentation

#1356 More Registration Documentation
  docs/api/MsQuicOpen.md
  docs/api/QUIC_REGISTRATION_CONFIG.md
  docs/api/RegistrationOpen.md
Labels: Area: Documentation

#1367 Update BVT Task to Fail
  .azure/azure-pipelines.ci.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-quicinterop.yml
  .azure/templates/run-spinquic.yml
  .azure/templates/upload-artifacts.yml
  .azure/templates/upload-test-artifacts.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
  scripts/spin.ps1
  scripts/test.ps1
Labels: Area: Pipeline, Area: Testing

#1371 Reset TLS Unit Test Flags
  src/platform/unittest/TlsTest.cpp
Labels: Area: Testing

#1351 add basic support for pkcs12 import
  CMakeLists.txt
  scripts/install-test-certificates.ps1
  scripts/run-gtest.ps1
  scripts/test.ps1
  src/inc/msquic.h
  src/platform/tls_openssl.c
  src/platform/unittest/TlsTest.cpp
  src/platform/unittest/main.cpp
Labels: Area: API, TLS: OpenSSL

#1372 Enable SAL checking in core and bin for user mode builds
  src/bin/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/ack_tracker.c
  src/core/connection.c
  src/core/crypto.c
  src/core/crypto_tls.c
  src/core/datagram.c
  src/core/frame.c
  src/core/frame.h
  src/core/packet.c
  src/core/settings.c
  src/core/stream_send.c
Labels: Area: Core

#1374 Support multiple instances of secnetperf in kernel mode
  scripts/performance-helper.psm1
  src/perf/bin/appmain.cpp
  src/perf/bin/drvmain.cpp
  src/perf/bin/secnetperfdriver.kernel.vcxproj
  src/perf/lib/SecNetPerfMain.cpp
Labels: Area: Performance

#1375 Add secnetperf to vpack for Windows
  scripts/prepare-package.ps1
Labels: Area: Performance

#1382 Delay Stream SHUTDOWN_COMPLETE Event While Data Pending
  src/core/stream.c
Labels: Area: API, Area: Core, bug

#1385 Add script to invoke ETW trace
  scripts/Invoke-EtwTraceCollection.ps1
Labels: Area: Logging

#1376 OpenSSL Resumption / 0-RTT Work
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  src/core/configuration.c
  src/inc/quic_platform.h
  src/manifest/clog.sidecar
  src/platform/tls_openssl.c
  src/platform/unittest/TlsTest.cpp
  src/test/lib/DataTest.cpp
Labels: TLS: OpenSSL

#1388 Properly detect arm current platform for macos pwsh builds
  scripts/build.ps1
Labels: Area: Build, OS: macOS

#1390 Improve Release Documentation
  docs/Release.md
Labels: Area: Documentation

#1392 Update Interop for 0-RTT
  scripts/run_endpoint.sh
Labels: Area: Interop, Area: Testing

#1391 Only set SO_REUSEPORT on server sockets
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu, bug

#1395 Add build flag to disable GSO on posix for interop runner
  CMakeLists.txt
  Dockerfile
  src/platform/datapath_epoll.c
Labels: Area: Interop, OS: Ubuntu

#1396 Update Interop Runner Client to Use v1
  scripts/run_endpoint.sh
Labels: Area: Interop, Area: Pipeline

#1405 Fix Cmake generator arguments
  .azure/azure-pipelines.ci.yml
  scripts/build.ps1
Labels: Area: Build

#1404 Make Connection Required Arg for QuicVersionNegotiation Functions
  src/core/unittest/VersionNegExtTest.cpp
  src/core/version_neg.c
  src/core/version_neg.h
Labels: Area: Build

#1406 Use CMAKE_CURRENT_SOURCE_DIR for openssl
  CMakeLists.txt
Labels: Area: Build

#1407 Enable Resumption & 0-RTT in Interop Server
  src/tools/interopserver/InteropServer.cpp
Labels: Area: Interop

#1410 Adds Start/Stop and Updates Flush for EtwTraceCollection
  scripts/Invoke-EtwTraceCollection.ps1
Labels: Area: Logging

#1408 Fix Cmake generator arguments (1.0) (#1405)
  .azure/azure-pipelines.ci.yml
  scripts/build.ps1
Labels: Area: Build

#1409 Fix Cmake generator arguments (1.1) (#1405)
  .azure/azure-pipelines.ci.yml
  scripts/build.ps1
Labels: Area: Build

#1399 Run Asan on OpenSSL builds instead of Stub builds
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-user.yml
  .azure/templates/run-spinquic.yml
  CMakeLists.txt
  scripts/run-gtest.ps1
  scripts/spin.ps1
  src/platform/tls_openssl.c
  src/platform/unittest/CryptTest.cpp
Labels: Area: Testing, OS: Ubuntu, TLS: OpenSSL

#1412 Fix not matching ETW trace string in quic driver helpers.
  src/inc/quic_driver_helpers.h
Labels: Area: Logging

#1411 Remove stub TLS
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.perf.yml
  CMakeLists.txt
  docs/BUILD.md
  docs/TLS.md
  scripts/FullRunRPS.json
  scripts/RemoteTests.json
  scripts/TcpTests.json
  scripts/build.ps1
  scripts/emulated-performance.ps1
  scripts/install-build-artifacts.ps1
  scripts/interop.ps1
  scripts/merge-coverage.ps1
  scripts/merge-darwin.ps1
  scripts/performance.ps1
  scripts/ping.ps1
  scripts/spin.ps1
  scripts/test.ps1
  src/manifest/clog.sidecar
  src/platform/CMakeLists.txt
  src/platform/cert_stub.c
  src/platform/platform_internal.h
  src/platform/selfsign_stub.c
  src/platform/tls_stub.c
  src/platform/unittest/CryptTest.cpp
Labels: TLS: Stub

#1414 Build M1 OpenSSL Builds, Create Universal Binaries
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-distribution.yml
  .azure/templates/merge-darwin.yml
  CMakeLists.txt
  scripts/install-build-artifacts.ps1
  scripts/merge-darwin.ps1
Labels: Area: Build, OS: macOS
