Repository microsoft/msquic, pull requests merged in 2022-05, with the labels that each got.

#2675 NetBIOS Datagrams is port 138, not 128
  src/core/binding.c
Labels: external, Area: Core

#2653 Change .NET interop to internal, other type changes
  scripts/generate-dotnet.ps1
  src/cs/LicenseHeader.txt
  src/cs/MsQuicNet.sln
  src/cs/lib/InternalsVisible.cs
  src/cs/lib/MsQuicException.cs
  src/cs/lib/msquic.cs
  src/cs/lib/msquic_generated.cs
  src/cs/lib/msquic_generated_linux.cs
  src/cs/lib/msquic_generated_macos.cs
  src/cs/lib/msquic_generated_windows.cs
  src/cs/tool/Program.cs
Labels: Language: C#

#2676 XDP perf dashboard
  assets/summary/data.js.in
  assets/summary/dataView.js
  assets/summary/detailedCharts.js
  assets/summary/main/data.js
  detailed.html
  index.html
  powershell/generate-graphs.ps1
Labels: Area: Performance, Area: Lola

#2677 Consume XDP fix for TX hangs
  src/platform/datapath_raw_xdp.c
Labels: Area: Lola

#2681 Increase ring size and buffer count
  src/platform/datapath_raw_xdp.c
Labels: Area: Performance, Area: Lola

#2680 Update listener docs for quirks regarding ListenerStart on the same port
  docs/api/ListenerStart.md
Labels: Area: Documentation

#2678 Use all processors for XDP perf test
  scripts/performance.ps1
  src/core/connection.c
  src/inc/quic_datapath.h
  src/perf/lib/SecNetPerfMain.cpp
Labels: Area: Performance, Area: Lola

#2667 Reintroduce port reservation features
  src/inc/quic_datapath.h
  src/platform/datapath_winuser.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: OS: Windows (User), Bug: Platform

#2655 Switch epoll and kqueue to level triggers
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
Labels: OS: Ubuntu, OS: macOS

#2691 Increase RPS latency storage
  src/perf/lib/PerfCommon.h
Labels: Area: Performance, Area: Lola

#2693 Add SharedEC to Perf and SpinQuic
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.perf.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Build, Area: Performance, Area: Automation, Area: Lola

#2695 Fix Builder->TotalDatagramsLength being incorrectly calculated
  src/core/packet_builder.c
Labels: Bug: Core

#2694 Fix PMTU packets logging as a 0 length send in kernel mode
  src/platform/datapath_winkernel.c
Labels: OS: Windows (Kernel), Bug: Platform

#2698 Disable XDP Builds on release/2.0
  .azure/azure-pipelines.ci.yml
Labels: Area: Build, Area: Automation

#2699 Update to Latest XDP SDK
  .azure/azure-pipelines.perf.yml
  scripts/prepare-machine.ps1
  src/platform/datapath_raw_xdp.c
Labels: Area: Build, Area: Lola

#2701 Add XDP Nuget Package, build XDP in Onebranch
  .azure/OneBranch.Official.yml
  .azure/OneBranch.PullRequest.yml
  .azure/obtemplates/build-nuget.yml
  .azure/obtemplates/build-winuser-xdp.yml
  .azure/templates/build-nuget.yml
  scripts/package-nuget.ps1
  src/distribution/Microsoft.Native.Quic.MsQuic.XDP.Schannel.nuspec
  src/distribution/Microsoft.Native.Quic.MsQuic.XDP.Schannel.targets
Labels: Area: Build, Area: Automation, Area: Lola

#2703 Fix Nuget Packaging Failure in CI
  .azure/templates/build-nuget.yml
Labels: Area: Build, Area: Automation

#2708 Save XDP symbols in azure pipeline artifacts
  scripts/prepare-machine.ps1
Labels: Area: Performance, Area: Lola

#2711 Save XDP binaries in artifacts
  scripts/prepare-machine.ps1
Labels: Area: Performance, Area: Lola

#2716 Update Copyright info for performance dashboard
  detailed.html
  index.html
  rps.html
  wanperf.html
Labels: Area: Documentation

#2719 Add Callback Helpers to .NET Interop Layer
  src/cs/lib/msquic_extensions.cs
Labels: Language: C#

#2721 Add variable to skip docker detector in onebranch
  .azure/OneBranch.Official.yml
  .azure/OneBranch.Package.yml
  .azure/OneBranch.PullRequest.yml
  .azure/OneBranch.Tests.Official.yml
  .azure/OneBranch.Tests.PullRequest.yml
Labels: Area: Automation

#2702 Indicate null/missing client certificate
  CMakeLists.txt
  src/core/connection.c
  src/inc/msquic_posix.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/inc/quic_tls.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: TLS: OpenSSL, TLS: Schannel, Area: API

#2728 Add sendbuf param to RPS client
  src/perf/lib/RpsClient.cpp
Labels: Area: Performance

#2736 Ingest the latest XDP devkit
  scripts/prepare-machine.ps1
  src/platform/datapath_raw_xdp.c
Labels: Area: Performance, Area: Lola

#2729 Support setting SECPKG_ATTR_CLIENT_CERT_POLICY directly
  src/core/configuration.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/quic_tls.h
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/tools/spin/spinquic.cpp
Labels: OS: Windows (User), OS: Windows (Kernel), TLS: Schannel, Area: API

#2737 Ignore XDP workers that do not have an XDP queue assigned
  src/platform/datapath_raw_xdp.c
Labels: Area: Performance, Area: Lola

#2730 Support Schannel users calling QuerySecurityContextToken
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/platform/tls_schannel.c
  src/tools/spin/spinquic.cpp
Labels: OS: Windows (User), OS: Windows (Kernel), TLS: Schannel, Area: API

#2739 Improve https://aka.ms/xdp-install
  scripts/prepare-machine.ps1
  scripts/xdp-devkit.json
  scripts/xdp-install.ps1
Labels: Area: Performance, Area: Lola

#2746 Fix Schannel Context Request Flags
  src/platform/tls_schannel.c
Labels: TLS: Schannel, Bug: Platform

#2748 Use port set XDP rules
  scripts/performance.ps1
  src/platform/datapath_raw_xdp.c
Labels: Area: Performance, Area: Lola

#2749 Fix build on Ubuntu 22.04
  .azure/azure-pipelines.ci.yml
  src/core/unittest/SettingsTest.cpp
Labels: OS: Ubuntu

#2740 Add new Windows/Schannel-only flags.
  docs/api/QUIC_CREDENTIAL_CONFIG.md
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/platform/certificates_capi.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: OS: Windows (User), OS: Windows (Kernel), TLS: Schannel, Area: API

#2752 Consume XDP from github release and stash XDP version in MsQuic for XDP nuget package
  scripts/package-nuget.ps1
  scripts/xdp-devkit.json
Labels: Area: Performance, Area: Lola

#2753 Fix port set rules not working for IPv6
  src/platform/datapath_raw_xdp.c
Labels: Area: Performance, Area: Lola

#2759 Fix typo in generated .net code
  src/cs/LicenseHeader.txt
  src/cs/lib/msquic_generated.cs
  src/cs/lib/msquic_generated_linux.cs
  src/cs/lib/msquic_generated_macos.cs
Labels: Language: C#

#2762 Expose Parameter for TLS Provider
  docs/Settings.md
  scripts/generate-dotnet.ps1
  src/core/library.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/quic_tls.h
  src/lib.rs
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/test/lib/ApiTest.cpp
Labels: Area: API

#2756 Allow TCP perf to fail to complete without failing pipeline
  scripts/RemoteTests.json
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance
