Repository microsoft/msquic, pull requests merged in 2022-04, with the labels that each got.

#2599 Prepare for Onboarding XDP Perf
  .azure/azure-pipelines.perf.yml
  .azure/templates/run-performance.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
  scripts/prepare-machine.ps1
Labels: Area: Performance

#2598 Unreliable Datagram RFC 9221 is Official
  README.md
Labels: Area: Documentation

#2600 RFC/Drafts to Shields
  README.md
Labels: Area: Documentation

#2601 Run Latency RPS for Longer
  scripts/RemoteTests.json
Labels: Area: Performance

#2605 Remove quicreach
  src/tools/CMakeLists.txt
  src/tools/reach/CMakeLists.txt
  src/tools/reach/reach.cpp
Labels: Area: Testing

#2613 Block Certain Source Ports
  src/core/binding.c
  src/inc/msquic.hpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Protocol Updates, Area: Security, Area: Core

#2615 Lola uses winuser DNS functions as a stopgap
  src/generated/linux/datapath_raw.c.clog.h
  src/generated/linux/datapath_raw.c.clog.h.lttng.h
  src/platform/datapath_raw.c
Labels: Area: Lola

#2612 Don't Double Count Connection Packet Drops
  src/core/connection.c
  src/core/crypto.c
Labels: Bug: Core, Area: API, Area: Core

#2538 Add support to secnetperf to explcitly set cipher suites
  src/inc/quic_platform.h
  src/perf/bin/appmain.cpp
  src/perf/lib/SecNetPerfMain.cpp
  src/platform/selfsign_capi.c
  src/platform/selfsign_openssl.c
Labels: Area: Performance

#2617 P90 single connection latency graphs
  assets/summary/data.js.in
  assets/summary/dataView.js
  assets/summary/detailedCharts.js
  assets/summary/main/data.js
  assets/summary/rpsLatencyCharts.js
  assets/summary/summaryCharts.js
  detailed.html
  index.html
  powershell/generate-graphs.ps1
Labels: Area: Performance

#2619 Fix a jump anchor in detailed view
  detailed.html
Labels: Area: Performance

#2618 Resolve route in QuicSendFlush and enable LoLa testcases that are fixed by this change
  .azure/azure-pipelines.ci.yml
  src/core/connection.c
  src/core/send.c
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/manifest/clog.sidecar
Labels: Area: Core, Area: Lola

#2622 Fix QuicTestCibirExtension for LoLa and enable *CibirExtension* tests
  .azure/azure-pipelines.ci.yml
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing, Area: Lola

#2620 Fix route resolution error handling
  src/core/send.c
  src/platform/datapath_raw_socket.c
  src/platform/unittest/DataPathTest.cpp
Labels: Area: Lola

#2624 Add multi-connection P90 latency
  assets/summary/dataView.js
  assets/summary/detailedCharts.js
  assets/summary/latestData.js
  assets/summary/main/data.js
  assets/summary/rpsLatencyCharts.js
  assets/summary/summaryCharts.js
  detailed.html
  index.html
  powershell/generate-graphs.ps1
Labels: Area: Performance

#2626 Change C# Constants to uint
  scripts/generate-dotnet.ps1
  src/cs/lib/msquic_generated.cs
Labels: Language: C#

#2621 Fix .deb Package Creation
  scripts/make-packages.sh
Labels: Area: Build, OS: Ubuntu, Area: Automation

#2623 Spinquic job for LoLa
  .azure/azure-pipelines.ci.yml
  scripts/spin.ps1
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
Labels: Area: Testing, Area: Stress, Area: Lola

#2633 Mention C++, C# and Rust in Readme
  README.md
Labels: Area: Documentation

#2636 Cancel Long Running Workflows on New PR Commits
  .github/workflows/test-down-level.yml
  .github/workflows/wan-perf.yml
Labels: Area: Automation

#2634 Add Test for Linux Package
  .azure/azure-pipelines.ci.yml
  .azure/templates/test-distribution.yml
  scripts/update-version.ps1
Labels: Area: Testing, OS: Ubuntu, Area: Automation

#2639 CP release/2.0 - Linux Package and Infra Fixes
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.qns.yml
  .azure/obtemplates/push-vpack.yml
  .azure/templates/test-distribution.yml
  .github/workflows/wan-perf.yml
  CMakeLists.txt
  Cargo.toml
  scripts/make-packages.sh
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/update-version.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
Labels: Area: Build, Area: Automation, Backport

#2640 Fix unique RSS procs counting
  src/platform/datapath_raw_xdp.c
Labels: Area: Lola

#2642 Document API Thread-Safety Issues
  docs/api/MsQuicClose.md
  docs/api/MsQuicOpenVersion.md
Labels: Area: Documentation

#2540 Add logs to all cases an IOCP can exit the EC early
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/platform/datapath_winuser.c
Labels: OS: Windows (User)

#2182 Finish up kernel mode app storage
  src/generated/linux/quic.clog_storage_winkernel.c.clog.h.c
  src/generated/linux/storage_winkernel.c.clog.h
  src/generated/linux/storage_winkernel.c.clog.h.lttng.h
  src/generated/linux/storage_winuser.c.clog.h
  src/generated/linux/storage_winuser.c.clog.h.lttng.h
  src/inc/msquic.hpp
  src/platform/storage_winkernel.c
  src/platform/storage_winuser.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
Labels: OS: Windows (Kernel)

#2646 Expose Listener close function
  src/lib.rs
Labels: external, Language: Rust

#2648 Fix only setting minimum mtu during config open failing
  src/core/settings.c
  src/test/lib/MtuTest.cpp
Labels: Bug: Core

#2650 Update C# enums
  scripts/generate-dotnet.ps1
  src/cs/lib/msquic_generated.cs
  src/cs/tool/Program.cs
Labels: Language: C#

#2652 Allow Too Big IP in Raw Parsing
  src/platform/datapath_raw_socket.c
Labels: Bug: Platform, Area: Lola

#2659 Run perf from temp folder
  .azure/azure-pipelines.perf.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance

#2668 Backport correct signing profile to Ni
  .azure/obtemplates/build-linux-packages.yml
Labels: Area: Automation, Backport

#2669 Fix some issues with performance testing and logging
  .azure/azure-pipelines.perf.yml
  .azure/templates/run-performance.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance

#2670 Onboard XDP perf test
  .azure/azure-pipelines.perf.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
  src/core/packet_builder.c
  src/platform/datapath_raw_xdp.c
Labels: Area: Performance, Area: Lola
