Repository microsoft/msquic, pull requests merged in 2022-11, with the labels that each got.

#3198 Test Specific Handshake Loss Patterns
  src/core/connection.c
  src/core/connection.h
  src/core/inline.c
  src/core/loss_detection.c
  src/core/worker.c
  src/generated/linux/TestHelpers.h.clog.h
  src/generated/linux/TestHelpers.h.clog.h.lttng.h
  src/generated/linux/datapath_raw_socket.c.clog.h
  src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
  src/generated/linux/worker.c.clog.h
  src/generated/linux/worker.c.clog.h.lttng.h
  src/inc/msquic.hpp
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/datapath_raw_socket.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
Labels: Area: Testing

#3210 ThreadID 0 for client, ThreadID 1 for server for more determinisity
  src/tools/spin/spinquic.cpp
Labels: Area: Testing, Area: Stress

#3209 Fix modulo issue of MSB 1 with signed type
  src/tools/spin/spinquic.cpp
Labels: Area: Testing, Area: Stress

#3195 CP: v2.1 Load Balancing Fixed Server ID
  docs/Deployment.md
  src/core/connection.c
  src/core/library.c
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/clog.sidecar
Labels: Area: API, Area: Core

#3214 CP: v2.1 Timewheel Fix
  src/core/connection.c
Labels: Bug: Core, Area: Core

#3218 Add info about usage with older Windows releases with OpenSSL
  docs/Platforms.md
Labels: Area: Documentation, external

#3217 Update Down-Level Test to v2.1.5 Release
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3192 add repro/debug section
  src/fuzzing/README.md
Labels: Area: Documentation

#3216 Basic ECN congestion control support
  scripts/generate-dotnet.ps1
  src/core/bbr.c
  src/core/congestion_control.h
  src/core/connection.c
  src/core/connection.h
  src/core/cubic.c
  src/core/inline.c
  src/core/loss_detection.c
  src/cs/lib/msquic_generated.cs
  src/generated/linux/bbr.c.clog.h
  src/generated/linux/bbr.c.clog.h.lttng.h
  src/generated/linux/connection.h.clog.h
  src/generated/linux/connection.h.clog.h.lttng.h
  src/generated/linux/cubic.c.clog.h
  src/generated/linux/cubic.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/perf/lib/PerfHelpers.h
  src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvents.cs
Labels: Area: Performance, Area: Core

#3235 Update QUIC_CREDENTIAL_CONFIG.md PKCS12 support
  docs/api/QUIC_CREDENTIAL_CONFIG.md
Labels: Area: Documentation

#3234 Github Codespaces devcontainer
  .devcontainer/devcontainer.json
Labels: Area: Build

#3132 Added support for ca certificate file setting in SSL_CTX.
  CMakeLists.txt
  docs/api/QUIC_CREDENTIAL_CONFIG.md
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/msquichelper.h
  src/inc/quic_platform.h
  src/perf/bin/appmain.cpp
  src/platform/selfsign_capi.c
  src/platform/selfsign_openssl.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
  src/test/bin/quic_gtest.cpp
  src/tools/spin/spinquic.cpp
Labels: external, Area: API

#3236 Speed up git submodules update
  scripts/prepare-machine.ps1
Labels: Area: Build

#3248 Silo Improvements on Client Side
  src/core/connection.c
Labels: Bug: Core, Area: Core

#3245 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3253 Add CIFuzz GitHub action
  .github/workflows/cifuzz.yml
Labels: Area: Testing, Area: Stress, external, Area: Automation, Area: Security

#3249 Add Documentation for secnetperf
  src/perf/lib/ThroughputClient.cpp
  src/perf/readme.md
Labels: Area: Documentation

#3252 Backport 2.1: Silo Improvements on Client Side (#3248)
  src/core/connection.c
Labels: Bug: Core, Area: Core

#3257 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation
