Repository microsoft/msquic, pull requests merged in 2022-08, with the labels that each got.

#2928 Updated macOS Version
  .azure/azure-pipelines.ci.yml
  cmake/toolchains/ios.cmake
  scripts/build.ps1
Labels: Area: Build, OS: macOS

#2930 CP 2.0: Try fix Android (#2912)
  scripts/build.ps1
  src/platform/datapath_epoll.c
Labels: Area: Build, OS: Android

#2929 Correctly handle unsupported client cert on Windows Server 2022
  src/platform/tls_schannel.c
Labels: TLS: Schannel

#2932 Add ConnectionCloseStatus to Stream SHUTDOWN_DONE event
  src/core/stream.c
  src/cs/lib/msquic_generated.cs
  src/generated/linux/stream.c.clog.h
  src/generated/linux/stream.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/clog.sidecar
  src/test/lib/DataTest.cpp
  src/test/lib/TestStream.cpp
  src/test/lib/TestStream.h
Labels: Area: API

#2933 Fix Shared EC Perf Regression
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), Area: Performance

#2876 On connection idle cid changes
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
  src/core/connection.c
  src/core/connection.h
  src/core/quicdef.h
  src/core/send.c
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/lib.rs
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestStream.cpp
  src/test/lib/TestStream.h
Labels: external, Area: API, Area: Core

#2937 Revert Recent BBR Support
  .github/workflows/wan-perf.yml
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
  scripts/clog.inputs
  scripts/emulated-performance.ps1
  src/core/CMakeLists.txt
  src/core/bbr.c
  src/core/bbr.h
  src/core/congestion_control.c
  src/core/congestion_control.h
  src/core/connection.h
  src/core/core.kernel.vcxproj
  src/core/cubic.c
  src/core/inline.c
  src/core/loss_detection.c
  src/core/loss_detection.h
  src/core/precomp.h
  src/core/sent_packet_metadata.h
  src/core/sliding_window_extremum.c
  src/core/sliding_window_extremum.h
  src/core/stream.h
  src/core/stream_send.c
  src/core/unittest/CMakeLists.txt
  src/core/unittest/SlidingWindowExtremumTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/SlidingWindowExtremumTest.cpp.clog.h
  src/generated/linux/bbr.c.clog.h
  src/generated/linux/bbr.c.clog.h.lttng.h
  src/generated/linux/connection.h.clog.h
  src/generated/linux/connection.h.clog.h.lttng.h
  src/generated/linux/quic.clog_SlidingWindowExtremumTest.cpp.clog.h.c
  src/generated/linux/quic.clog_bbr.c.clog.h.c
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/perf/lib/PerfServer.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
  src/plugins/trace/dll/DataModel/QuicEvent.cs
  src/tools/etw/quicetw.h
Labels: Area: Performance

#2931 CP 2.0: Updated macOS Version (#2928)
  .azure/azure-pipelines.ci.yml
  cmake/toolchains/ios.cmake
  scripts/build.ps1
  src/platform/datapath_kqueue.c
Labels: Area: Build, OS: macOS

#2938 Fix CloseConnBeforeStreamFlush Test Failure
  src/test/lib/ApiTest.cpp
Labels: Area: Testing, Bug: Test/Tool

#2940 Disable Failing Loopback Tests on Shared EC Linux
  .azure/azure-pipelines.perf.yml
Labels: Area: Performance

#2936 Add new QUIC_STATUS_ALPN_IN_USE Status Code
  .github/workflows/test-down-level.yml
  src/core/binding.c
  src/core/binding.h
  src/core/listener.c
  src/generated/linux/listener.c.clog.h
  src/generated/linux/listener.c.clog.h.lttng.h
  src/inc/msquic_posix.h
  src/inc/msquic_winkernel.h
  src/inc/msquic_winuser.h
  src/test/lib/BasicTest.cpp
Labels: Area: API, Area: Core

#2941 Fix Mirroring on release/1.0
  .azure/azure-pipelines.ci.yml
  .github/workflows/mirror-repo.yml
Labels: Area: Automation

#2942 Fix Mirroring on release/1.1
  .azure/azure-pipelines.ci.yml
  .github/workflows/mirror-repo.yml
Labels: Area: Automation

#2947 Release Notes for v2.1
  docs/Release.md
Labels: Area: Documentation

#2949 Don't Check Minor Version in Test
  src/test/lib/ApiTest.cpp
Labels: Area: Testing

#2948 Update main Version to v2.2
  .azure/obtemplates/push-vpack.yml
  .azure/templates/test-distribution.yml
  CMakeLists.txt
  Cargo.toml
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
  src/test/lib/ApiTest.cpp
Labels: Area: Core

#2918 Initial support for FreeBSD
  src/inc/msquic.h
  src/inc/quic_platform_posix.h
  src/platform/CMakeLists.txt
  src/platform/datapath_kqueue.c
  src/platform/platform_posix.c
Labels: Area: Build, external

#2953 Harden Github Actions.
  .github/workflows/cargo.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-publish.yml
  .github/workflows/test-down-level.yml
Labels: Area: Automation

#2951 Onboard Downlevel Tests for v2.1
  .github/workflows/test-down-level.yml
Labels: Area: Testing

#2959 Support for changing alpn on listener callback (#2418)
  docs/api/QUIC_LISTENER_CALLBACK.md
  docs/api/QUIC_LISTENER_EVENT.md
  docs/api/QUIC_NEW_CONNECTION_INFO.md
  src/core/listener.c
  src/cs/lib/msquic_generated.cs
  src/generated/linux/listener.c.clog.h
  src/generated/linux/listener.c.clog.h.lttng.h
  src/inc/msquic.h
  src/lib.rs
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
  src/test/lib/TestListener.cpp
  src/test/lib/TestListener.h
Labels: Area: API

#2962 Make it possible to partially statically link CRT
  CMakeLists.txt
Labels: Area: Build, OS: Windows (User)

#2964 Use Partial Static CRT Linking by Default
  CMakeLists.txt
  scripts/build.ps1
Labels: Area: Build, OS: Windows (User)

#2970 Build Docker pipeline
  .azure/OneBranch.Docker.Official.yml
  .azure/dockers/ob/Dockerfile
Labels: Area: Automation

#2974 Use isolated ACR for linux
  .azure/OneBranch.Official.yml
Labels: Area: Automation

#2963 crude support for cross-arm build
  scripts/build.ps1
  scripts/get-buildconfig.ps1
  scripts/make-packages.sh
  submodules/CMakeLists.txt
Labels: Area: Build, OS: Ubuntu, OS: macOS

#2971 Follow redirect
  docs/api/ConfigurationOpen.md
Labels: Area: Documentation, external

#2968 Platform Event Queue Interface
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/platform/inline.c
  src/platform/unittest/PlatformTest.cpp
Labels: OS: Windows (User), OS: Ubuntu, OS: macOS, OS: Windows (Kernel)

#2978 Use isolated ACR for windows
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/linux/Dockerfile
  .azure/dockers/ob/windows/Dockerfile
  .azure/dockers/ob/windows/install-ewdk.ps1
  .azure/dockers/ob/windows/install-tools.ps1
  .azure/dockers/ob/windows/install.cmd
  .azure/dockers/ob/windows/win-installer-helper.psm1
Labels: Area: Automation

#2972 Support ALPN List Change via ConnectionSetConfiguration function
  docs/api/ConnectionSetConfiguration.md
  docs/api/QUIC_LISTENER_EVENT.md
  src/core/binding.c
  src/core/connection.c
  src/core/crypto.c
  src/core/crypto.h
  src/core/listener.c
  src/cs/lib/msquic_generated.cs
  src/generated/linux/listener.c.clog.h
  src/generated/linux/listener.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/quic_tls.h
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/TestListener.cpp
  src/test/lib/TestListener.h
Labels: feature request, external, Area: API, Area: Core

#2982 Added Supported Platforms to Release Docs
  docs/Release.md
Labels: Area: Documentation

#2983 Create a manual OBP to upload signed package to PMC
  .azure/OneBranch.Publish.yml
Labels: Area: Automation

#2984 Remove main trigger for publish OBP
  .azure/OneBranch.Publish.yml
Labels: Area: Automation

#2985 Fix QUIC Statistics Size Helpers
  src/inc/msquic.h
Labels: Area: API

#2986 Enable minimal datagram support
  .github/workflows/cargo.yml
  .gitignore
  scripts/build.rs
  src/lib.rs
Labels: external, Language: Rust

#2987 Build and sign arm/arm64 Onebranch pipeline for linux
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/azure-pipelines.ci.yml
  .azure/dockers/ob/linux/Dockerfile
  .azure/dockers/ob/linux/arm-cross-compile-sources.list
  .azure/obtemplates/build-linux.yml
  cmake/toolchains/aarch64-linux.cmake
  cmake/toolchains/arm-linux.cmake
  cmake/toolchains/arm-pi-gnueabihf.toolchain.cmake
  scripts/build.ps1
  scripts/make-packages.sh
  scripts/package-distribution.ps1
  scripts/prepare-machine.ps1
  submodules/CMakeLists.txt
Labels: Area: Automation

#2989 retry pthread create if it failes with ENOKEY
  src/platform/platform_posix.c
Labels: OS: Ubuntu, Bug: Platform

#2990 Backport changes to v2.1.0 to unblock linux release
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/azure-pipelines.ci.yml
  .azure/dockers/ob/linux/Dockerfile
  .azure/dockers/ob/linux/arm-cross-compile-sources.list
  .azure/dockers/ob/windows/Dockerfile
  .azure/dockers/ob/windows/install-ewdk.ps1
  .azure/dockers/ob/windows/install-tools.ps1
  .azure/dockers/ob/windows/install.cmd
  .azure/dockers/ob/windows/win-installer-helper.psm1
  .azure/obtemplates/build-linux.yml
  cmake/toolchains/aarch64-linux.cmake
  cmake/toolchains/arm-linux.cmake
  cmake/toolchains/arm-pi-gnueabihf.toolchain.cmake
  scripts/build.ps1
  scripts/get-buildconfig.ps1
  scripts/make-packages.sh
  scripts/package-distribution.ps1
  scripts/prepare-machine.ps1
  src/inc/msquic.h
  src/platform/platform_posix.c
  submodules/CMakeLists.txt
Labels: Area: Automation, Area: Core, Backport

#2994 Fix linux packaging
  .azure/obtemplates/build-linux-packages.yml
  .azure/obtemplates/build-linux.yml
  scripts/build.ps1
  scripts/make-packages.sh
Labels: Area: Automation

#2998 retry pthread_create also on ENOENT
  src/platform/platform_posix.c
Labels: Area: Core

#2999 Fix: Alpn Change Test
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing, external

#2967 [Extension]: Grease Quic Bit Support
  README.md
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
  scripts/prepare-machine.ps1
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/core/crypto_tls.c
  src/core/inline.c
  src/core/packet.c
  src/core/packet.h
  src/core/packet_builder.c
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/core/unittest/TransportParamTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/crypto_tls.c.clog.h
  src/generated/linux/crypto_tls.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/lib.rs
  src/manifest/clog.sidecar
  src/plugins/dbg/quictypes.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/tools/attack/packet_writer.cpp
  src/tools/interop/interop.cpp
  src/tools/interop/interop.h
Labels: Area: Protocol Updates, external, Area: API, Area: Core

#2995 Specify libssl1.1 dependency on deb package
  scripts/make-packages.sh
Labels: Area: Build, OS: Ubuntu

#3005 Github actions for building linux arm/arm64
  .github/workflows/build-containers.yml
  .github/workflows/cross-compile.yml
Labels: Area: Automation

#3008 Convert throughput tests from data transferred to timed.
  scripts/RemoteTests.json
Labels: Area: Performance, Area: Automation

#3009 Fix PGO pipeline bugs
  .azure/templates/make-pgo-pr.yml
Labels: Area: Performance, Area: Automation, Bug: Test/Tool

#3014 Add PGO support for OpenSSL
  .azure/azure-pipelines.periodic.yml
  .azure/templates/make-pgo-pr.yml
  scripts/make-pgo-pr.ps1
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance, Area: Automation

#2992 Platform Loop Refactor
  scripts/performance.ps1
  scripts/run-gtest.ps1
  scripts/test.ps1
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.sharedec.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
  src/core/library.c
  src/core/worker.c
  src/generated/linux/datapath_epoll.c.clog.h
  src/generated/linux/datapath_epoll.c.clog.h.lttng.h
  src/generated/linux/datapath_kqueue.c.clog.h
  src/generated/linux/datapath_kqueue.c.clog.h.lttng.h
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/generated/linux/platform_worker.c.clog.h
  src/generated/linux/platform_worker.c.clog.h.lttng.h
  src/inc/quic_datapath.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winuser.h
  src/manifest/clog.sidecar
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/platform_internal.h
  src/platform/platform_posix.c
  src/platform/platform_worker.c
  src/platform/unittest/PlatformTest.cpp
  src/platform/unittest/main.cpp
Labels: OS: Windows (User), OS: Ubuntu, OS: macOS, Area: Core, OS: FreeBSD

#3017 Remove unused YieldProcessor macros
  src/inc/quic_platform_posix.h
Labels: OS: Ubuntu, OS: macOS

#3018 Fix abstract comment in quic_platform_posix.h that just claims it's for linux
  src/inc/quic_platform_posix.h
Labels: Area: Documentation

#3019 Remove QUIC_USE_EXECUTION_CONTEXTS from CxPlat
  src/inc/quic_platform.h
  src/platform/platform_worker.c
Labels: Area: Performance

#3020 Fix kqueue generic events
  src/inc/quic_platform_posix.h
  src/platform/datapath_kqueue.c
  src/platform/platform_posix.c
  src/platform/unittest/PlatformTest.cpp
Labels: OS: macOS, OS: FreeBSD

#3024 Automate PGO for Shared EC and XDP
  .azure/azure-pipelines.periodic.yml
  scripts/make-pgo-pr.ps1
  scripts/performance-helper.psm1
Labels: Area: Performance, Area: Automation

#3029 Add QUIC_STATUS_ALPN_IN_USE to C# interop
  src/cs/lib/MsQuicException.cs
  src/cs/lib/msquic.cs
  src/cs/lib/msquic_generated_linux.cs
  src/cs/lib/msquic_generated_macos.cs
  src/cs/lib/msquic_generated_windows.cs
Labels: Area: API, Language: C#

#3030 Only run PGO weekly. Only use non-loopback results for PGO.
  .azure/azure-pipelines.periodic.yml
Labels: Area: Performance, Area: Automation

#3031 add 0x63 status code
  src/cs/lib/MsQuicException.cs
  src/cs/lib/msquic.cs
  src/cs/lib/msquic_generated_linux.cs
  src/cs/lib/msquic_generated_macos.cs
Labels: external, Area: API, Language: C#

#3027 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.sharedec.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3032 Replace Newtonsoft.Json with System.Text.Json
  scripts/generatevpackpat/Program.cs
  scripts/generatevpackpat/generatevpackpat.csproj
Labels: external, Language: C#
