Repository microsoft/msquic, pull requests merged in 2022-12, with the labels that each got.

#3260 Extend Pool Allocation Functionality
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
  src/inc/quic_platform_winuser.h
Labels: OS: Windows (User)

#3267 Use Ubuntu 20.04 to Build OpenSSL-Systemcrypto Variant
  .azure/azure-pipelines.ci.yml
Labels: Area: Build, OS: Ubuntu

#3266 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3186 Async ticket validation
  docs/api/ConnectionResumptionTicketValidationComplete.md
  src/core/api.c
  src/core/api.h
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/crypto.h
  src/core/library.c
  src/core/operation.h
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/quic_trace.h
  src/plugins/dbg/quictypes.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#3275 Fix CodeQL break
  .github/workflows/codeql-analysis.yml
Labels: Area: Automation

#3283 Windows User Mode Datapath Improvements
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
  src/core/binding.c
  src/core/binding.h
  src/core/packet_builder.c
  src/inc/quic_datapath.h
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/pcp.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/attack/attack.cpp
  src/tools/lb/loadbalancer.cpp
Labels: OS: Windows (User), Area: Performance

#3282 Simplify winuser SQE->CQE mapping and remove IO completion keys
  CMakeLists.txt
  src/inc/quic_platform_winuser.h
  src/platform/datapath_raw_xdp.c
  src/platform/datapath_winuser.c
  src/platform/platform_winuser.c
Labels: OS: Windows (User)

#3288 RPS Test Diagnostics Improvements
  src/perf/bin/appmain.cpp
  src/perf/lib/PerfCommon.h
  src/perf/lib/RpsClient.cpp
Labels: Area: Performance

#3286 Continue teasing apart receive completion path
  CMakeLists.txt
  src/platform/datapath_winuser.c
Labels: OS: Windows (User)

#3291 Some MTU Test Improvements
  CMakeLists.txt
  src/test/lib/MtuTest.cpp
Labels: Area: Testing

#3284 Support Inline StreamSends
  src/core/api.c
Labels: Area: Performance, Area: API

#3292 Support multiple outstanding receives
  src/platform/datapath_winuser.c
Labels: OS: Windows (User)

#3290 Update Posix Platforms to Use Route Queue
  src/core/binding.c
  src/core/connection.c
  src/generated/linux/datapath_epoll.c.clog.h
  src/generated/linux/datapath_epoll.c.clog.h.lttng.h
  src/generated/linux/datapath_kqueue.c.clog.h
  src/generated/linux/datapath_kqueue.c.clog.h.lttng.h
  src/inc/quic_datapath.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
Labels: OS: Ubuntu, OS: macOS, Area: Performance, OS: Android, OS: iOS, OS: FreeBSD

#3274 Refactor epoll Send Path
  scripts/log.ps1
  src/generated/linux/datapath_epoll.c.clog.h
  src/generated/linux/datapath_epoll.c.clog.h.lttng.h
  src/platform/datapath_epoll.c
  src/platform/platform_internal.h
Labels: OS: Ubuntu, Area: Performance

#3297 Posix NUMA Node Support
  .github/workflows/codeql-analysis.yml
  CMakeLists.txt
  scripts/prepare-machine.ps1
  scripts/qns.Dockerfile
  src/inc/CMakeLists.txt
  src/platform/platform_posix.c
Labels: OS: Ubuntu, Area: Performance

#3303 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3258 Add support for RIO
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), Area: Performance

#3304 Linux Receive Path Improvements
  CMakeLists.txt
  scripts/qns.Dockerfile
  src/generated/linux/datapath_epoll.c.clog.h
  src/generated/linux/datapath_epoll.c.clog.h.lttng.h
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu, Area: Performance

#3308 rust to support ticket completion api
  src/lib.rs
Labels: Language: Rust

#3312 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3314 Fix onebranch linux build docker
  .azure/dockers/ob/linux/Dockerfile
Labels: Area: Build

#3315 Use new onebranch linux docker image
  .azure/OneBranch.Official.yml
Labels: Area: Build
