Repository microsoft/msquic, pull requests merged in 2022-10, with the labels that each got.

#3095 Update release documentation
  docs/Release.md
Labels: Area: Documentation

#3094 Add 2.1.2 to downlevel test
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3102 Fix VNE TP test.
  src/test/lib/HandshakeTest.cpp
Labels: Bug: Test/Tool

#3107 Fix iOS Build Errors
  src/inc/msquic_posix.h
  src/test/bin/quic_gtest.cpp
Labels: Area: Build, OS: Ubuntu, OS: macOS

#3104 Fix XDP Cleanup on Init Failure Crash
  src/platform/datapath_raw.c
Labels: OS: Windows (User), Bug: Platform, Area: Lola

#3106 Disable Preview Feature Tests on Official Builds
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  scripts/build.ps1
  src/core/unittest/SettingsTest.cpp
  src/inc/msquicp.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
Labels: Area: Build, Area: Testing, Area: Automation

#3108 Backport changes to release/2.0 for OBP builds
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/linux/Dockerfile
  .azure/dockers/ob/windows/Dockerfile
  .azure/dockers/ob/windows/install-ewdk.ps1
  .azure/dockers/ob/windows/install-tools.ps1
  .azure/dockers/ob/windows/install.cmd
  .azure/dockers/ob/windows/win-installer-helper.psm1
Labels: Area: Build, Area: Automation, Backport

#2588 Avoid fetching OpenSSL digests and ciphers
  src/generated/linux/crypt_openssl.c.clog.h
  src/generated/linux/crypt_openssl.c.clog.h.lttng.h
  src/platform/crypt_openssl.c
  src/platform/platform_posix.c
  src/platform/tls_openssl.c
Labels: TLS: OpenSSL, external, Area: Performance, blocked

#3113 Update Down-Level Tests
  .github/workflows/test-down-level.yml
  scripts/build.ps1
Labels: Area: Testing, Area: Automation

#3117 Fix Race Condition in HPS Client
  src/perf/lib/HpsClient.cpp
  src/perf/lib/HpsClient.h
Labels: Area: Performance, Bug: Test/Tool

#3119 Activate Grease Quic Bit in Interop Server
  src/tools/interopserver/InteropServer.cpp
Labels: Area: Interop

#3131 Fixed ticket error in client code #3130
  src/tools/sample/sample.c
Labels: external, Bug: Test/Tool

#3122 Fix passing pointer-pointer, skip inevitable SEGV case
  src/fuzzing/fuzz.cc
Labels: Area: Testing, Area: Stress

#3135 Add -StaticCRT switch to build script and never use partial static crt linking for debug builds
  CMakeLists.txt
  scripts/build.ps1
Labels: Area: Build

#3121 Async IO Support for XDP
  scripts/performance.ps1
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
  src/core/worker.c
  src/generated/linux/datapath_raw_xdp.c.clog.h
  src/generated/linux/datapath_raw_xdp.c.clog.h.lttng.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/manifest/clog.sidecar
  src/platform/datapath_raw_xdp.c
  src/platform/datapath_winuser.c
  src/platform/inline.c
  src/platform/platform_worker.c
  src/platform/unittest/DataPathTest.cpp
Labels: Area: Performance, Area: Lola

#3051 Initial Arch Documentation
  docs/Architecture.md
Labels: Area: Documentation

#2697 Increase Initial Packet Sizes to Help with Amplification Protection
  docs/Settings.md
  src/core/binding.c
  src/core/datagram.c
  src/core/mtu_discovery.c
  src/core/quicdef.h
  src/core/settings.c
Labels: Area: Performance, Area: Core

#3140 Fix TCP Perf Test Race Condition on Shutdown
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
Labels: Area: Performance, Bug: Test/Tool

#3139 Support QUIC Worker Polling
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
  src/core/quicdef.h
  src/core/worker.c
  src/core/worker.h
Labels: Area: Performance, Area: Core

#3143 Add Tests for Zero version in VN TP.
  src/core/connection.c
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Testing

#3147 Rename OtherVersions to AvailableVersions.
  docs/Settings.md
  src/core/connection.c
  src/core/unittest/VersionNegExtTest.cpp
  src/core/version_neg.c
  src/core/version_neg.h
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/version_neg.c.clog.h
  src/generated/linux/version_neg.c.clog.h.lttng.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
Labels: Area: Core

#3148 fix(test): allow QUIC_CONNECTION_EVENT_PEER_NEEDS_STREAMS
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#3151 Update Perf Publishing Scripts
  powershell/generate-graphs.ps1
  powershell/merge-performance.ps1
Labels: Area: Performance

#3152 Save All Histograms from Perf
  .azure/azure-pipelines.perf.yml
  scripts/performance-helper.psm1
  scripts/performance.ps1
Labels: Area: Performance, Area: Automation

#3149 Wire up ECN for Winkernel datapath
  src/platform/datapath_winkernel.c
Labels: Bug: Platform

#3161 TSG: Fix some minor issues
  docs/TSG.md
Labels: Area: Documentation

#3162 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3154 Enable Stream Stats on Perf
  scripts/RemoteTests.json
  scripts/performance.ps1
  src/core/stream_send.c
  src/perf/lib/ThroughputClient.cpp
Labels: Area: Performance, Area: Automation

#3163 Update test-down-level.yml
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3064 Fix/suppress some new clang/cppcheck warnings
  CMakeLists.txt
  src/core/api.c
  src/core/bbr.c
  src/platform/datapath_kqueue.c
  src/platform/hashtable.c
Labels: Area: Build, external

#3166 Wire up RX ECN for winkernel
  src/platform/datapath_winkernel.c
Labels: Bug: Platform

#3169 Configure ECN socket option for winkernel
  src/platform/datapath_winkernel.c
Labels: Bug: Platform

#3167 Perf Counter Snapshot Improvements
  src/core/library.c
  src/core/library.h
  src/generated/linux/library.c.clog.h
  src/generated/linux/library.c.clog.h.lttng.h
Labels: Area: Performance, Area: Logging

#3170 Improved Logging for NIC Drop Scenario
  .azure/azure-pipelines.perf.yml
  docs/Diagnostics.md
  scripts/log.ps1
  scripts/performance.ps1
  src/manifest/MsQuic.wprp
  src/manifest/MsQuicEtw.man
Labels: Area: Performance, Area: Automation, Area: Logging

#3171 Enable Back Windows ASAN Testing
  .azure/azure-pipelines.ci.yml
Labels: Area: Testing, Area: Automation

#3184 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3185 doc: no dup StreamReceiveComplete call
  docs/api/StreamReceiveComplete.md
Labels: Area: Documentation, external

#3164 Add option for some crude tracing on `stdout`
  .azure/azure-pipelines.ci.yml
  .gitignore
  CMakeLists.txt
  scripts/build.ps1
  src/generated/CMakeLists.txt
  src/generated/stdout/quic_trace.c
  src/inc/quic_trace.h
  src/platform/inline.c
Labels: external, Area: Logging

#3168 Add ECN support: ECN validation
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
  src/core/connection.c
  src/core/loss_detection.c
  src/core/packet_builder.c
  src/core/packet_builder.h
  src/core/packet_space.h
  src/core/path.c
  src/core/path.h
  src/core/quicdef.h
  src/core/send.c
  src/core/send.h
  src/core/sent_packet_metadata.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/loss_detection.c.clog.h
  src/generated/linux/loss_detection.c.clog.h.lttng.h
  src/generated/linux/send.c.clog.h
  src/generated/linux/send.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/perf/lib/HpsClient.h
  src/perf/lib/PerfCommon.h
  src/perf/lib/PerfServer.h
  src/perf/lib/RpsClient.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/ThroughputClient.h
  src/plugins/trace/dll/DataModel/QuicEvent.cs
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
  src/tools/etw/quicetw.h
Labels: Area: Core

#3116 call spinquic from oss-fuzz
  src/tools/spin/spinquic.cpp
Labels: Area: Testing, Area: Stress

#3187 Increase BVT Timeout
  .azure/templates/run-bvt.yml
Labels: Area: Testing, Area: Automation

#3172 Support Fixed Server ID Encoded Load Balancing Mode
  docs/Deployment.md
  src/core/connection.c
  src/core/library.c
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/clog.sidecar
Labels: Area: API, Area: Core

#3197 Fix Some WPA Plugin Stuff
  src/plugins/trace/dll/Properties/launchSettings.json
  src/plugins/trace/dll/Tables/QuicConnectionTable.cs
  src/plugins/trace/dll/Tables/QuicExecutionTable.cs
  src/plugins/trace/dll/Tables/QuicNetworkTable.cs
  src/plugins/trace/dll/Tables/QuicSchedulingTable.cs
  src/plugins/trace/dll/Tables/QuicStreamStateTable.cs
  src/plugins/trace/dll/Tables/QuicTxBlockedTable.cs
  src/plugins/trace/dll/Tables/QuicWorkerActivityTable.cs
  src/plugins/trace/exe/QuicTrace.csproj
  src/plugins/trace/exe/SingleFileAssemblyLoader.cs
Labels: Bug: Test/Tool

#3194 Tests Wait Longer
  src/test/lib/EventTest.cpp
Labels: Area: Testing, Bug: Test/Tool
