Repository microsoft/msquic, pull requests merged in 2022-03, with the labels that each got.

#2443 Remove email from optional reviewers
  scripts/generate-git-checkin.ps1
Labels: Area: Automation

#2442 Backport PGO and rust fixes to Ni
  CMakeLists.txt
  scripts/generate-git-checkin.ps1
  src/lib.rs
Labels: Backport

#2447 release/2.0 - Wrap CID Parameters in PREVIEW
  src/inc/msquic.h
Labels: Area: API

#2445 Support CIBIR Extension
  README.md
  docs/Settings.md
  src/core/binding.c
  src/core/cid.h
  src/core/connection.c
  src/core/connection.h
  src/core/crypto_tls.c
  src/core/library.c
  src/core/library.h
  src/core/listener.c
  src/core/listener.h
  src/core/lookup.c
  src/core/quicdef.h
  src/core/transport_params.h
  src/core/unittest/TransportParamTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/crypto_tls.c.clog.h
  src/generated/linux/crypto_tls.c.clog.h.lttng.h
  src/generated/linux/listener.c.clog.h
  src/generated/linux/listener.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/lib.rs
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#2451 Fix possible infinite loop in priority stream scheduling
  src/core/send.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Bug: Core

#2450 Fix dotnet generator (#2446) (Backport to Ni)
  .github/workflows/check-dotnet.yml
  scripts/generate-dotnet.ps1
  src/cs/lib/msquic_generated.cs
Labels: Backport, Language: C#

#2453 Update main to v2.1
  .azure/azure-pipelines.qns.yml
  .azure/obtemplates/push-vpack.yml
  CMakeLists.txt
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
Labels: Area: Build

#2452 Fix possible infinite loop in priority stream scheduling (#2451) (Backport to Ni)
  src/core/send.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Bug: Core, Backport

#2454 Improve crash dump debugging in CI
  CMakeLists.txt
  scripts/log.ps1
  scripts/prepare-machine.ps1
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
  scripts/spin.ps1
  scripts/test.ps1
  src/inc/CMakeLists.txt
Labels: OS: Ubuntu, OS: macOS, Area: Automation

#2461 Add size support to QUIC_STATISTICS_V2
  src/core/connection.c
  src/core/settings.c
Labels: Area: Core

#2464 Fixes for Scorecard Action
  .github/workflows/scorecards-analysis.yml
Labels: Area: Automation

#2463 Extra Protection Around Stream Send Queue
  src/core/send.c
  src/core/send.h
  src/core/stream.c
Labels: Bug: Core, Area: Core

#2382 Add cc window size in connection statistics
  src/core/congestion_control.h
  src/core/connection.c
  src/core/connection.h
  src/core/cubic.c
  src/core/inline.c
  src/cs/lib/msquic_generated.cs
  src/generated/linux/connection.h.clog.h
  src/generated/linux/connection.h.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
Labels: external, Area: API, Area: Core

#2472 Expose shutdown in RUST's connection object
  src/lib.rs
Labels: external, Language: Rust

#2474 Build on windows-2019 (release/1.1)
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-winkernel.yml
Labels: Area: Build, OS: Windows (User), OS: Windows (Kernel), Area: Automation

#2477 release/2.0 CP - Extra Protection Around Stream Send Queue #2463
  src/core/send.c
  src/core/send.h
  src/core/stream.c
Labels: Backport

#2473 Build on windows-2019 (release/1.0)
  .azure/azure-pipelines.ci.yml
  .azure/templates/build-config-winkernel.yml
Labels: Area: Build, OS: Windows (User), OS: Windows (Kernel), Area: Automation

#2475 Remove Old QNS Files and Update Version
  .azure/azure-pipelines.qns.yml
  .azure/templates/run-qns.yml
  scripts/update-version.ps1
Labels: Area: Build, Area: Automation

#2457 Add CIBIR Support to SecNetPerf
  src/perf/lib/HpsClient.cpp
  src/perf/lib/PerfHelpers.h
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/RpsClient.cpp
  src/perf/lib/RpsClient.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/ThroughputClient.cpp
  src/perf/lib/ThroughputClient.h
Labels: Area: Testing, Area: Performance

#2480 Add note about required prepare-machine invocation to TEST.md
  docs/TEST.md
Labels: Area: Documentation

#2476 Add cargo publish --dry-run to CI
  .azure/templates/cargo.yml
  Cargo.toml
Labels: Area: Automation, Language: Rust

#2481 release/2.0 CP - Add cargo publish --dry-run to CI (#2476)
  .azure/templates/cargo.yml
  Cargo.toml
Labels: Backport

#2459 Lazily initialize datapath for core affinitization plumbing
  src/core/library.c
  src/core/registration.c
  src/generated/linux/library.c.clog.h
  src/generated/linux/library.c.clog.h.lttng.h
  src/generated/linux/registration.c.clog.h
  src/generated/linux/registration.c.clog.h.lttng.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvents.cs
Labels: Area: Core

#2483 Update BUILD.md
  docs/BUILD.md
Labels: Area: Documentation, Area: Build

#2485 Fix Rust Issues
  src/lib.rs
Labels: Language: Rust

#2479 Pass CIBIR ID to XDP
  scripts/prepare-machine.ps1
  src/core/listener.c
  src/inc/quic_datapath.h
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_xdp.c
Labels: Area: Lola

#2487 Suppress empty file warning in msvc
  CMakeLists.txt
Labels: Area: Build, OS: Windows (User)

#2493 Fix onebranch builds after removing 32 bit
  scripts/onebranch-build-kernel.cmd
Labels: Area: Build, Area: Automation

#2490 release/1.0 - Disable Perf Tests
  .azure/azure-pipelines.ci.yml
Labels: Area: Performance, Area: Automation

#2484 Move Cargo to GH Action
  .azure/azure-pipelines.ci.yml
  .azure/templates/cargo.yml
  .github/workflows/cargo.yml
  scripts/prepare-machine.ps1
Labels: Area: Build, Area: Automation, Language: Rust

#2488 fix packaging on macOS
  scripts/make-packages.sh
Labels: external

#2497 release/2.0 - Disable Plugin Build
  .azure/azure-pipelines.plugins.yml
Labels: Area: Automation

#2495 release/1.0 - Disable Plugin Build
  .azure/azure-pipelines.plugins.yml
Labels: Area: Automation

#2496 release/1.1 - Disable Plugin Build
  .azure/azure-pipelines.plugins.yml
Labels: Area: Automation

#2492 Run Down-Level Tests
  .github/workflows/test-down-level.yml
  scripts/prepare-machine.ps1
Labels: Area: Testing

#2494 Embed git commit hash into binary
  .azure/templates/build-config-winkernel.yml
  CMakeLists.txt
  cmake/GitCommands.cmake
  docs/Settings.md
  scripts/build.rs
  scripts/onebranch-build-kernel.cmd
  src/bin/winkernel/msquic.kernel.vcxproj
  src/bin/winkernel/msquicpriv.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/core/library.c
  src/core/library.h
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/msquic.ver
  src/lib.rs
  src/platform/platform.kernel.vcxproj
  src/tools/spin/spinquic.cpp
Labels: Area: Build

#2502 Refactor Performance Pipeline
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.perf.yml
Labels: Area: Performance, Area: Automation

#2498 Create XDP BVT test job
  .azure/azure-pipelines.ci.yml
  .azure/templates/run-bvt.yml
  scripts/run-gtest.ps1
  scripts/test.ps1
Labels: Area: Testing, Area: Automation, Area: Lola

#2504 Fix kqueue timeout with shared ec mode
  src/platform/datapath_kqueue.c
Labels: OS: macOS

#2505 Switch XDP BVT job to run on Server 2022
  .azure/azure-pipelines.ci.yml
Labels: Area: Automation

#2512 Fix Cleanup Bug in OOM Case
  src/platform/platform_winuser.c
Labels: OS: Windows (User)

#2510 Fix kqueue timeout with shared ec mode (#2504)
  src/platform/datapath_kqueue.c
Labels: OS: macOS, Backport

#2511 Add Retry to Some Tests
  src/test/lib/HandshakeTest.cpp
  src/test/lib/QuicDrill.cpp
Labels: Area: Testing

#2507 Fixes for Catching Breaking Changes
  .github/workflows/test-down-level.yml
  scripts/run-gtest.ps1
Labels: Area: Testing, Area: Automation

#2508 Update Logs
  src/core/loss_detection.c
  src/generated/linux/loss_detection.c.clog.h
  src/generated/linux/loss_detection.c.clog.h.lttng.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/tools/etw/trace.c
Labels: Area: Build, Area: Logging

#2513 Mark CxPlatFree as not allowing an optional input
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winuser.h
  src/platform/platform_posix.c
  src/platform/platform_winuser.c
Labels: Area: Build

#2506 Refactor prepare-machine.ps1
  .azure/OneBranch.Tests.Official.yml
  .azure/OneBranch.Tests.PullRequest.yml
  .azure/azure-pipelines.ci.yml
  .azure/azure-pipelines.perf.yml
  .azure/azure-pipelines.periodic.yml
  .azure/obtemplates/build-distribution.yml
  .azure/obtemplates/build-linux-packages.yml
  .azure/obtemplates/build-linux.yml
  .azure/obtemplates/run-bvt.yml
  .azure/templates/build-config-user.yml
  .azure/templates/build-config-winkernel.yml
  .azure/templates/build-distribution.yml
  .azure/templates/build-nuget.yml
  .azure/templates/merge-publish-coverage.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-dotnet.yml
  .azure/templates/run-performance.yml
  .azure/templates/run-quicinterop.yml
  .azure/templates/run-spinquic.yml
  .github/workflows/cargo.yml
  .github/workflows/check-clog.yml
  .github/workflows/check-dotnet.yml
  .github/workflows/test-down-level.yml
  .github/workflows/wan-perf.yml
  docs/BUILD.md
  docs/Diagnostics.md
  docs/TEST.md
  scripts/prepare-machine.ps1
  scripts/test.ps1
Labels: Area: Build, Area: Testing, Area: Automation

#2514 release/2.0 - CP #2508, #2511, #2512 & #2513
  src/core/loss_detection.c
  src/generated/linux/loss_detection.c.clog.h
  src/generated/linux/loss_detection.c.clog.h.lttng.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winuser.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/platform_posix.c
  src/platform/platform_winuser.c
  src/test/lib/HandshakeTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/etw/trace.c
Labels: Backport

#2515 Fix Configuration in Dbg Plugin
  src/plugins/dbg/configuration.cpp
Labels: Bug: Test/Tool

#2521 Don't Fail on Regression for PGO Runs
  .azure/azure-pipelines.perf.yml
  src/bin/winuser/pgo_x64/msquic.pgd
Labels: Area: Performance, Area: Automation

#2523 Add XDP driver installation to automation
  .azure/azure-pipelines.ci.yml
  scripts/prepare-machine.ps1
Labels: Area: Testing, Area: Automation, Area: Lola

#2519 Raw datapath processor candidates knob
  docs/Settings.md
  src/core/library.c
  src/core/library.h
  src/core/registration.c
  src/core/unittest/SettingsTest.cpp
  src/core/unittest/main.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/library.c.clog.h
  src/generated/linux/library.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/quic_datapath.h
  src/inc/quic_platform.h
  src/manifest/clog.sidecar
  src/perf/lib/SecNetPerfMain.cpp
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/attack/attack.cpp
  src/tools/lb/loadbalancer.cpp
  src/tools/pcp/pcp.cpp
  src/tools/reach/reach.cpp
Labels: Area: API, Area: Lola

#2522 Move Plugins to GitHub Action
  .azure/azure-pipelines.plugins.yml
  .azure/templates/build-config-dbgext.yml
  .azure/templates/build-config-quictrace.yml
  .github/workflows/plugins.yml
  .github/workflows/wan-perf.yml
Labels: Area: Build, Area: Automation

#2520 CodeQL - Add Quality
  .github/codeql/codeql-config.yml
Labels: Area: Automation

#2528 Backport 32 bit removal to Ni
  .azure/azure-pipelines.ci.yml
  .azure/obtemplates/build-winkernel.yml
  msquic.kernel.sln
  scripts/onebranch-build-kernel.cmd
  scripts/prepare-package.ps1
  src/bin/winkernel/msquic.kernel.vcxproj
  src/bin/winkernel/msquicpriv.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/inc/msquic.h
  src/manifest/manifest.kernel.vcxproj
  src/perf/bin/secnetperfdriver.kernel.vcxproj
  src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
  src/perf/lib/perflib.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, OS: Windows (Kernel), Backport

#2531 Abstract HFDK Labels per Version
  src/core/connection.c
  src/core/crypto.c
  src/core/packet.c
  src/core/packet.h
  src/inc/quic_crypt.h
  src/inc/quic_tls.h
  src/perf/lib/Tcp.cpp
  src/platform/crypt.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/CryptTest.cpp
  src/platform/unittest/TlsTest.cpp
  src/tools/attack/attack.cpp
  src/tools/attack/packet_writer.cpp
  src/tools/attack/packet_writer.h
Labels: TLS: OpenSSL, TLS: Schannel, Area: Protocol Updates, Area: Core

#2533 Fix YML Path Triggers
  .github/workflows/plugins.yml
  .github/workflows/wan-perf.yml
Labels: Area: Automation

#2532 Fix test script not failing when only crashes occur
  scripts/run-gtest.ps1
Labels: Area: Testing

#2530 Make GlobalRawDataPathProcsSetAndGet pass with 1 cpu
  src/core/unittest/SettingsTest.cpp
Labels: OS: macOS

#2534 Try to Fix Cargo Test on Ubuntu
  .github/workflows/cargo.yml
Labels: Area: Testing, Area: Automation, Language: Rust

#2458 Version Negotiation Draft5+ changes
  docs/Settings.md
  docs/Versions.md
  docs/api/GetParam.md
  docs/api/QUIC_SETTINGS.md
  src/core/binding.c
  src/core/configuration.c
  src/core/connection.c
  src/core/crypto.c
  src/core/frame.h
  src/core/library.c
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/VersionNegExtTest.cpp
  src/core/version_neg.c
  src/core/version_neg.h
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/generated/linux/version_neg.c.clog.h
  src/generated/linux/version_neg.c.clog.h.lttng.h
  src/inc/msquic.hpp
  src/inc/msquicp.h
  src/inc/quic_platform.h
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
  src/tools/interop/interop.cpp
Labels: Area: Protocol Updates, Area: API, Area: Core

#2539 Don't enable datapath queued sends when shared ec is enabled
  CMakeLists.txt
Labels: Area: Lola

#2547 Fix file permissions.
  src/inc/msquic.h
  src/lib.rs
Labels: Area: Build

#2546 Add QuicLoad Tool
  src/tools/CMakeLists.txt
  src/tools/load/CMakeLists.txt
  src/tools/load/load.cpp
Labels: Area: Testing, Area: Stress

#2550 Use Mermaid for API Hierarchy Chart
  docs/API.md
  docs/images/api_objects.png
Labels: Area: Documentation

#2551 Support Building Release NuGet Packages
  .azure/OneBranch.Official.yml
  .azure/obtemplates/build-nuget.yml
Labels: Area: Automation

#2554 release/2.0 CP - Support Building Release NuGet Packages (#2551)
  .azure/OneBranch.Official.yml
  .azure/obtemplates/build-nuget.yml
Labels: Backport

#2553 Accumulator logic for MAX_DATA updates
  src/core/send.h
  src/core/stream_recv.c
Labels: Bug: Core, Area: Core

#2555 release/2.0 CP - Accumulator logic for MAX_DATA updates #2553
  src/core/send.h
  src/core/stream_recv.c
Labels: Backport

#2562 Misc Updates
  .github/workflows/cargo.yml
  .github/workflows/check-clog.yml
  .github/workflows/check-dotnet.yml
  .github/workflows/mirror-repo.yml
  .github/workflows/test-down-level.yml
  .github/workflows/wan-perf.yml
  docs/Release.md
Labels: Area: Documentation, Area: Automation

#2564 Refactor for Future NEW_TOKEN Support
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/inline.c
  src/core/packet.c
  src/core/packet.h
Labels: Area: Protocol Updates, Area: Core

#2566 Only compute TailBuffer in FreeBuffer on debug builds
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
Labels: OS: Ubuntu, OS: macOS

#2537 Light up unit tests on XDP platform
  .azure/azure-pipelines.ci.yml
  scripts/run-gtest.ps1
  scripts/test.ps1
  src/inc/quic_datapath.h
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_xdp.c
  src/platform/unittest/DataPathTest.cpp
  src/platform/unittest/main.cpp
Labels: Area: Testing, Area: Lola

#2577 [RUST] Implements stats v2 struct and missing stream events
  Cargo.toml
  src/lib.rs
Labels: external, Language: Rust

#2575 TSG for Windows Packet Capture
  docs/TSG.md
Labels: Area: Documentation, OS: Windows (User), OS: Windows (Kernel)

#2576 Add URO debugging to TSG
  docs/TSG.md
  docs/images/ptp-timestamp-config.png
Labels: Area: Documentation

#2579 2.0 CP - [RUST] Implements stats v2 struct and missing stream events
  .azure/azure-pipelines.qns.yml
  .azure/obtemplates/push-vpack.yml
  CMakeLists.txt
  Cargo.toml
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
  src/lib.rs
Labels: Backport

#2548 QUIC Version 2 support
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/crypto_tls.c
  src/core/inline.c
  src/core/packet.c
  src/core/packet.h
  src/core/packet_builder.c
  src/core/quicdef.h
  src/core/send.c
  src/core/send.h
  src/core/stream_send.c
  src/core/unittest/TicketTest.cpp
  src/core/unittest/VersionNegExtTest.cpp
  src/core/version_neg.c
  src/core/version_neg.h
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/packet.c.clog.h
  src/generated/linux/packet.c.clog.h.lttng.h
  src/generated/linux/version_neg.c.clog.h
  src/generated/linux/version_neg.c.clog.h.lttng.h
  src/inc/quic_tls.h
  src/inc/quic_versions.h
  src/manifest/clog.sidecar
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/CryptTest.cpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/tools/attack/attack.cpp
  src/tools/attack/packet_writer.cpp
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
Labels: Area: Protocol Updates, Area: Core

#2571 Fix clog2text not being available during test runs
  .azure/templates/build-config-user.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-quicinterop.yml
  .azure/templates/run-spinquic.yml
  scripts/log.ps1
  scripts/prepare-machine.ps1
Labels: Area: Automation, Area: Logging

#2572 Enable many more tests for XDP
  .azure/azure-pipelines.ci.yml
  scripts/test.ps1
  src/generated/linux/datapath_raw_socket.c.clog.h
  src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
  src/inc/msquic.hpp
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_socket.c
  src/platform/unittest/DataPathTest.cpp
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/BasicTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/DatagramTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/MtuTest.cpp
  src/test/lib/OwnershipTest.cpp
  src/test/lib/PathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/TestListener.cpp
Labels: Area: Testing, Area: Lola

#2569 Pass USE_SUPPLIED_CREDS to Schannel
  docs/api/QUIC_CREDENTIAL_CONFIG.md
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/lib.rs
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: TLS: Schannel, Area: API

#2591 Stream Shutdown on Failure in Operation Cleanup
  src/core/operation.c
Labels: Bug: Core

#2593 Remove library git hash and datapath processors from preview features
  src/inc/msquic.h
Labels: Area: API

#2592 Fix listener stop documentation in api.md
  docs/API.md
Labels: Area: Documentation

#2594 Stream Shutdown on Failure in Operation Cleanup (#2591)
  src/core/operation.c
Labels: Bug: Core, Backport

#2596 No Perf on Release Branches
  .azure/azure-pipelines.ci.yml
  .github/workflows/wan-perf.yml
Labels: Area: Performance

#2595 One Connection/Stream Perf Test for Latency Data
  .azure/azure-pipelines.perf.yml
  .github/workflows/wan-perf.yml
  scripts/RemoteTests.json
Labels: Area: Performance
