Repository microsoft/msquic, pull requests merged in 2022-02, with the labels that each got.

#2347 Updates for ACK Frequency Draft 2
  src/core/ack_tracker.c
  src/core/ack_tracker.h
  src/core/connection.c
  src/core/crypto_tls.c
  src/core/frame.c
  src/core/frame.h
  src/core/send.c
  src/core/unittest/SpinFrame.cpp
  src/core/unittest/main.h
  src/generated/linux/frame.c.clog.h
  src/generated/linux/frame.c.clog.h.lttng.h
  src/manifest/clog.sidecar
Labels: Area: Core

#2331 Switch windows-latest to windows-2022
  .azure/azure-pipelines.ci.yml
Labels: Area: Automation

#2095 Add soversion to msquic
  .azure/azure-pipelines.qns.yml
  .azure/obtemplates/push-vpack.yml
  CMakeLists.txt
  scripts/make-packages.sh
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/update-version.ps1
  scripts/write-versions.ps1
  src/bin/CMakeLists.txt
  src/distribution/Info.plist
  src/generated/CMakeLists.txt
  src/inc/msquic.ver
  src/platform/platform_posix.c
Labels: Area: Build, OS: Ubuntu, OS: macOS

#2271 Make settings configuration backwards compatible in the future
  scripts/clog.inputs
  src/core/configuration.c
  src/core/connection.c
  src/core/library.c
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/CMakeLists.txt
  src/core/unittest/SettingsTest.cpp
  src/generated/linux/SettingsTest.cpp.clog.h
  src/generated/linux/quic.clog_SettingsTest.cpp.clog.h.c
  src/inc/msquic.h
  src/test/lib/ApiTest.cpp
Labels: Area: Core

#2342 Add Unknown/Default Datagram Send State
  docs/api/QUIC_CONNECTION_EVENT.md
  src/inc/msquic.h
  src/test/lib/TestConnection.cpp
Labels: Area: API

#2352 Update .NET to 6.0 (Which is LTS)
  .azure/templates/run-dotnet.yml
  src/cs/lib/msquic.csproj
  src/cs/tool/MsQuicTool.csproj
Labels: Area: Build

#2312 Remove Sync Stream Start
  docs/api/StreamSend.md
  docs/api/StreamStart.md
  src/core/api.c
  src/core/api.h
  src/core/stream_send.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/lib.rs
  src/test/lib/ApiTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/tools/post/post.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#2322 Remove Level from SetParam/GetParam
  docs/Diagnostics.md
  docs/Settings.md
  docs/Versions.md
  docs/api/GetParam.md
  docs/api/SetParam.md
  src/core/api.c
  src/core/api.h
  src/core/connection.c
  src/core/library.c
  src/core/library.h
  src/core/operation.h
  src/cs/lib/msquic_generated.cs
  src/generated/linux/api.c.clog.h
  src/generated/linux/api.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/msquichelper.h
  src/inc/msquicp.h
  src/lib.rs
  src/manifest/clog.sidecar
  src/perf/lib/HpsClient.cpp
  src/perf/lib/PerfHelpers.h
  src/perf/lib/PerfServer.cpp
  src/perf/lib/RpsClient.cpp
  src/perf/lib/ThroughputClient.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/OwnershipTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/TestListener.cpp
  src/test/lib/TestStream.cpp
  src/tools/interop/interop.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
  src/tools/ip/quicip.h
  src/tools/ip/server/quicipserver.cpp
  src/tools/reach/reach.cpp
  src/tools/sample/sample.c
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#2346 Async Listener Stop
  docs/api/ListenerClose.md
  docs/api/ListenerStop.md
  src/core/binding.c
  src/core/listener.c
  src/core/listener.h
  src/generated/linux/listener.c.clog.h
  src/generated/linux/listener.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/quic_platform_posix.h
  src/manifest/clog.sidecar
  src/perf/lib/PerfServer.cpp
  src/platform/platform_posix.c
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/TestListener.cpp
Labels: Area: API, Area: Core

#2379 Dependabot Cleanup
  .github/dependabot.yml
  .github/workflows/check-clog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-publish.yml
  .github/workflows/mirror-repo.yml
  .github/workflows/scorecards-analysis.yml
Labels: Area: Automation

#2375 Readd macos spinquic running
  .azure/azure-pipelines.ci.yml
Labels: Area: Stress, OS: macOS

#2363 Connection ID Prefixes
  docs/Settings.md
  src/core/cid.h
  src/core/connection.c
  src/core/connection.h
  src/core/listener.c
  src/core/listener.h
  src/core/registration.c
  src/core/registration.h
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/quic_platform.h
  src/lib.rs
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#2381 Publish artifacts on success or failure on macOS
  .azure/templates/upload-test-artifacts.yml
Labels: Area: Stress, OS: macOS

#2371 Make StreamReceiveComplete Not Fail
  docs/api/StreamReceiveComplete.md
  src/core/api.c
  src/core/api.h
  src/core/operation.c
  src/core/stream.c
  src/core/stream.h
  src/core/stream_recv.c
  src/generated/linux/api.c.clog.h
  src/generated/linux/api.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/inline.c
  src/test/lib/DataTest.cpp
Labels: Area: API, Area: Core

#2339 Limit Receive Flush Sizes
  src/core/connection.c
  src/core/quicdef.h
Labels: Area: Performance, Area: Core

#2388 Add SetRemoteAddr to msquic.hpp
  src/inc/msquic.hpp
Labels: Area: API

#2385 Package Up MsQuicTest
  scripts/package-distribution.ps1
Labels: Area: Automation

#2389 QuicStreamSendFlush: Don't double start the stream
  src/core/stream_send.c
  src/test/bin/quic_gtest.h
  src/test/lib/EventTest.cpp
Labels: external, Area: API, Area: Core

#2397 Add "All" as Option in Issue Template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: Area: Documentation

#2393 Remove Setting OpenSSL Groups List
  src/platform/tls_openssl.c
Labels: TLS: OpenSSL

#2390 Some code comment cleanup/additions
  src/core/binding.c
  src/core/configuration.c
  src/core/connection.c
  src/core/lookup.c
  src/core/loss_detection.c
Labels: Area: Documentation, Area: Core

#2402 Legacy Compile Mode
  src/core/library.c
  src/inc/msquic.h
  src/tools/reach/reach.cpp
Labels: Area: API, Area: Core

#2386 QUIC_STATISTICS_V2
  docs/Settings.md
  src/core/connection.c
  src/core/listener.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/lib.rs
  src/perf/lib/PerfHelpers.h
  src/test/lib/DataTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/MtuTest.cpp
  src/test/lib/OwnershipTest.cpp
  src/test/lib/QuicDrill.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/tools/interop/interop.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#2336 Combined QUIC and Datapath Execution Context Support
  .azure/azure-pipelines.ci.yml
  CMakeLists.txt
  scripts/build.ps1
  scripts/clog.inputs
  src/core/worker.c
  src/core/worker.h
  src/generated/linux/datapath_epoll.c.clog.h
  src/generated/linux/datapath_epoll.c.clog.h.lttng.h
  src/generated/linux/datapath_kqueue.c.clog.h
  src/generated/linux/datapath_kqueue.c.clog.h.lttng.h
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/generated/linux/platform_worker.c.clog.h
  src/generated/linux/platform_worker.c.clog.h.lttng.h
  src/generated/linux/quic.clog_platform_worker.c.clog.h.c
  src/inc/quic_platform.h
  src/manifest/clog.sidecar
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
  src/platform/CMakeLists.txt
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winuser.c
  src/platform/platform_internal.h
  src/platform/platform_posix.c
  src/platform/platform_winuser.c
  src/platform/platform_worker.c
  src/plugins/dbg/connection.cpp
  src/plugins/dbg/quictypes.h
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Performance, Area: Core

#2403 Fix some typos in test code
  scripts/performance-helper.psm1
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
  scripts/test.ps1
  src/test/lib/DataTest.cpp
Labels: Area: Testing

#2401 Report ABORTED for StreamSend if remotely closed
  src/core/api.c
  src/test/lib/ApiTest.cpp
Labels: Area: Core

#2254 Release Notes for v2.0
  Cargo.toml
  docs/Release.md
Labels: Area: Documentation

#2338 WAN Perf Improvements
  .github/workflows/wan-perf.yml
  scripts/emulated-performance.ps1
Labels: Area: Performance, Area: Automation

#2406 Default Building only Library
  CMakeLists.txt
  scripts/build.ps1
  scripts/build.rs
  scripts/qns.Dockerfile
Labels: Area: Build

#2408 Disable 2nd datapath in secnetperf in lola scenarios
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.cpp
Labels: Area: Lola

#2416 Clean up WAN Perf Debug Output
  scripts/emulated-performance.ps1
Labels: Area: Performance, Area: Automation

#2407 Route refresh on persistent congestion
  src/core/connection.c
  src/core/cubic.c
  src/core/path.c
  src/core/send.c
  src/generated/linux/datapath_raw_socket.c.clog.h
  src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/platform/datapath_raw.c
  src/platform/datapath_raw_socket.c
Labels: Area: Lola

#2421 Fix Stats v2 Query Size
  src/core/connection.c
Labels: Area: Interop, Area: Core

#2422 Add troubles
  docs/TSG.md
Labels: Area: Documentation, external

#2423 Fix/suppress a few more nits
  CMakeLists.txt
  src/core/connection.c
  src/platform/cgroup.c
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/tls_openssl.c
Labels: Area: Build, external

#2399 Split public settings structs
  docs/Settings.md
  scripts/generate-dotnet.ps1
  src/core/configuration.c
  src/core/configuration.h
  src/core/congestion_control.c
  src/core/congestion_control.h
  src/core/connection.c
  src/core/connection.h
  src/core/cubic.c
  src/core/cubic.h
  src/core/library.c
  src/core/library.h
  src/core/precomp.h
  src/core/send.c
  src/core/send.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/cs/tool/Program.cs
  src/generated/linux/congestion_control.c.clog.h
  src/generated/linux/congestion_control.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/lib.rs
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestHelpers.h
  src/tools/interop/interop.cpp
  src/tools/interop/interop.h
  src/tools/interopserver/InteropServer.cpp
  src/tools/interopserver/InteropServer.h
  src/tools/reach/reach.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Core

#2424 Remove legacy compile mode
  docs/Release.md
  src/inc/msquic.h
Labels: Area: Core

#2425 Validate pipeline commit matches resource in vpack publish
  .azure/obtemplates/prepare-vpacks.yml
  scripts/validate-package-commits.ps1
Labels: Area: Automation

#2426 Add quicdev as reviewers to vpack git checkin
  scripts/generate-git-checkin.ps1
Labels: Area: Automation

#2409 Disable Shared EC Tests
  .azure/azure-pipelines.ci.yml
Labels: Area: Testing, Area: Automation

#2431 Use a single PAT for both vpack and git push
  .azure/obtemplates/git-submit.yml
Labels: Area: Automation

#2429 Add tool to generate Vpack PAT
  scripts/generatevpackpat/Program.cs
  scripts/generatevpackpat/generatevpackpat.csproj
Labels: Area: Automation

#2433 Revert "Remove optional reviewers from git checkin (#2427)"
  scripts/generate-git-checkin.ps1
Labels: Area: Automation

#2434 Backport build and C# changes to 2.0 branch
  .azure/obtemplates/git-submit.yml
  scripts/generate-dotnet.ps1
  scripts/generate-git-checkin.ps1
  src/cs/lib/msquic_generated.cs
Labels: Backport

#2435 Remove VN gtest suite
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
Labels: Area: Testing

#2436 Remove VN gtest suite (#2435)
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
Labels: Backport

#2439 Fix PGO directory when running a standalone cmake build
  CMakeLists.txt
Labels: Area: Build

#2438 Fix Rust Build Warnings
  src/lib.rs
Labels: Area: Build, Language: Rust
