Repository microsoft/msquic, pull requests merged in 2022-09, with the labels that each got.

#3037 EADDRNOTAVAIL code is 49 on macos
  src/cs/lib/msquic_generated_macos.cs
Labels: external, Area: API, Language: C#

#3041 Always creating worker threads without affinitization on error.
  src/generated/linux/platform_posix.c.clog.h
  src/generated/linux/platform_posix.c.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/platform/platform_posix.c
Labels: OS: Ubuntu

#3043 Update Patch Version Number
  .azure/obtemplates/push-vpack.yml
  .azure/templates/test-distribution.yml
  CMakeLists.txt
  Cargo.toml
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
Labels: Area: Build

#3046 Update Down Level Tests for v2.1.1
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3045 Add New Release Instructions
  docs/Release.md
Labels: Area: Documentation

#3053 Fix arm32 package naming
  docs/Release.md
  scripts/make-packages.sh
Labels: Area: Automation

#3054 Backport changes for v2.1.2
  CMakeLists.txt
  scripts/build.ps1
  scripts/make-packages.sh
Labels: Area: Core, Backport

#3061 Backport "Fix linux packaging (#2994)" to 2.1.2
  .azure/obtemplates/build-linux-packages.yml
  .azure/obtemplates/build-linux.yml
  scripts/build.ps1
  scripts/make-packages.sh
Labels: Backport

#3065 Use correct length increment for IP_PKTINFO CMsg header
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu, Bug: Platform

#3067 Use correct length increment for msg_controllen (#3065)
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu, Bug: Platform

#3066 Add vcpkg installation instructions
  docs/BUILD.md
Labels: Area: Documentation

#3063 Add test for VN compatibility list generation.
  src/core/unittest/VersionNegExtTest.cpp
Labels: Area: Testing

#3085 Change Test TP to use 4 bytes for Type instead of 2.
  src/inc/msquicp.h
Labels: Area: Testing

#3076 Add tests for invalid-sized version_info transport parameter.
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/crypto_tls.c
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/crypto_tls.c.clog.h
  src/generated/linux/crypto_tls.c.clog.h.lttng.h
  src/inc/msquicp.h
  src/manifest/clog.sidecar
  src/platform/tls_openssl.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
Labels: Bug: Core, Area: Testing

#3091 Update Release.md
  docs/Release.md
Labels: Area: Documentation

#3092 Update Default Windows Ingest Branch
  .azure/OneBranch.Package.yml
Labels: Area: Automation
