Repository microsoft/msquic, pull requests merged in 2023-08, with the labels that each got.

#3786 Add a name to unnamed struct QUIC_HANDLE
  src/core/configuration.h
  src/core/listener.h
  src/core/registration.h
  src/core/stream.h
Labels: Area: Build, external

#3784 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3790 QEO Fixes
  src/core/connection.c
  src/core/crypto.c
  src/core/path.c
  src/core/path.h
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/crypto.c.clog.h
  src/generated/linux/crypto.c.clog.h.lttng.h
  src/generated/linux/path.c.clog.h
  src/generated/linux/path.c.clog.h.lttng.h
  src/tools/spin/spinquic.cpp
Labels: Area: Core

#3791 Fix QEO RX Packet Encrypted Logic
  src/core/connection.c
Labels: Area: Core

#3789 Add Debian 12 package & fix Fedora 37 package
  .azure/OneBranch.Publish.yml
Labels: Area: Automation, Area: Packaging

#3781 Remove QUIC_USE_RAW_DATAPATH macro
  CMakeLists.txt
  src/core/connection.c
  src/core/connection.h
  src/core/cubic.c
  src/core/library.c
  src/core/listener.c
  src/core/path.c
  src/core/send.c
  src/inc/msquicp.h
  src/inc/quic_datapath.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw_linux.c
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_win.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/unittest/DataPathTest.cpp
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/MtuTest.cpp
  src/test/lib/QuicDrill.cpp
  src/test/lib/TestHelpers.h
  src/test/lib/precomp.h
  src/tools/etw/quicetw.h
Labels: Area: Lola

#3797 Update .sscignore to ignore CFS0041 (cargo)
  .sscignore
Labels: Area: Automation

#3798 Regenerate Suppression File
  .azure/openssl.gdnsuppress
  docs/CredScan.md
Labels: Area: Automation

#3799 Fix OneBranch Kernel Tests
  .azure/obtemplates/run-bvt.yml
Labels: Area: Automation

#3796 Update XDP Usage to v1.0
  .azure/azure-pipelines.perf.yml
  scripts/package-nuget.ps1
  scripts/performance.ps1
  scripts/prepare-machine.ps1
  scripts/xdp-devkit.json
  scripts/xdp-install.ps1
  scripts/xdp.json
  src/platform/datapath_raw_xdp_win.c
Labels: Area: Lola

#3801 Split stress test and BVT test
  .github/workflows/build-reuse-darwin-framework.yml
  .github/workflows/build-reuse-unix.yml
  .github/workflows/build-reuse-win.yml
  .github/workflows/build-reuse-winkernel.yml
  .github/workflows/stress.yml
  .github/workflows/test.yml
Labels: Area: Automation

#3802 Configure Codecov to reduce noise
  codecov.yml
Labels: Area: Automation

#3793 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3803 Update Readme Shields
  README.md
Labels: Area: Documentation

#3800 fix kernel build warning
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/MtuTest.cpp
  src/test/lib/precomp.h
Labels: Area: Build

#3778 Reliable Reset Stream Support - Phase 1 - Feature Negotiation
  src/core/connection.c
  src/core/connection.h
  src/core/crypto_tls.c
  src/core/frame.c
  src/core/frame.h
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/FrameTest.cpp
  src/core/unittest/SettingsTest.cpp
  src/core/unittest/SpinFrame.cpp
  src/core/unittest/TransportParamTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/crypto_tls.c.clog.h
  src/generated/linux/crypto_tls.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Protocol Updates, Area: API, Area: Core

#3806 Only do Official Releases in OneBranch
  .azure/obtemplates/build-linux.yml
  .azure/obtemplates/build-winuser-xdp.yml
  .azure/obtemplates/build-winuser.yml
  scripts/build.ps1
Labels: Area: Build, Area: Automation

#3807 Update build-reuse-darwin-framework.yml Permissions
  .github/workflows/build-reuse-darwin-framework.yml
Labels: Area: Automation, Area: Security

#3814 Fix Debug Builds on Windows User Mode
  src/inc/quic_platform_winuser.h
  src/test/bin/quic_gtest.cpp
Labels: Area: Build, Area: Testing

#3808 More Loss and BBR Tests
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Testing

#3815 Enable logs to get the code coverage
  .github/workflows/code-coverage.yml
Labels: Area: Testing, Area: Automation

#3816 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3826 Refactor the RX Datapath Object Abstraction Model
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/datagram.c
  src/core/datagram.h
  src/core/inline.c
  src/core/library.c
  src/core/packet.c
  src/core/packet.h
  src/core/stream.h
  src/core/stream_recv.c
  src/core/worker.c
  src/generated/linux/datapath_winkernel.c.clog.h
  src/generated/linux/datapath_winkernel.c.clog.h.lttng.h
  src/generated/linux/packet.c.clog.h
  src/generated/linux/packet.c.clog.h.lttng.h
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), OS: Ubuntu, OS: macOS, OS: Windows (Kernel), Area: Core

#3827 More Refactoring of the QUIC Layer RX Packets
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/connection.h
  src/core/library.c
  src/core/library.h
  src/core/operation.h
  src/core/packet_space.c
  src/core/packet_space.h
  src/core/path.c
  src/core/path.h
  src/core/quicdef.h
  src/core/worker.c
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
Labels: Area: Core

#3828 Support customizing tool chain file for cross compile
  scripts/build.ps1
Labels: Area: Build, Area: Automation

#3831 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3823 feat: close listeners in registration rundown
  src/core/listener.c
  src/core/listener.h
  src/core/registration.c
  src/core/registration.h
Labels: Area: API, Area: Core
