Repository microsoft/msquic, pull requests merged in 2023-07, with the labels that each got.

#3730 Update docs to reflect what is in msquic.h
  docs/Settings.md
Labels: Area: Documentation

#3735 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3739 Fix Up OneBranch PR Yaml
  .azure/OneBranch.PullRequest.yml
Labels: Area: Automation

#3732 Migrate Windows Prerelease tests to 1ES hosted pool
  .azure/azure-pipelines.ci.yml
  .github/workflows/code-coverage.yml
  .github/workflows/test.yml
  CMakeLists.txt
  docs/AZP.md
  scripts/interop.ps1
  scripts/run-executable.ps1
Labels: github_actions

#3738 Migrate AzP CI to Github
  .azure/azure-pipelines.ci.yml
  .azure/obtemplates/build-linux.yml
  .azure/templates/build-darwin-framework.yml
  .azure/templates/build-distribution.yml
  .azure/templates/build-nuget.yml
  .azure/templates/merge-darwin.yml
  .azure/templates/merge-publish-coverage.yml
  .azure/templates/run-bvt.yml
  .azure/templates/run-dotnet.yml
  .azure/templates/run-quicinterop.yml
  .azure/templates/run-spinquic.yml
  .azure/templates/test-distribution.yml
  .github/workflows/build-darwin-framework.yml
  .github/workflows/build-reuse-darwin-framework.yml
  .github/workflows/build-reuse-unix.yml
  .github/workflows/build-reuse-win.yml
  .github/workflows/build.yml
  .github/workflows/dotnet-test.yml
  .github/workflows/package-linux.yml
  .github/workflows/package-reuse-linux.yml
  scripts/build.ps1
  scripts/package-nuget.ps1
Labels: Area: Automation, github_actions

#3741 Consolidate BVT jobs for different runners
  .github/workflows/code-coverage.yml
  .github/workflows/test.yml
Labels: github_actions

#3744 Delete msquic libs in packgaging test in case they get loaded instead of the ones in the installed package
  .github/workflows/package-linux.yml
Labels: Area: Testing, Area: Packaging

#3628 Refactoring for cross-platform xdp placeholder
  scripts/clog.inputs
  src/core/connection.c
  src/core/connection.h
  src/generated/linux/datapath_raw_linux.c.clog.h
  src/generated/linux/datapath_raw_linux.c.clog.h.lttng.h
  src/generated/linux/datapath_raw_socket.c.clog.h
  src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
  src/generated/linux/datapath_raw_socket_linux.c.clog.h
  src/generated/linux/datapath_raw_socket_win.c.clog.h
  src/generated/linux/datapath_raw_socket_win.c.clog.h.lttng.h
  src/generated/linux/datapath_raw_win.c.clog.h
  src/generated/linux/datapath_raw_win.c.clog.h.lttng.h
  src/generated/linux/datapath_raw_xdp_linux.c.clog.h
  src/generated/linux/datapath_raw_xdp_win.c.clog.h
  src/generated/linux/datapath_raw_xdp_win.c.clog.h.lttng.h
  src/generated/linux/quic.clog_datapath_raw_linux.c.clog.h.c
  src/generated/linux/quic.clog_datapath_raw_socket_linux.c.clog.h.c
  src/generated/linux/quic.clog_datapath_raw_socket_win.c.clog.h.c
  src/generated/linux/quic.clog_datapath_raw_win.c.clog.h.c
  src/generated/linux/quic.clog_datapath_raw_xdp_linux.c.clog.h.c
  src/generated/linux/quic.clog_datapath_raw_xdp_win.c.clog.h.c
  src/inc/quic_platform_posix.h
  src/platform/CMakeLists.txt
  src/platform/datapath_raw.h
  src/platform/datapath_raw_linux.c
  src/platform/datapath_raw_linux.h
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_socket_linux.c
  src/platform/datapath_raw_socket_win.c
  src/platform/datapath_raw_win.c
  src/platform/datapath_raw_win.h
  src/platform/datapath_raw_xdp.h
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
Labels: OS: Windows (User), OS: Ubuntu, Area: Lola

#3747 Pin ubuntu docker base image hash
  .docker/ubuntu-20.04/Dockerfile
  .docker/ubuntu-22.04/Dockerfile
Labels: Area: Build

#3751 Use codecov.io for code coverage
  .github/workflows/code-coverage.yml
  README.md
Labels: Area: Testing

#3752 Minor badge fixes
  README.md
Labels: Area: Documentation

#3756 Minor fixes for Github workflows
  .github/workflows/build-reuse-darwin-framework.yml
  .github/workflows/build-reuse-unix.yml
  .github/workflows/build-reuse-win.yml
  .github/workflows/build-reuse-winkernel.yml
  .github/workflows/build.yml
  .github/workflows/dotnet-test.yml
  .github/workflows/test-down-level.yml
  .github/workflows/test.yml
  scripts/prepare-machine.ps1
Labels: Area: Testing, Area: Automation

#3750 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3757 Minor Changes to Improve Listener Code Coverage
  src/core/listener.c
Labels: Area: Core

#3755 Support retrieving the initial destination CID from GetParam
  docs/Settings.md
  src/core/connection.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/test/lib/ApiTest.cpp
Labels: Area: API, Area: Core

#3760 Container based build workflow for Linux
  .azure/obtemplates/build-linux-packages.yml
  .azure/obtemplates/build-linux.yml
  .azure/obtemplates/build-winuser-xdp.yml
  .devcontainer/devcontainer.json
  .devcontainer/developer/devcontainer.json
  .github/workflows/build-reuse-unix.yml
  scripts/prepare-machine.ps1
Labels: github_actions

#3761 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3763 Move VPack to OneBranch
  .azure/OneBranch.Package.yml
  .azure/obtemplates/git-submit.yml
  .azure/obtemplates/prepare-vpacks.yml
  .azure/obtemplates/push-vpack.yml
  scripts/generate-git-checkin.ps1
  scripts/update-version.ps1
Labels: Area: Automation

#3618 Connection UDP Receive Event
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
  src/plugins/trace/dll/DataModel/LTTng/QuicLTTngEvent.cs
  src/plugins/trace/dll/DataModel/QuicConnection.cs
  src/plugins/trace/dll/DataModel/QuicData.cs
  src/plugins/trace/dll/DataModel/QuicEvent.cs
  src/plugins/trace/dll/DataModel/QuicEvents.cs
  src/plugins/trace/dll/Tables/QuicNetworkTable.cs
Labels: Area: Performance, Area: Logging

#3764 CP 2.1: Move VPack to OneBranch (#3763)
  .azure/OneBranch.Package.yml
  .azure/obtemplates/git-submit.yml
  .azure/obtemplates/prepare-vpacks.yml
  .azure/obtemplates/push-vpack.yml
  scripts/generate-git-checkin.ps1
  scripts/update-version.ps1
Labels: Area: Automation

#3765 CP 2.2: Move VPack to OneBranch (#3763)
  .azure/OneBranch.Package.yml
  .azure/obtemplates/git-submit.yml
  .azure/obtemplates/prepare-vpacks.yml
  .azure/obtemplates/push-vpack.yml
  scripts/generate-git-checkin.ps1
  scripts/update-version.ps1
Labels: Area: Automation

#3770 Dynamically load/unload xdp dll
  src/platform/CMakeLists.txt
  src/platform/datapath_raw_xdp_win.c
Labels: Area: Lola

#3769 Improve C++ wrapper.
  src/inc/msquic.hpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
Labels: Area: API

#3758 Add QUIC_SETTINGS Support to SpinQuic
  src/core/settings.c
  src/tools/spin/spinquic.cpp
Labels: Bug: Core, Area: Testing, Area: Stress

#3777 Use UDP Length for XDP RX
  src/platform/datapath_raw_socket.c
Labels: Area: Lola

#3773 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3779 Consume XDP v0.17.0
  scripts/prepare-machine.ps1
  scripts/xdp-devkit.json
  scripts/xdp-install.ps1
  src/platform/datapath_raw_xdp_win.c
Labels: dependencies
