Repository microsoft/msquic, pull requests merged in 2023-05, with the labels that each got.

#3599 Automatic linux package publish pipeline Part 1
  .azure/OneBranch.Publish.yml
  .azure/obtemplates/build-linux-packages.yml
  .azure/obtemplates/upload-linux-package.yml
Labels: Area: Build, Area: Automation

#3601 Automatic linux package publish pipeline Part 2
  .azure/OneBranch.Publish.yml
  .azure/dockers/ob/pkg-publish/publish-packages.sh
  .azure/obtemplates/upload-linux-package.yml
  scripts/upload-linux-packages.sh
Labels: Area: Build, Area: Automation

#3600 Initial Datapath QEO Interface
  src/inc/quic_datapath.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/unittest/DataPathTest.cpp
Labels: Area: Performance

#3602 Fix OneBranch Publishing YAML
  .azure/OneBranch.Publish.yml
Labels: Area: Automation, Area: Packaging

#3603 Turn on automated publishing
  .azure/OneBranch.Publish.yml
Labels: Area: Build, Area: Automation

#3605 Backport publishing related changes to 2.2
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/OneBranch.Publish.yml
  .azure/OneBranch.PullRequest.yml
  .azure/dockers/ob/linux-20.04/Dockerfile
  .azure/dockers/ob/linux-20.04/arm-cross-compile-sources.list
  .azure/dockers/ob/linux-22.04/Dockerfile
  .azure/dockers/ob/linux-22.04/arm-cross-compile-sources.list
  .azure/dockers/ob/pkg-publish/Dockerfile
  .azure/dockers/ob/pkg-publish/publish-packages.sh
  .azure/dockers/ob/windows/Dockerfile
  .azure/dockers/ob/windows/install-ewdk.ps1
  .azure/dockers/ob/windows/install-tools.ps1
  .azure/dockers/ob/windows/install-workloads.ps1
  .azure/dockers/ob/windows/msquic.vsconfig
  .azure/obtemplates/build-distribution.yml
  .azure/obtemplates/build-linux-packages.yml
  .azure/obtemplates/build-linux.yml
  .azure/templates/build-distribution.yml
  .github/workflows/docker-publish-xcomp.yml
  scripts/onebranch-build-kernel.cmd
  scripts/package-distribution.ps1
  scripts/upload-linux-packages.sh
Labels: Area: Build, Area: Automation, Backport, Area: Packaging

#3608 Apply tag filtering at stage level in publishing pipeline
  .azure/OneBranch.Publish.yml
Labels: Area: Automation, Area: Packaging

#3606 Use vse2022:latest to avoid onebranch warnings
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/windows/Dockerfile
Labels: Area: Build, Area: Automation

#3611 Scheduled windows docker update pipeline
  .azure/OneBranch.Docker.Official.yml
Labels: Area: Build, Area: Automation

#3617 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3620 Fix locating numa.h
  CMakeLists.txt
Labels: Area: Build, Area: Automation

#3621 CP Fix locating numa.h
  CMakeLists.txt
Labels: Area: Build, Area: Automation

#3623 Backport "Use vse2022:latest to avoid onebranch warnings" to 2.2
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/windows/Dockerfile
Labels: Backport, Area: Packaging

#3624 Prevent Path Removal Underflow
  src/core/path.c
  src/core/path.h
Labels: Area: Core

#3627 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3632 Plumb QEO to XDP
  src/platform/datapath_raw.c
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp.c
Labels: Area: Lola

#3637 Shutdown Stream on Send/Start Failure
  src/core/api.c
  src/core/binding.c
  src/core/connection.c
  src/core/operation.h
  src/core/registration.c
  src/core/stream_send.c
Labels: Bug: Core

#3641 Build Processor Info for Max Processors
  src/generated/linux/platform_winuser.c.clog.h
  src/generated/linux/platform_winuser.c.clog.h.lttng.h
  src/platform/platform_winuser.c
Labels: OS: Windows (User), Bug: Platform

#3652 Use PMC v4 API for publishing packages
  .azure/OneBranch.Publish.yml
  .azure/dockers/ob/pkg-publish/Dockerfile
  .azure/dockers/ob/pkg-publish/publish-packages.sh
  scripts/upload-linux-packages.sh
Labels: Area: Packaging

#3654 Revert "pmc v4 (#3652)"
  .azure/OneBranch.Publish.yml
  .azure/dockers/ob/pkg-publish/Dockerfile
  .azure/dockers/ob/pkg-publish/publish-packages.sh
  scripts/upload-linux-packages.sh
Labels: Area: Packaging

#3660 Correctly handle XdpOpenAPi failure
  src/platform/datapath_raw_xdp.c
Labels: Area: Lola

#3658 Current Partition instead of Current Processor
  src/core/binding.c
  src/core/connection.c
  src/core/inline.c
  src/core/library.c
  src/core/library.h
  src/core/packet_builder.c
  src/core/packet_space.c
Labels: Area: Core

#3661 Load from System32 on Windows for msquic.dll
  src/bin/CMakeLists.txt
Labels: Area: Build, OS: Windows (User)
