Repository microsoft/msquic, pull requests merged in 2023-10, with the labels that each got.

#3542 Use Latest Interop Runner Docker Image
  scripts/qns.Dockerfile
  scripts/run_endpoint.sh
Labels: Area: Testing, Area: Interop, Area: Automation

#3890 Avoid using unknown #pragma for non-MSVC compiler in public header files.
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/msquic_posix.h
Labels: Area: Build, external

#3887 Add Missing Header Guards
  src/platform/datapath_raw.h
  src/platform/datapath_raw_linux.h
Labels: Area: Build, Area: Automation

#3889 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
Labels: Area: Performance, Area: Automation

#3904 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
Labels: Area: Performance, Area: Automation

#3905 Move Stream Send Reference
  src/core/api.c
Labels: Bug: Core, Area: API

#3900 Handle bad behavior by app in reliable shutdown path.
  src/core/stream_send.c
  src/generated/linux/stream_send.c.clog.h
  src/generated/linux/stream_send.c.clog.h.lttng.h
  src/test/lib/DataTest.cpp
Labels: Bug: Core

#3908 Point Down Level Tests to Latest Releases
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3912 Fix QUIC_TRACE <--> map_QUIC_TRACE in ETW
  src/inc/quic_trace.h
  src/manifest/MsQuicEtw.man
Labels: Area: Logging

#3913 Drill test failure triage
  src/platform/datapath_raw_xdp_win.c
  src/test/lib/QuicDrill.cpp
Labels: Area: Testing, Bug: Test/Tool

#3893 Remove unnecessary logging, be more careful which SEND flags we clear.
  README.md
  src/core/send.h
  src/core/stream.h
  src/core/stream_send.c
  src/generated/linux/stream_send.c.clog.h
  src/generated/linux/stream_send.c.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/test/lib/DataTest.cpp
Labels: Bug: Core

#3916 Add note for default ubuntu dotnet issue
  docs/Diagnostics.md
  scripts/log_wrapper.sh
Labels: Area: Documentation

#3919 datapath_epoll: adjust CXPLAT_MAX_IO_BATCH_SIZE arithmetic
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu, external, Area: Performance

#3922 Add Debian 12 package & fix Fedora 37 package (#3789)
  .azure/OneBranch.Publish.yml
Labels: Area: Automation, Area: Packaging

#3928 Do not hardcode Android version
  scripts/build.ps1
Labels: Area: Build, Area: Automation, OS: Android

#3929 fix build with OpenSSL 3.1
  submodules/CMakeLists.txt
Labels: Area: Build

#3932 Turn off optimizations for functional tests for arm64
  src/test/lib/precomp.h
Labels: Area: Testing

#3933 Better Delayed ACK Support
  src/core/ack_tracker.c
  src/core/connection.c
  src/core/connection.h
  src/core/inline.c
  src/core/send.c
Labels: Area: Performance, Area: API, Area: Core

#3931 Streams Hold References on Connections
  src/core/connection.c
  src/core/connection.h
  src/core/stream.c
Labels: Area: Core

#3937 Run Recv Fuzzing in Code Coverage
  .github/workflows/code-coverage.yml
Labels: Area: Testing, Area: Stress, Area: Automation

#3940 Fix epoll TCP implementation
  src/platform/datapath_epoll.c
  src/platform/platform_internal.h
Labels: OS: Ubuntu, Area: Performance

#3941 Don't Affinitize Platform Worker
  src/platform/platform_worker.c
Labels: Area: Performance

#3947 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
Labels: Area: Performance, Area: Automation

#3942 New Way of Fuzzing Packet
  .github/workflows/stress.yml
  src/tools/recvfuzz/recvfuzz.cpp
Labels: Area: Stress

#3948 Support setting flow control limits for individual stream types
  docs/Settings.md
  docs/api/QUIC_SETTINGS.md
  src/core/connection.c
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/stream.c
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/clog.sidecar
Labels: Area: API, Area: Core
