Repository microsoft/msquic, pull requests merged in 2023-06, with the labels that each got.

#3666 doc: clarify BufferCount in QUIC_STREAM_EVENT_RECEIVE
  docs/Streams.md
Labels: Area: Documentation

#3667 Additional Testing for Stream Close in Spinquic
  src/core/connection.c
  src/core/stream.c
  src/core/stream.h
  src/core/stream_set.c
  src/plugins/dbg/quictypes.h
  src/tools/spin/spinquic.cpp
Labels: Area: Testing, Area: Stress, Area: Core

#3670 Update Linux Packages to Depend on libnuma
  scripts/make-packages.sh
Labels: OS: Ubuntu, Area: Packaging

#3674 Migrate to PMC v4 for publishing
  .azure/OneBranch.Publish.yml
  .azure/dockers/ob/pkg-publish/Dockerfile
  .azure/dockers/ob/pkg-publish/publish-packages.sh
  scripts/upload-linux-packages.sh
Labels: Area: Packaging

#3677 v2.2.2 version bump
  .azure/obtemplates/push-vpack.yml
  .azure/templates/test-distribution.yml
  CMakeLists.txt
  Cargo.toml
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
Labels: Area: Packaging

#3678 Backport "Migrate to PMC v4 for publishing (#3674)" to 2.2
  .azure/OneBranch.Publish.yml
  .azure/dockers/ob/pkg-publish/Dockerfile
  .azure/dockers/ob/pkg-publish/publish-packages.sh
  scripts/upload-linux-packages.sh
Labels: Area: Packaging

#3682 Backport some changes to 2.2.2
  .github/workflows/cargo.yml
  .github/workflows/docker-publish.yml
  .github/workflows/test-down-level.yml
  scripts/make-packages.sh
  src/bin/CMakeLists.txt
  src/core/binding.c
  src/core/connection.c
  src/core/inline.c
  src/core/library.c
  src/core/library.h
  src/core/packet_builder.c
  src/core/packet_space.c
  src/core/stream.c
  src/core/stream.h
  src/core/stream_set.c
  src/platform/datapath_raw_xdp.c
  src/platform/tls_schannel.c
  src/plugins/dbg/quictypes.h
  src/tools/spin/spinquic.cpp
Labels: Backport

#3665 Support Delaying Stream ID FC Updates to StreamClose
  docs/api/QUIC_CONNECTION_EVENT.md
  docs/api/StreamOpen.md
  src/core/api.c
  src/core/stream.c
  src/core/stream.h
  src/core/stream_set.c
  src/cs/lib/msquic_generated.cs
  src/generated/linux/stream.c.clog.h
  src/generated/linux/stream.c.clog.h.lttng.h
  src/generated/linux/stream_set.c.clog.h
  src/generated/linux/stream_set.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/clog.sidecar
  src/plugins/dbg/quictypes.h
  src/tools/spin/spinquic.cpp
Labels: Area: API, Area: Core

#3686 Publish pipeline manual mode
  .azure/OneBranch.Publish.yml
Labels: Area: Packaging

#3693 Fix UDPv6 checksum
  src/platform/datapath_raw_socket.c
Labels: Area: Lola

#3694 Fix worker event handle leak in MsQuic!RegistrationClose
  src/core/worker.c
Labels: Area: Core

#3696 Test sign drivers for perf tests
  .azure/templates/build-config-winkernel.yml
  scripts/prepare-machine.ps1
  scripts/sign.ps1
Labels: Area: Build, Area: Automation

#3695 Connections Size, Not Count
  src/platform/datapath_raw_xdp.c
Labels: Bug: Platform

#3699 Onboard Kernel Tests to GitHub (w/ Signing Fixes)
  .azure/templates/build-config-winkernel.yml
  .github/workflows/bvt.yml
  scripts/prepare-machine.ps1
  scripts/run-gtest.ps1
  scripts/sign.ps1
  src/bin/winkernel/msquic.kernel.vcxproj
  src/bin/winkernel/msquicpriv.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/manifest/manifest.kernel.vcxproj
  src/perf/bin/secnetperfdriver.kernel.vcxproj
  src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
  src/perf/lib/perflib.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
  src/test/lib/testlib.kernel.vcxproj
Labels: Area: Build, Area: Automation

#3592 Update Polling Idle Timeout Dynamically
  src/core/library.c
  src/generated/linux/library.c.clog.h
  src/generated/linux/library.c.clog.h.lttng.h
  src/inc/quic_datapath.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/test/lib/ApiTest.cpp
Labels: Area: API, Area: Core, Area: Lola

#3705 Split QuicTestConnectionParam to Reduce Stack Usage
  src/test/lib/ApiTest.cpp
Labels: Area: Build, Area: Testing

#3709 Sign Drivers for OneBranch Testing
  .azure/obtemplates/run-bvt.yml
Labels: Area: Testing

#3719 Correctly sign CBL mariner packages and publish them
  .azure/OneBranch.Publish.yml
  .azure/obtemplates/build-linux-packages.yml
Labels: Area: Packaging

#3724 Fix some minor issues in linux build dockers
  .azure/OneBranch.Docker.Official.yml
  .docker/linux-20.04/Dockerfile
  .docker/linux-20.04/arm-cross-compile-sources.list
  .docker/linux-22.04/Dockerfile
  .docker/linux-22.04/arm-cross-compile-sources.list
  .docker/windows/Dockerfile
  .docker/windows/install-tools.ps1
  .docker/windows/install-workloads.ps1
  .docker/windows/install.cmd
  .docker/windows/msquic.vsconfig
  .docker/windows/win-installer-helper.psm1
  .github/workflows/docker-publish-xcomp.yml
Labels: Area: Build

#3726 Fix ownership issue in dockers
  .docker/ubuntu-20.04/Dockerfile
  .docker/ubuntu-20.04/arm-cross-compile-sources.list
  .docker/ubuntu-22.04/Dockerfile
  .docker/ubuntu-22.04/arm-cross-compile-sources.list
  .github/workflows/docker-publish-xcomp.yml
Labels: Area: Build

#3725 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3720 Resue build workflows
  .github/workflows/build-reuse-unix.yml
  .github/workflows/build-reuse-win.yml
  .github/workflows/build-reuse-winkernel.yml
  .github/workflows/build.yml
  .github/workflows/bvt.yml
  .github/workflows/stress.yml
  .github/workflows/test.yml
Labels: Area: Build

#3731 Fix skipped linux tests
  .github/workflows/test.yml
  scripts/prepare-machine.ps1
Labels: Area: Testing
