Repository microsoft/msquic, pull requests merged in 2023-03, with the labels that each got.

#3462 Ingest XDP v0.16.7 and use TCP CIBIR rules when needed
  .github/workflows/build.yml
  .github/workflows/bvt.yml
  .github/workflows/stress.yml
  .github/workflows/test-down-level.yml
  scripts/run-gtest.ps1
  scripts/test.ps1
  scripts/xdp-devkit.json
  src/generated/linux/datapath_raw_socket.c.clog.h
  src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_xdp.c
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/MtuTest.cpp
Labels: Area: Lola

#3476 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3480 Ported fix for MacOS status codes dotnet
  src/cs/lib/msquic.cs
Labels: Area: Build, OS: macOS, Language: C#

#3479 Improve Send Cleanup Path to Fix Benign Assert
  src/core/send.c
  src/core/send.h
Labels: Area: Core

#3486 Nibanks/stop openssl3 build warnings
  scripts/build.ps1
Labels: Area: Build, OS: Windows (User), TLS: OpenSSL

#3481 get client random if setting TlsSecrets on server
  src/platform/tls_openssl.c
Labels: TLS: OpenSSL

#3487 Fix Remote Addr Tests Down Level (v2.1)
  src/test/lib/ApiTest.cpp
Labels: Area: Testing, Bug: Test/Tool

#3490 Fix OneBranch Images on release/2.1
  .azure/OneBranch.Official.yml
Labels: Area: Build, Area: Automation

#3489 Windows Sockets Abstraction Improvements
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), Bug: Platform

#3501 Document how to build and use clog2text and lttng
  docs/Diagnostics.md
Labels: Area: Documentation

#3500 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3507 Fix 2 Valgrind warnings
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu

#3506 Update credscan suppression for openssl3 submodule.
  .azure/CredScanSuppressions.json
  .azure/openssl.gdnsuppress
Labels: Area: Build, Area: Automation, Area: Security

#3505 Fix Zero-byte Test Allocation
  src/core/unittest/TransportParamTest.cpp
  src/platform/platform_posix.c
  src/platform/platform_winuser.c
  src/platform/unittest/TlsTest.cpp
  src/test/lib/TestHelpers.h
Labels: Area: Testing, Bug: Test/Tool

#3508 Add Readme File to Nuget
  README.md
  scripts/package-nuget.ps1
  src/distribution/Microsoft.Native.Quic.MsQuic.OpenSSL.nuspec
  src/distribution/Microsoft.Native.Quic.MsQuic.Schannel.nuspec
  src/distribution/Microsoft.Native.Quic.MsQuic.UWP.OpenSSL.nuspec
  src/distribution/Microsoft.Native.Quic.MsQuic.XDP.Schannel.nuspec
Labels: Area: Documentation

#3512 Full Logging for BVTs
  .github/workflows/bvt.yml
Labels: Area: Testing, Area: Logging

#3492 [release/2.1] make chacha optional on Linux
  CMakeLists.txt
  src/generated/linux/tls_openssl.c.clog.h
  src/generated/linux/tls_openssl.c.clog.h.lttng.h
  src/inc/quic_crypt.h
  src/platform/crypt_bcrypt.c
  src/platform/crypt_openssl.c
  src/platform/platform_posix.c
  src/platform/tls_openssl.c
  src/platform/unittest/TlsTest.cpp
Labels: Backport

#3514 Use the new service connection for ACR
  .azure/OneBranch.Publish.yml
Labels: Area: Automation

#3522 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3515 Fix and Clean up Windows Socket Delete Code Paths
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), Bug: Platform

#3526 Update Down Level Test to 2.1.8
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3527 Add Test Timeouts
  scripts/run-gtest.ps1
  src/test/bin/quic_gtest.cpp
Labels: Area: Testing

#3537 Update LTTng to Latest (v2.13)
  .azure/dockers/ob/linux/Dockerfile
  .azure/templates/test-distribution.yml
  .github/workflows/codeql-analysis.yml
  docs/BUILD.md
  docs/Diagnostics.md
  scripts/log.ps1
  scripts/prepare-machine.ps1
Labels: OS: Ubuntu, Area: Logging
