Repository microsoft/msquic, pull requests merged in 2023-04, with the labels that each got.

#3545 Handle sending path challenge on paths that have not resolved route yet
  src/core/send.c
Labels: Area: Core, Area: Lola

#3539 Fix QUIC_TLS_SECRETS on Server and Client.
  src/core/crypto.c
  src/core/crypto.h
  src/core/crypto_tls.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/test/lib/DataTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/TestHelpers.h
Labels: Bug: Core

#3549 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3551 Update README for microsoft/msquic repository
  README.md
Labels: Area: Documentation, external

#3552 Add instructions for testing on a different machine
  docs/TEST.md
Labels: Area: Documentation

#3556 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3558 Fix instructions for installing perl
  docs/BUILD.md
Labels: Area: Documentation

#3559 Perf Counters can be non-zero on Release Tests
  src/test/lib/ApiTest.cpp
Labels: Bug: Test/Tool

#3560 Perf counters can be non-zero on release part 2
  src/test/lib/ApiTest.cpp
Labels: Area: Testing, OS: Windows (Kernel), Bug: Test/Tool

#3563 More Datagram Test Fixes
  src/platform/datapath_raw_socket.c
  src/test/lib/DatagramTest.cpp
Labels: Area: Testing

#3568 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.openssl3.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3570 Build Microsoft.Native.Quic.MsQuic.XDP.OpenSSL nuget package
  .azure/OneBranch.Official.yml
  .azure/obtemplates/build-nuget.yml
  .azure/templates/build-nuget.yml
  src/distribution/Microsoft.Native.Quic.MsQuic.XDP.OpenSSL.nuspec
  src/distribution/Microsoft.Native.Quic.MsQuic.XDP.OpenSSL.targets
Labels: Area: Automation, Area: Lola, Area: Packaging

#3571 Release 2.2 Notes
  docs/Platforms.md
  docs/Release.md
Labels: Area: Documentation

#3572 Update main to 2.3
  .azure/obtemplates/push-vpack.yml
  .azure/templates/test-distribution.yml
  CMakeLists.txt
  Cargo.toml
  scripts/package-distribution.ps1
  scripts/package-nuget.ps1
  scripts/write-versions.ps1
  src/distribution/Info.plist
  src/inc/msquic.ver
Labels: Area: Core

#3574 Fix QTIP tests in release branch
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/MtuTest.cpp
Labels: Area: Lola

#3582 v2.2 Down Level Test Support
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3584 Update issue template for bugs for v2.2
  .github/ISSUE_TEMPLATE/bug_report.yaml
  docs/Release.md
Labels: Area: Documentation

#3583 Add OpenSSL v3 Distribution
  .azure/OneBranch.Official.yml
  .azure/obtemplates/build-distribution.yml
  .azure/templates/build-distribution.yml
Labels: Area: Build, Area: Automation, Area: Packaging

#3585 Publish all linux packages for a particular release tag all at once
  .azure/OneBranch.Publish.yml
Labels: Area: Automation

#3586 docs: Replace NEW_STREAM with PEER_STREAM_STARTED
  docs/API.md
Labels: Area: Documentation, external

#3588 Check in the linux package publish docker
  .azure/dockers/ob/pkg-publish/Dockerfile
  .azure/dockers/ob/pkg-publish/publish-packages.sh
Labels: Area: Build, OS: Ubuntu, Area: Automation, Area: Packaging

#3589 Use Ubuntu 22.04 based docker for buidling msquic+openssl3 in OB pipeline
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/linux-20.04/Dockerfile
  .azure/dockers/ob/linux-20.04/arm-cross-compile-sources.list
  .azure/dockers/ob/linux-22.04/Dockerfile
  .azure/dockers/ob/linux-22.04/arm-cross-compile-sources.list
  .azure/obtemplates/build-linux.yml
Labels: Area: Build, Area: Automation, Area: Packaging

#3591 Build and push linux build dockers in automation
  .azure/dockers/ob/linux-20.04/Dockerfile
  .azure/dockers/ob/linux-22.04/Dockerfile
  .github/workflows/docker-publish-xcomp.yml
Labels: Area: Build, Area: Automation, github_actions

#3593 Generate Ubuntu 22.04 Packages (using OpenSSL v3)
  .azure/OneBranch.PullRequest.yml
  .azure/obtemplates/build-linux-packages.yml
  scripts/package-distribution.ps1
Labels: Area: Build, OS: Ubuntu, Area: Automation, Area: Packaging

#3595 Use vse2022:vnext in Onebranch pipeline
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/windows/Dockerfile
  .azure/dockers/ob/windows/install-ewdk.ps1
  .azure/dockers/ob/windows/install-tools.ps1
  .azure/dockers/ob/windows/install-workloads.ps1
  .azure/dockers/ob/windows/msquic.vsconfig
  scripts/onebranch-build-kernel.cmd
Labels: Area: Build, Area: Automation
