Repository microsoft/msquic, pull requests merged in 2023-12, with the labels that each got.

#3977 Use American English Spelling of 'acknowledgment'
  docs/Streams.md
  docs/api/QUIC_CONNECTION_EVENT.md
  docs/api/StreamShutdown.md
  src/core/ack_tracker.c
  src/core/bbr.h
  src/core/connection.h
  src/core/loss_detection.c
  src/core/quicdef.h
  src/core/send.c
  src/core/transport_params.h
  src/plugins/dbg/quictypes.h
Labels: Area: Documentation

#3983 fix(perf): RpsClient SIGBUS on aarch64
  src/perf/lib/RpsClient.h
Labels: OS: Ubuntu

#3982 Fix Internal Build Referencing Preview Features
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/EventTest.cpp
Labels: Area: Build, Area: Automation

#3985 Add documentation for getting started with the sample server-client app
  README.md
  docs/Sample.md
Labels: Area: Documentation

#3991 Light up Windows Kernel + DuoNic testing
  scripts/run-gtest.ps1
  scripts/test.ps1
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
Labels: Area: Testing

#3992 Fix Original Destination CID Query
  src/core/connection.c
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
Labels: Bug: Core, Area: Testing, Area: Core

#4003 Fix compiler warning about loss of data in stdout logging
  src/generated/stdout/quic_trace.c
Labels: Area: Build, external, Area: Logging

#4006 Fix cross-compile docker image building
  .docker/ubuntu-20.04/Dockerfile
  .docker/ubuntu-20.04/arm-cross-compile-sources.list
  .docker/ubuntu-22.04/Dockerfile
  .docker/ubuntu-22.04/arm-cross-compile-sources.list
Labels: Area: Build, OS: Ubuntu

#4009 Refactor Processor Count Usage
  src/core/library.c
  src/core/unittest/SettingsTest.cpp
  src/generated/linux/platform_winuser.c.clog.h
  src/generated/linux/platform_winuser.c.clog.h.lttng.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/perf/lib/PerfClient.cpp
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.cpp
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/platform_posix.c
  src/platform/platform_winkernel.c
  src/platform/platform_winuser.c
  src/platform/platform_worker.c
  src/platform/unittest/TlsTest.cpp
  src/test/lib/ApiTest.cpp
  src/tools/attack/attack.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Performance, Area: Core

#4017 Add 'attacking rate' option to the attacking tool.
  src/tools/attack/attack.cpp
Labels: Area: Performance

#4020 Add New Receive Buffer Unit Tests
  scripts/clog.inputs
  src/core/recv_buffer.h
  src/core/unittest/CMakeLists.txt
  src/core/unittest/RecvBufferTest.cpp
  src/generated/linux/RecvBufferTest.cpp.clog.h
  src/generated/linux/quic.clog_RecvBufferTest.cpp.clog.h.c
Labels: Area: Testing

#4032 Simplify timer operations
  src/core/connection.c
  src/core/connection.h
  src/core/inline.c
  src/core/timer_wheel.c
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
Labels: Area: Core

#4030 Compile static library may failed by linking dl.a
  src/bin/CMakeLists.txt
Labels: Area: Build, external
