Repository microsoft/msquic, pull requests merged in 2023-01, with the labels that each got.

#3317 Detail steps for fuzzing debug
  src/fuzzing/README.md
Labels: Area: Documentation

#3318 new API for async certificate validation
  docs/api/ConnectionCertificateValidationComplete.md
  src/core/api.c
  src/core/api.h
  src/core/connection.c
  src/core/library.c
  src/core/operation.h
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/quic_trace.h
  src/lib.rs
  src/plugins/dbg/quictypes.h
  src/test/lib/TestConnection.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Documentation, Area: API, Language: C#, Language: Rust

#3321 remove Handshake state check
  docs/Settings.md
  src/core/api.c
Labels: Bug: Core

#3325 Address onebranch pipeline warnings
  .azure/OneBranch.Official.yml
  .azure/OneBranch.PullRequest.yml
Labels: Area: Build

#3322 Don't invoke CancelIo in CxPlatSocketContextUninitialize
  src/platform/datapath_winuser.c
Labels: OS: Windows (User), Area: Performance

#3323 check for Winsock unreachable error codes in addition to Win32
  src/platform/datapath_winuser.c
Labels: OS: Windows (User)

#3246 HyStart++ for MsQuic
  src/core/cubic.c
  src/core/cubic.h
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/cubic.c.clog.h
  src/generated/linux/cubic.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
Labels: Area: Core

#3342 Fall back to WinDbg if WinDbgX is not installed
  scripts/run-executable.ps1
  scripts/run-gtest.ps1
Labels: Area: Testing

#3340 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3344 Adds Hashtable Restructuring
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
  src/inc/quic_hashtable.h
  src/platform/hashtable.c
Labels: Area: Performance

#3343 gamecore_console: default to latest Windows SDK
  CMakeLists.txt
  scripts/build.ps1
  src/platform/platform_winuser.c
Labels: Area: Build

#3324 Update Quic VNE and Version 2 constants.
  src/core/crypto_tls.c
  src/core/frame.h
  src/core/packet.c
  src/inc/quic_versions.h
  src/plugins/trace/dll/DataModel/QuicEvents.cs
  src/test/lib/HandshakeTest.cpp
Labels: Area: Protocol Updates, Area: Core

#3348 gamecore_console: fix build with 10.0.20348.0
  CMakeLists.txt
  src/platform/tls_schannel.c
Labels: Area: Build

#3331 Fix QUIC_SETTINGS param validation tests.
  src/test/lib/ApiTest.cpp
  src/test/lib/TestHelpers.h
Labels: Area: Testing

#3306 Don't Use v4 Local Addr CMsg
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu

#3359 Fix credscan warnings
  .azure/CredScanSuppressions.json
  .azure/OneBranch.Official.yml
Labels: Area: Build

#3360 build: fix onebranch pipelines
  .azure/OneBranch.Docker.Official.yml
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/windows/Dockerfile
  .azure/dockers/ob/windows/install-workloads.ps1
  .azure/dockers/ob/windows/vsconfig.2019
  CMakeLists.txt
Labels: Area: Build

#3366 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3368 Consume XDP v0.16.5
  scripts/xdp-devkit.json
  src/platform/datapath_raw_xdp.c
Labels: Area: Lola

#3372 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3369 Add CMake Presets file.
  CMakePresets.json
Labels: Area: Build

#3377 Update Down Level Tests for v2.1.7
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#3378 Update some packages in linux build docker image
  .azure/OneBranch.Official.yml
  .azure/dockers/ob/linux/Dockerfile
  .github/workflows/cross-compile.yml
Labels: Area: Build

#3385 [Automated] Update PGO
  src/bin/winuser/pgo_x64/msquic.openssl.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.pgd
  src/bin/winuser/pgo_x64/msquic.schannel.xdp.pgd
Labels: Area: Performance, Area: Automation

#3386 Remove Hard Coded Alias and WI from Ingest PR
  scripts/generate-git-checkin.ps1
Labels: Area: Automation

#3380 Work Around Missing NUMA Node Info
  src/generated/linux/platform_winuser.c.clog.h
  src/generated/linux/platform_winuser.c.clog.h.lttng.h
  src/inc/quic_platform_winuser.h
  src/manifest/clog.sidecar
  src/platform/datapath_winuser.c
  src/platform/platform_winuser.c
Labels: OS: Windows (User), Bug: Platform
