Repository microsoft/msquic, pull requests merged in 2024-08, with the labels that each got.

#4386 Add Priority Connection Queue to Worker
  src/core/connection.c
  src/core/connection.h
  src/core/operation.h
  src/core/worker.c
  src/core/worker.h
  src/plugins/dbg/connection.cpp
  src/plugins/dbg/quictypes.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
  src/tools/spin/spinquic.cpp
Labels: Area: Performance, Area: Core

#4429 Fix Artifact Upload for Recv Fuzzing Tests
  .github/workflows/stress.yml
Labels: Area: Automation

#4182 Multiple Receive API Support
  docs/Settings.md
  docs/Streams.md
  docs/api/QUIC_SETTINGS.md
  docs/api/StreamReceiveComplete.md
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/stream.c
  src/core/stream.h
  src/core/stream_recv.c
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/manifest/clog.sidecar
  src/perf/lib/PerfClient.cpp
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
  src/tools/forwarder/forwarder.cpp
Labels: Area: API, Area: Core

#4430 Add instructions for publishing Linux packages
  docs/Release.md
Labels: Area: Documentation, Area: Packaging

#4458 Add option to configure TCP execution context
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/SecNetPerf.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
Labels: Area: Performance

#4460 set include_dest value
  src/bin/CMakeLists.txt
Labels: Area: Build, external

#4463 Fix Time64Distro Packaging on GH Actions
  .azure/OneBranch.Official.yml
  .azure/OneBranch.PullRequest.yml
  .azure/obtemplates/build-linux-packages.yml
  .github/workflows/package-linux.yml
  .github/workflows/package-reuse-linux.yml
  scripts/package-distribution.ps1
Labels: Area: Build, Area: Automation, Area: Packaging, Partner: .NET

#4467 Update WPA Plugin Stream Lifetime Table
  .github/workflows/plugins.yml
  src/plugins/trace/dll/Tables/QuicStreamLifetime.cs
  src/plugins/trace/dll/pluginManifest.json
Labels: Area: Testing

#4469 Remove invalid characters from logfile names on non-Windows
  scripts/run-gtest.ps1
Labels: OS: Ubuntu, Area: Automation

#4466 Integrate Cross Platform Linux Packaging Tester
  .github/workflows/package-linux.yml
  scripts/docker-script.sh
  src/cs/QuicSimpleTest/Program.cs
  src/cs/QuicSimpleTest/QuicHello.net8.0.csproj
  src/cs/QuicSimpleTest/QuicHello.net9.0.csproj
Labels: Area: Build, OS: Ubuntu, Area: Automation, Area: Packaging

#4483 Socket Errors are Asynchronous
  src/platform/datapath_winuser.c
Labels: Bug: Platform

#4485 Revert CancelDatapathIo Call Order
  src/platform/datapath_winuser.c
Labels: Bug: Platform

#4465 Implement LowLat mode in TCP
  src/inc/quic_platform.h
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
Labels: Area: Performance

#4349 Log QUIC_TLS_SECRETS on all TestConnections and write to disk on cleanup
  scripts/run-gtest.ps1
  src/inc/msquichelper.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestConnection.cpp
  src/test/lib/TestConnection.h
  src/test/lib/precomp.h
Labels: Area: Testing

#4487 Avoid treat atomic alignment warning as error for Android X86
  src/platform/CMakeLists.txt
Labels: Area: Build, external

#4516 Return void for CxPlatSocketSend
  src/core/binding.c
  src/core/binding.h
  src/generated/linux/Tcp.cpp.clog.h
  src/generated/linux/Tcp.cpp.clog.h.lttng.h
  src/generated/linux/binding.c.clog.h
  src/generated/linux/binding.c.clog.h.lttng.h
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/datapath_xplat.c
  src/platform/pcp.c
  src/platform/platform_internal.h
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/QuicDrill.cpp
  src/tools/recvfuzz/recvfuzz.cpp
Labels: Area: Core

#4511 Add flag to not set ideal proc on worker threads
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/platform/platform_worker.c
Labels: external

#4518 Make GetParam return INVALID_STATE error when TLS has been cleaned up
  src/core/library.c
  src/test/lib/ApiTest.cpp
Labels: Bug: Platform
