Repository microsoft/msquic, pull requests merged in 2024-10, with the labels that each got.

#4584 Add prereqs to publishing alpine package docs
  docs/Release.md
Labels: Area: Documentation, Partner: .NET

#4585 Add Helper Complete Jobs
  .github/workflows/build.yml
  .github/workflows/package-linux.yml
  .github/workflows/test-down-level.yml
Labels: Area: Build, Area: Automation

#4484 Align XDP Queues with RSS Better
  src/generated/linux/datapath_raw_xdp_win.c.clog.h
  src/generated/linux/datapath_raw_xdp_win.c.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/platform/datapath_raw_xdp.h
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
Labels: Area: Performance

#4588 Support for SecNetPerf Variables to be in Units of CPU Count
  src/perf/lib/PerfClient.cpp
Labels: Area: Testing, Area: Performance

#4593 add barrier missing between producer submit and needpoke check
  src/platform/datapath_raw_xdp_win.c
Labels: Bug: Platform

#4589 Max RPS NetPerf Test
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Testing, Area: Performance, Area: Automation

#4609 Remove the L from unevaluated string literals.
  src/core/mtu_discovery.c
  src/core/packet_builder.h
  src/core/quicdef.h
  src/core/range.h
Labels: OS: macOS

#4621 Fix crash issue on Samsung phone A217M when send big payload size
  src/platform/datapath_epoll.c
Labels: OS: Ubuntu, external

#4623 Locate `mc.exe` at configuration time
  CMakeLists.txt
Labels: Area: Build, external

#4625 Delegate build environment configuration with QUIC_EXTERNAL_TOOLCHAIN
  CMakeLists.txt
  src/inc/CMakeLists.txt
  src/platform/CMakeLists.txt
Labels: Area: Build, external
