Repository microsoft/msquic, pull requests merged in 2024-11, with the labels that each got.

#4640 Update Execution Docs
  docs/API.md
  docs/Execution.md
Labels: Area: Documentation

#4614 Support Thread Affinity for Execution Config
  src/core/worker.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfClient.h
  src/perf/lib/SecNetPerf.h
  src/perf/lib/SecNetPerfMain.cpp
  src/platform/platform_worker.c
Labels: Area: Performance, Area: API

#4646 Improve version deployment documentation
  docs/Deployment.md
  docs/Settings.md
  docs/Versions.md
Labels: Area: Documentation

#4574 export platform
  .github/workflows/build-reuse-win.yml
  CMakeLists.txt
  src/bin/CMakeLists.txt
  src/core/unittest/CMakeLists.txt
  src/generated/CMakeLists.txt
  src/perf/bin/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/unittest/CMakeLists.txt
  src/platform/unittest/external/CMakeLists.txt
  src/test/bin/CMakeLists.txt
  src/tools/CMakeLists.txt
  src/tools/attack/CMakeLists.txt
  src/tools/pcp/CMakeLists.txt
  src/tools/recvfuzz/CMakeLists.txt
  submodules/CMakeLists.txt
Labels: Area: Build, external

#4602 Expose TTL (on handshake) to applications
  .github/workflows/netperf.yml
  src/core/connection.c
  src/core/connection.h
  src/inc/msquic.h
  src/inc/quic_datapath.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw_socket.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: API, Area: Core

#4607 Standard SecNetPerf Scenarios
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
  src/inc/msquichelper.h
  src/perf/lib/PerfClient.cpp
  src/perf/lib/SecNetPerfMain.cpp
Labels: Area: Performance, Area: Automation
