Repository microsoft/msquic, pull requests merged in 2024-12, with the labels that each got.

#4674 Pass Through Disable AIA Flag
  docs/api/QUIC_CREDENTIAL_CONFIG.md
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/platform/certificates_capi.c
  src/platform/tls_openssl.c
  src/platform/tls_schannel.c
  src/platform/unittest/TlsTest.cpp
Labels: OS: Windows (User), OS: Windows (Kernel), TLS: Schannel, Area: API

#4688 Fix OneBranch Build of msquictest
  src/test/bin/quic_gtest.cpp
Labels: Area: Build, OS: Windows (User), Area: Automation

#4689 Update test-down-level.yml for new Releases
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#4692 Refactor: Add namespace, enable sanitize builds
  .github/workflows/build-reuse-win.yml
  src/bin/CMakeLists.txt
  src/platform/unittest/external/CMakeLists.txt
Labels: Area: Build

#4699 Update Alpine Release doc
  docs/Release.md
Labels: Area: Documentation, Partner: .NET

#4712 Run fmt and clippy for rust code
  .github/workflows/cargo.yml
  scripts/build.rs
  src/lib.rs
Labels: Language: Rust

#4716 Add conversion method for Addr
  Cargo.toml
  src/lib.rs
Labels: external, Language: Rust

#4718 added unique pointer for connection
  src/test/lib/DataTest.cpp
Labels: Bug: Test/Tool

#4719 Changes to trigger wan perf test run manually
  .github/workflows/wan-perf.yml
Labels: Area: Automation

#4721 Add repo var to all other ci jobs
  .github/workflows/build-reuse-darwin-framework.yml
  .github/workflows/code-coverage.yml
  .github/workflows/dotnet-test.yml
  .github/workflows/package-reuse-linux.yml
  .github/workflows/stress.yml
  .github/workflows/test.yml
Labels: Area: Build, external

#4708 Use global API table instead of each handle's having table ptr
  Cargo.toml
  src/lib.rs
Labels: external, Language: Rust

#4727 Simplify cmake config chainloading
  CMakeLists.txt
  src/bin/CMakeLists.txt
  src/bin/msquic-config-unix.cmake.in
  src/bin/msquic-config.cmake.in
Labels: Area: Build, external

#4725 Export msquic include install dir
  src/bin/CMakeLists.txt
Labels: Area: Build, external
