Repository microsoft/msquic, pull requests merged in 2024-01, with the labels that each got.

#4035 NMR registration helpers
  src/inc/msquic.h
  src/test/bin/winkernel/control.cpp
Labels: Area: API

#4036 fix: apply lb settings after lb mode change
  src/core/library.c
  src/core/unittest/SettingsTest.cpp
Labels: external, Area: Core

#4037 Add 'cancel on loss' send mode to MsQuicStream.
  docs/Streams.md
  docs/api/StreamSend.md
  src/core/stream.h
  src/core/stream_send.c
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/plugins/dbg/quictypes.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: API, Area: Core

#4043 Remove Windows 2019 Builds
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: Area: Build, Area: Automation

#4016 More SecNetPerf Cleanup/Refactoring
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfClient.h
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/SecNetPerf.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.h
Labels: Area: Performance

#4015 Support Optional Units on secnetperf Arguments
  scripts/RemoteTests.json
  src/perf/bin/appmain.cpp
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfClient.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/readme.md
Labels: Area: Performance

#4045 NMR helper improvement
  src/inc/msquic.h
  src/test/bin/winkernel/control.cpp
Labels: Area: API

#4049 Update SQL strings to conform to new format.
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance

#4051 Update the Reusable Build Workflows to Support Perf Builds
  .github/workflows/build-reuse-unix.yml
  .github/workflows/build-reuse-win.yml
  .github/workflows/build-reuse-winkernel.yml
  .github/workflows/code-coverage.yml
  .github/workflows/package-reuse-linux.yml
  .github/workflows/stress.yml
  .github/workflows/test.yml
Labels: Area: Build, Area: Automation

#4052 Allow NMR helpers to not wait at all
  src/inc/msquic.h
Labels: Area: API

#4055 Fix tests not targeting private msquic.sys
  src/bin/winkernel/msquicpriv.kernel.vcxproj
  src/bin/winkernel/nmrprovider.c
  src/inc/msquicp.h
  src/test/bin/winkernel/control.cpp
  src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
Labels: Area: Testing

#4050 Restart Server on Each NetPerf Test Run
  .github/workflows/build-reuse-winkernel.yml
  scripts/prepare-machine.ps1
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
  src/inc/msquic.hpp
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.cpp
  src/perf/lib/Tcp.h
Labels: Area: Performance, Area: Automation, Bug: Test/Tool

#4060 Fix a naming conflict in msquic.h
  src/bin/winkernel/nmrprovider.c
  src/inc/msquic.h
  src/test/bin/winkernel/control.cpp
Labels: Area: API

#4062 Run secnetperf in Separate Process to Wait on (with Timeout)
  .github/workflows/netperf.yml
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4064 Support Testing Multiple IO Models with netperf
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
  src/perf/lib/SecNetPerfMain.cpp
Labels: Area: Performance, Area: Automation

#4068 Adds Kernel Support for netperf
  scripts/prepare-machine.ps1
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4070 Update ubuntu dockers for compliance
  .docker/ubuntu-20.04/Dockerfile
  .docker/ubuntu-22.04/Dockerfile
Labels: Area: Build

#4072 Some Minor Output and Error Clean up for netperf
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4065 Refactor fragile ID tracking and add latency insertion
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4073 Add Ubuntu 23.10 to `OneBranch.Publish.yml`.
  .azure/OneBranch.Publish.yml
Labels: Area: Automation, Area: Packaging

#4077 Run netperf Tests Longer
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4078 Print Statistics in netperf Throughput Tests
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
  src/perf/lib/PerfClient.cpp
  src/perf/lib/SecNetPerf.h
Labels: Area: Performance, Area: Automation

#4079 Break Endless Loop in GetPrivateRsaKey
  src/platform/selfsign_capi.c
Labels: OS: Windows (User), OS: Windows (Kernel), Bug: Platform

#4083 Update Schannel Logic to Handler Larger Output Buffers
  src/generated/linux/tls_schannel.c.clog.h
  src/generated/linux/tls_schannel.c.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/platform/tls_schannel.c
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
Labels: OS: Windows (User), OS: Windows (Kernel), TLS: Schannel, Bug: Platform

#4085 v2.3 Release Notes
  docs/Release.md
Labels: Area: Documentation

#4095 Add Fedora 39 to OneBranch.Publish.yml
  .azure/OneBranch.Publish.yml
Labels: OS: Ubuntu, Area: Automation, Area: Packaging

#4094 Add v2.3 to Down Level Tests
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#4097 Improvements for netperf
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
  src/manifest/MsQuic.wprp
  src/manifest/MsQuicEtw.man
Labels: Area: Performance, Area: Automation

#4098 Refactor queue limit
  src/core/connection.c
  src/core/quicdef.h
Labels: Area: Performance, Area: Core

#4099 Fix XDP for netperf
  scripts/secnetperf-helpers.psm1
  src/platform/datapath_raw_xdp_win.c
Labels: Area: Performance, Area: Automation, Bug: Platform
