Repository microsoft/msquic, pull requests merged in 2024-06, with the labels that each got.

#4336 Update Dockerfile for xdp and cross compile
  .docker/ubuntu-20.04/Dockerfile
  .docker/ubuntu-22.04/Dockerfile
  .github/workflows/docker-publish-xcomp.yml
Labels: Area: Build, Area: Automation

#4346 Fix QTIP Config in Test YAML
  .github/workflows/test.yml
Labels: Area: Testing, Area: Automation

#4348 Install Perl on Windows via WinGet
  scripts/prepare-machine.ps1
Labels: Area: Build

#4279 Support Priority Work on Connections
  src/core/api.c
  src/core/connection.c
  src/core/connection.h
  src/core/datagram.c
  src/core/operation.c
  src/core/operation.h
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: Performance, Area: API

#4352 Fix test log path sanitation
  scripts/run-gtest.ps1
Labels: Area: Testing
