Repository microsoft/msquic, pull requests merged in 2024-02, with the labels that each got.

#4104 Bigger printf-Style Log Buffer
  src/inc/quic_trace.h
Labels: Area: Logging

#4113 Fix Deployment Docs Link
  docs/Deployment.md
Labels: Area: Documentation

#4114 More Connection Statistics for netperf
  .github/workflows/build-reuse-win.yml
  .github/workflows/stress.yml
  CMakeLists.txt
  scripts/build.ps1
  src/inc/quic_datapath.h
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/SecNetPerf.h
  src/perf/lib/Tcp.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
Labels: Area: Build, Area: Performance

#4115 Fix Possible DISPATCH_SEND Inline Issue
  src/core/api.c
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/test/lib/TestStream.cpp
Labels: Bug: Core, Area: Core

#4117 Use Environment in secnetperf Output
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4116 Default to Latest Build Tools on Windows
  CMakeLists.txt
Labels: Area: Build

#4100 Fixes to Support qtip in netperf
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4119 New windows docker image for Onebranch
  .azure/OneBranch.Official.yml
Labels: Area: Build

#4122 Remove TCP-specific Cleanup Stuff
  src/platform/datapath_winuser.c
Labels: Bug: Platform, Bug: Test/Tool

#4121 Fix Cancel On Loss Test's Race Condition
  src/test/lib/DataTest.cpp
Labels: Bug: Test/Tool

#4129 Fix overflow in winkernel CxPlatEventWaitWithTimeout
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
Labels: OS: Windows (Kernel), Area: Core

#4127 Collect Get-NetView Diagnostics for netperf
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation, Area: Logging

#4133 Limit the scope of metadata events in MsQuic.wprp
  src/manifest/MsQuic.wprp
Labels: Area: Logging

#4135 Add a Threat Model doc
  docs/ThreatModel.md
Labels: Area: Documentation

#4137 Another Fix for Perf Counters Test
  src/test/lib/ApiTest.cpp
Labels: Bug: Test/Tool

#4136 Fix Down Level Tests
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#4139 Improve/Expand Down Level Test Coverage
  .github/workflows/test-down-level.yml
Labels: Area: Testing, Area: Automation

#4140 Remove Invalid Assert
  src/core/send.c
Labels: Area: Core

#4149 Add perf merge events back
  src/manifest/MsQuic.wprp
Labels: Area: Logging

#4145 Don't send client CONNECTION_CLOSE on 1-RTT before handshake completion.
  src/core/packet_builder.c
  src/test/lib/HandshakeTest.cpp
Labels: Area: Core

#4151 Fix Get-NetView Execution
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4157 Process Full Latency Output and Encode in Json
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4161 Threat Model Text Improvements
  docs/ThreatModel.md
Labels: Area: Documentation

#4160 Add a run date column for the test runs
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation
