Repository microsoft/msquic, pull requests merged in 2024-03, with the labels that each got.

#4042 Receive Buffer Refactoring
  src/core/crypto.c
  src/core/recv_buffer.c
  src/core/recv_buffer.h
  src/core/stream.c
  src/core/stream_recv.c
  src/core/unittest/RecvBufferTest.cpp
  src/core/worker.c
  src/generated/linux/recv_buffer.c.clog.h
  src/generated/linux/recv_buffer.c.clog.h.lttng.h
Labels: Area: Core

#4179 Update documentation on NEW_CONNECTION_INFO::ServerName
  docs/api/QUIC_NEW_CONNECTION_INFO.md
Labels: Area: Documentation

#4177 Support Multiple Pending Receives
  src/core/api.c
  src/core/connection.c
  src/core/connection.h
  src/core/library.h
  src/core/operation.c
  src/core/operation.h
  src/core/stream.c
  src/core/stream.h
  src/core/stream_recv.c
  src/generated/linux/api.c.clog.h
  src/generated/linux/api.c.clog.h.lttng.h
  src/inc/quic_platform_posix.h
  src/platform/inline.c
  src/plugins/dbg/quictypes.h
  src/tools/spin/spinquic.cpp
Labels: Area: Core

#4074 Fuzz Handshake packet
  scripts/recvfuzz.ps1
  src/tools/recvfuzz/recvfuzz.cpp
Labels: Area: Testing, Area: Stress

#4187 Fix Verify Check to Account for Race Conditions
  src/core/api.c
Labels: Bug: Core, Area: Stress, Area: API

#4191 [2.3] Update OneBranch build docker image
  .azure/OneBranch.Official.yml
Labels: Area: Build, Backport

#4190 Update OneBranch build docker image
  .azure/OneBranch.Official.yml
Labels: Area: Build

#4192 [2.2] Update OneBranch build docker image
  .azure/OneBranch.Official.yml
Labels: Area: Build, Backport

#4196 Removed Unused Cert Sign Function
  src/generated/linux/cert_capi.c.clog.h
  src/generated/linux/cert_capi.c.clog.h.lttng.h
  src/inc/quic_cert.h
  src/platform/cert_capi.c
Labels: Area: Build, TLS: miTLS

#4188 Fix CodeCoverage Upload
  .github/workflows/code-coverage.yml
Labels: Area: Automation

#4199 Skip Unit Tests in Code Coverage
  .github/workflows/code-coverage.yml
  src/inc/msquic.hpp
Labels: Area: Testing, Area: Automation

#4197 Fix Posix QuicAddrToString
  src/inc/msquic_posix.h
Labels: OS: Ubuntu, OS: macOS, Area: Core

#4206 Move Code Coverage to OpenSSL
  .github/workflows/code-coverage.yml
Labels: Area: Testing, Area: Automation

#4201 Persist BestResult / BestResultCommit / Baseline for all results, regardless of regression.
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
Labels: Area: Performance, Area: Automation

#4209 Fix Publish of Cross-Compile Docker Image Tag
  .github/workflows/docker-publish-xcomp.yml
Labels: Area: Build, OS: Ubuntu, Area: Automation

#4211 Work around fpm dependencies for ubuntu 20.04
  .docker/ubuntu-20.04/Dockerfile
Labels: Area: Build

#4217 Support Native Compiler in OneBranch Builds
  scripts/update-version.ps1
  src/bin/winkernel/msquic.kernel.vcxproj
  src/bin/winkernel/msquicpriv.kernel.vcxproj
  src/core/core.kernel.vcxproj
  src/core/precomp.h
  src/manifest/manifest.kernel.vcxproj
  src/nuget.config
  src/perf/bin/drvmain.cpp
  src/perf/bin/secnetperfdriver.kernel.vcxproj
  src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
  src/perf/lib/perflib.kernel.vcxproj
  src/platform/platform.kernel.vcxproj
  src/test/bin/winkernel/msquictest.kernel.vcxproj
  src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
  src/test/lib/precomp.h
  src/test/lib/testlib.kernel.vcxproj
  version.json
Labels: Area: Build, OS: Windows (Kernel), Area: Automation
