Repository microsoft/msquic, pull requests merged in 2024-05, with the labels that each got.

#4273 Package WPA Plugin
  .github/workflows/plugins.yml
  src/plugins/trace/dll/QuicTraceLib.csproj
  src/plugins/trace/dll/pluginManifest.json
Labels: Area: Automation, Area: Logging

#4262 Enable secnetperf with xdp on azure VM
  docs/BUILD.md
  scripts/secnetperf-helpers.psm1
  scripts/secnetperf.ps1
  scripts/spin.ps1
  scripts/test.ps1
  src/cs/lib/msquic_generated.cs
  src/inc/msquic.h
  src/perf/lib/SecNetPerfMain.cpp
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_xplat.c
  src/platform/unittest/DataPathTest.cpp
  src/test/bin/quic_gtest.cpp
  src/test/lib/ApiTest.cpp
  src/tools/attack/attack.cpp
  src/tools/spin/spinquic.cpp
Labels: OS: Ubuntu, Area: Performance, Area: Automation

#4281 Debugger Extension Fixes & Improvements
  src/plugins/dbg/library.cpp
  src/plugins/dbg/quictypes.h
  src/plugins/dbg/worker.cpp
Labels: Bug: Test/Tool

#4292 Disable Linux XDP HPS
  scripts/secnetperf-helpers.psm1
Labels: Area: Performance, Area: Automation

#4264 Fix broken build on Alpine
  .azure/obtemplates/build-linux.yml
  CMakeLists.txt
  docs/BUILD.md
  scripts/build.ps1
  scripts/build.rs
  src/platform/CMakeLists.txt
Labels: Area: Build, OS: Ubuntu, Partner: .NET

#4305 fix: buffer overflow in quic_trace
  src/generated/stdout/quic_trace.c
Labels: external, Area: Logging

#4331 Minor Abstract Update
  src/core/api.c
Labels: Area: Documentation, Area: Core
