Repository microsoft/msquic, pull requests merged in 2024-04, with the labels that each got.

#4222 Add logic to remove any logging residue.
  scripts/secnetperf-helpers.psm1
Labels: Area: Automation, Area: Logging

#4223 Log.ps1 should remove AppData ETL buildup
  scripts/log.ps1
Labels: Area: Automation, Area: Logging

#4224 Implement workaround for log.ps1 not working on Lab Linux
  scripts/secnetperf-helpers.psm1
Labels: Area: Performance, Area: Automation, Area: Logging

#4231 Fix Bug in SpinQuic Around Receive Complete
  src/tools/spin/spinquic.cpp
Labels: Area: Stress, Bug: Test/Tool

#4235 Fix Stream Recv Behavior
  src/core/stream_recv.c
  src/tools/spin/spinquic.cpp
Labels: Area: Testing, Area: Stress, Area: Core

#4169 Convert application close frame to transport close frame during handshake.
  src/core/connection.c
  src/core/connection.h
  src/core/crypto.c
  src/core/crypto.h
  src/core/frame.h
  src/core/loss_detection.c
  src/core/packet_builder.c
  src/core/send.c
  src/core/send.h
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: Core

#4237 Update SpinQuic to Validate Bytes in Stream Receive aren't Corrupted
  src/core/api.c
  src/core/datagram.c
  src/tools/spin/spinquic.cpp
Labels: Area: Testing, Area: Stress

#4245 Fix for a deadlock discovered in 4169
  src/core/packet_builder.c
  src/core/packet_builder.h
  src/core/send.c
Labels: Bug: Core, Partner: .NET

#4247 CodeQL Classification
  .CodeQL.yml
Labels: Area: Automation, Area: Security

#4248 Cpestano/bug fix relative paths
  scripts/prepare-machine.ps1
Labels: Area: Automation

#4250 Fix a Few CodeQL Warnings
  src/core/recv_buffer.c
  src/core/stream_send.c
  src/perf/lib/SecNetPerfMain.cpp
  src/platform/unittest/CryptTest.cpp
Labels: Area: Build

#4259 Drop Nth Packet Test
  src/generated/linux/TestHelpers.h.clog.h
  src/generated/linux/TestHelpers.h.clog.h.lttng.h
  src/manifest/clog.sidecar
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
  src/test/lib/TestHelpers.h
Labels: Area: Testing

#4265 Adds retry logic to creating Secnetperf remote powershell sessions
  scripts/secnetperf.ps1
Labels: Area: Testing, Area: Performance, Area: Automation
