Repository microsoft/msquic, pull requests merged in 2025-07, with the labels that each got.

#5192 Reduce rust crate size by excluding fuzz test corpora
  Cargo.toml
Labels: Language: Rust, Area: Packaging

#5220 More silo enlightenment
  src/core/connection.c
Labels: Bug: Platform

#5195 Reduce rust crate size by excluding fuzz test corpora
  Cargo.toml
Labels: Language: Rust, Area: Packaging

#5211 Fix SecNetPerf Parameter Handlings
  src/perf/bin/appmain.cpp
Labels: Bug: Test/Tool

#5219 Fix size check for QUIC_HANDSHAKE_INFO
  src/platform/tls_openssl.c
Labels: Bug: Core, TLS: OpenSSL
