Repository microsoft/msquic, pull requests merged in 2025-02, with the labels that each got.

#4792 Fix wrong instruction in sample.md
  docs/Sample.md
Labels: external

#4793 datapath_winuser: query RioDispatch only if we are using Rio
  src/platform/datapath_winuser.c
Labels: Bug: Platform

#4797 Relax TLS Unit Test Checks
  src/platform/unittest/TlsTest.cpp
Labels: Area: Testing, Bug: Platform

#4798 Add lab cpu traces
  scripts/secnetperf-helpers.psm1
Labels: Area: Performance, Area: Automation, Area: Logging

#4757 Add support for setting TypeOfService/TrafficClass on connections
  docs/Settings.md
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/core/packet_builder.c
  src/cs/lib/msquic_generated.cs
  src/ffi/linux_bindings.rs
  src/ffi/win_bindings.rs
  src/generated/linux/connection.c.clog.h
  src/generated/linux/connection.c.clog.h.lttng.h
  src/generated/linux/datapath_winkernel.c.clog.h
  src/generated/linux/datapath_winkernel.c.clog.h.lttng.h
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/perf/lib/Tcp.cpp
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/pcp.c
  src/platform/platform_internal.h
  src/platform/unittest/DataPathTest.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/QuicDrill.cpp
  src/test/lib/TestHelpers.h
  src/tools/attack/attack.cpp
  src/tools/lb/loadbalancer.cpp
  src/tools/recvfuzz/recvfuzz.cpp
Labels: OS: Windows (User), OS: Ubuntu, OS: Windows (Kernel), Area: API

#4806 Optimize searching for packets in the LostPackets list to see if they…
  src/core/loss_detection.c
Labels: Area: Performance

#4808 Remove ubuntu-20.04 from GitHub Actions
  .github/workflows/build-reuse-unix.yml
  .github/workflows/build.yml
  .github/workflows/docker-publish-xcomp.yml
  .github/workflows/dotnet-test.yml
  .github/workflows/package-linux.yml
  .github/workflows/package-reuse-linux.yml
  .github/workflows/stress.yml
  .github/workflows/test-down-level.yml
  .github/workflows/test.yml
  scripts/secnetperf.ps1
Labels: Area: Build, OS: Ubuntu, Area: Automation

#4786 Rust: ConnectionEvent enum
  src/lib.rs
  src/types.rs
Labels: Language: Rust

#4811 Require powershell 7.2 for scripts susceptible to be run manually
  scripts/build.ps1
  scripts/generate-dotnet.ps1
  scripts/prepare-machine.ps1
  scripts/test.ps1
  scripts/update-sidecar.ps1
Labels: Area: Automation

#4816 Updates for Kernel Solution for 32-bit Builds
  msquic.kernel.sln
Labels: Area: Build, OS: Windows (Kernel), Area: Automation

#4828 Fix Release-Build Failure on Debian Bookworm
  src/inc/msquichelper.h
Labels: Area: Build, OS: Linux, external

#4817 Remove Older, Unsupported Release
  docs/Release.md
Labels: Area: Documentation

#4815 Rust: StreamEvent enum
  src/lib.rs
  src/types.rs
Labels: Language: Rust

#4758 Add a mode to the receive buffer to handle external buffers
  docs/api/StreamOpen.md
  src/core/api.c
  src/core/api.h
  src/core/connection.c
  src/core/crypto.c
  src/core/library.c
  src/core/operation.c
  src/core/operation.h
  src/core/recv_buffer.c
  src/core/recv_buffer.h
  src/core/stream.c
  src/core/stream.h
  src/core/stream_recv.c
  src/core/stream_set.c
  src/core/unittest/RecvBufferTest.cpp
  src/core/worker.c
  src/core/worker.h
  src/cs/lib/msquic_generated.cs
  src/generated/linux/recv_buffer.c.clog.h
  src/generated/linux/recv_buffer.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/quic_platform.h
  src/inc/quic_trace.h
  src/manifest/MsQuicEtw.man
  src/plugins/dbg/quictypes.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
Labels: Area: API, Area: Core

#4831 Rust: ListenerEvent enum
  src/lib.rs
  src/types.rs
Labels: Language: Rust

#4849 Remove Extra Keep Alive set in ConnectionStart
  src/core/connection.c
Labels: Area: Core

#4859 Rust: Support preview apis in ffi generated code
  src/ffi/linux_bindings.rs
  src/ffi/win_bindings.rs
  src/ffi/wrapper.hpp
Labels: Language: Rust

#4836 Receive buffer documentation
  docs/ReceiveBuffer.md
Labels: Area: Documentation

#4869 Disable Android on 24.04
  .github/workflows/build.yml
Labels: Area: Build, OS: Android

#4839 Rust: Settings type
  src/lib.rs
  src/settings.rs
Labels: Language: Rust

#4871 Initialize processor info memory to prevent garbage values
  src/platform/platform_winuser.c
Labels: OS: Windows (User), Bug: Platform

#4858 Rust: Move rust code to a single folder
  Cargo.toml
  scripts/build.rs
  src/rs/error.rs
  src/rs/ffi/linux_bindings.rs
  src/rs/ffi/mod.rs
  src/rs/ffi/win_bindings.rs
  src/rs/ffi/wrapper.hpp
  src/rs/lib.rs
  src/rs/settings.rs
  src/rs/types.rs
Labels: Language: Rust
