Repository microsoft/msquic, pull requests merged in 2025-01, with the labels that each got.

#4733 Fix Path Classifiers in CodeQL YML
  .CodeQL.yml
Labels: Area: Automation

#4732 Event Queue Completion Refactor
  src/generated/linux/datapath_raw_xdp_linux.c.clog.h
  src/generated/linux/datapath_raw_xdp_linux.c.clog.h.lttng.h
  src/generated/linux/datapath_raw_xdp_win.c.clog.h
  src/generated/linux/datapath_raw_xdp_win.c.clog.h.lttng.h
  src/generated/linux/datapath_winuser.c.clog.h
  src/generated/linux/datapath_winuser.c.clog.h.lttng.h
  src/inc/quic_platform.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_linux.c
  src/platform/datapath_raw_dummy.c
  src/platform/datapath_raw_xdp.h
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
  src/platform/datapath_win.c
  src/platform/datapath_winuser.c
  src/platform/inline.c
  src/platform/platform_internal.h
  src/platform/platform_winuser.c
  src/platform/platform_worker.c
  src/platform/unittest/PlatformTest.cpp
Labels: Area: Core

#4723 Auto generate rust bindings using rust bindgen
  .github/workflows/cargo.yml
  Cargo.toml
  scripts/build.rs
  src/ffi/linux_bindings.rs
  src/ffi/mod.rs
  src/ffi/win_bindings.rs
  src/ffi/wrapper.hpp
  src/lib.rs
Labels: Language: Rust

#4738 More use of CMAKE_INSTALL_<...>DIR
  CMakeLists.txt
  src/bin/CMakeLists.txt
  src/generated/CMakeLists.txt
Labels: Area: Build, external

#4737 Provide namespaced CMake targets
  src/bin/CMakeLists.txt
  src/bin/msquic-config.cmake.in
  src/inc/CMakeLists.txt
  src/platform/CMakeLists.txt
  src/platform/unittest/external/CMakeLists.txt
Labels: Area: Build, external

#4320 Possibility for datagrams to be dropped when not able to send
  docs/api/DatagramSend.md
  docs/api/StreamSend.md
  src/core/datagram.c
  src/core/datagram.h
  src/core/send.c
  src/cs/lib/msquic_generated.cs
  src/ffi/linux_bindings.rs
  src/ffi/win_bindings.rs
  src/inc/msquic.h
  src/plugins/trace/README.md
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DatagramTest.cpp
Labels: external, Area: API, Area: Core

#4743 Implement Error and ErrorCode for Rust
  src/error.rs
  src/lib.rs
Labels: Language: Rust

#4744 suppress invalid-unevaluated-string for AppleClang 16
  CMakeLists.txt
Labels: Area: Build, OS: macOS, external

#4745 Disable Matrix Fail Fast for Cargo Action
  .github/workflows/cargo.yml
Labels: Area: Automation

#4756 Rust: Migrate to use ffi QUIC_API_TABLE
  src/error.rs
  src/ffi/mod.rs
  src/lib.rs
Labels: Language: Rust

#4765 Rust: Rename QUIC_ERROR to QUIC_STATUS
  src/error.rs
  src/ffi/linux_bindings.rs
  src/ffi/win_bindings.rs
  src/ffi/wrapper.hpp
  src/lib.rs
Labels: Language: Rust

#4775 Delete .NET 8.0 from pipeline
  .github/workflows/package-alpine-linux.yml
  .github/workflows/package-linux.yml
  src/cs/QuicSimpleTest/QuicHello.net8.0.csproj
Labels: Area: Build, Area: Testing, Area: Automation, .NET

#4774 Add netperf capability to collect CPU traces on Azure
  scripts/quic_callback.ps1
  scripts/secnetperf-helpers.psm1
Labels: Area: Performance, Area: Automation, Area: Logging
