Repository microsoft/msquic, pull requests merged in 2025-03, with the labels that each got.

#4886 Allow non-System32 DLL Loads for Sanitizer Builds
  CMakeLists.txt
Labels: Area: Build, OS: Windows (User)

#4447 Key Update Crash on Allocation Failure
  src/platform/crypt.c
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DrillDescriptor.cpp
  src/test/lib/DrillDescriptor.h
  src/test/lib/QuicDrill.cpp
Labels: Bug: Core

#4887 Wait for Dumps
  scripts/run-executable.ps1
Labels: Area: Testing, Area: Automation

#4852 Optimize QuicStreamSetUpdateMaxStreams
  src/core/stream.c
  src/core/stream.h
  src/core/stream_set.c
  src/core/stream_set.h
  src/inc/quic_platform.h
  src/platform/inline.c
  src/plugins/dbg/quictypes.h
Labels: Area: Performance, Area: Core

#4868 Add New Listener Callback for DoS Mode
  docs/Settings.md
  src/core/binding.c
  src/core/binding.h
  src/core/library.c
  src/core/listener.c
  src/core/listener.h
  src/inc/msquic.h
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
Labels: Area: API

#4807 Add "delay" and "delayType" options to secnetperf tool
  src/core/api.c
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfServer.cpp
  src/perf/lib/PerfServer.h
  src/perf/lib/SecNetPerf.h
  src/perf/lib/SecNetPerfMain.cpp
  src/perf/lib/Tcp.h
  src/perf/readme.md
Labels: Area: Performance

#4893 task_3717_DotNetChanges: Changes in CS files
  src/cs/lib/msquic_generated.cs
  src/rs/ffi/linux_bindings.rs
  src/rs/ffi/win_bindings.rs
Labels: Language: C#, Language: Rust

#4881 Rust: RegistrationConfig and CredentialConfig types
  .github/workflows/cargo.yml
  Cargo.toml
  scripts/build.rs
  src/rs/config.rs
  src/rs/lib.rs
Labels: Language: Rust

#4894 Fix Some Synchronization Issues in Receive Fuzzer
  src/tools/recvfuzz/recvfuzz.cpp
Labels: Area: Testing, Area: Automation, Bug: Test/Tool

#4915 Add support for MsQuic Logging on Azure Netperf
  scripts/quic_callback.ps1
  scripts/secnetperf-helpers.psm1
Labels: Area: Performance, Area: Logging

#4916 Enable Android on 24.04 with openssl3
  .github/workflows/build.yml
  scripts/build.ps1
  src/tools/forwarder/forwarder.cpp
  src/tools/interopserver/InteropServer.cpp
  src/tools/ip/server/quicipserver.cpp
  src/tools/lb/loadbalancer.cpp
  src/tools/sample/sample.c
Labels: Area: Build, OS: Android

#4898 Onboard ws2025 Tests
  .github/workflows/build-reuse-win.yml
  .github/workflows/test.yml
Labels: Area: Testing, Area: Automation

#4918 Rust: Implement various bitflags enums
  src/rs/config.rs
  src/rs/lib.rs
  src/rs/server_client_test.rs
  src/rs/types.rs
Labels: Language: Rust

#4925 Enable Linux Interop Testing
  .github/workflows/test.yml
  src/tools/interop/interop.cpp
Labels: Area: Testing, OS: Linux, Area: Automation

#4921 Document usage of stream priority set param
  .github/workflows/publish-docfx.yml
  docs/Settings.md
Labels: Area: Documentation

#4929 Refactor CxPlat Pool Abstraction
  src/core/api.c
  src/core/binding.c
  src/core/connection.c
  src/core/crypto.c
  src/core/datagram.c
  src/core/operation.c
  src/core/operation.h
  src/core/packet_space.c
  src/core/recv_buffer.c
  src/core/recv_buffer.h
  src/core/sent_packet_metadata.c
  src/core/stream.c
  src/core/stream_send.c
  src/core/unittest/RecvBufferTest.cpp
  src/core/worker.c
  src/inc/msquic.hpp
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winkernel.h
  src/inc/quic_platform_winuser.h
  src/platform/datapath_epoll.c
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_win.c
  src/platform/datapath_winkernel.c
  src/platform/datapath_winuser.c
  src/platform/inline.c
Labels: Area: Core

#4934 Add Linux Release Tests
  .github/workflows/test.yml
Labels: Area: Testing, Area: Automation

#4936 Rust: Enable server client test on nix
  src/rs/lib.rs
  src/rs/server_client_test.rs
Labels: Language: Rust

#4935 Move Pools to Global Per Proc
  src/core/api.c
  src/core/binding.c
  src/core/connection.c
  src/core/datagram.c
  src/core/frame.h
  src/core/library.c
  src/core/library.h
  src/core/loss_detection.c
  src/core/operation.c
  src/core/operation.h
  src/core/precomp.h
  src/core/send.c
  src/core/sent_packet_metadata.h
  src/core/stream.c
  src/core/stream_recv.c
  src/core/worker.c
  src/core/worker.h
  src/inc/quic_platform_posix.h
  src/inc/quic_platform_winuser.h
Labels: Area: Core

#4945 Add XDP Code Coverage Support
  .github/workflows/code-coverage.yml
  scripts/run-executable.ps1
Labels: Area: Testing, Area: Automation

#4937 Avoid reuse of a global buffer between test cases
  src/test/lib/DataTest.cpp
Labels: Bug: Test/Tool

#4832 Implement Connection Pool API
  docs/api/ConnectionPoolCreate.md
  docs/api/QUIC_CONNECTION_POOL_CONFIG.md
  scripts/clog.inputs
  scripts/prepare-machine.ps1
  src/core/CMakeLists.txt
  src/core/api.c
  src/core/api.h
  src/core/binding.c
  src/core/connection.c
  src/core/connection.h
  src/core/connection_pool.c
  src/core/core.kernel.vcxproj
  src/core/inline.c
  src/core/library.c
  src/core/library.h
  src/cs/lib/msquic_generated.cs
  src/generated/linux/ToeplitzTest.cpp.clog.h
  src/generated/linux/connection_pool.c.clog.h
  src/generated/linux/connection_pool.c.clog.h.lttng.h
  src/generated/linux/quic.clog_ToeplitzTest.cpp.clog.h.c
  src/generated/linux/quic.clog_connection_pool.c.clog.h.c
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/msquic_posix.h
  src/inc/msquic_winkernel.h
  src/inc/quic_datapath.h
  src/inc/quic_platform.h
  src/inc/quic_platform_winuser.h
  src/inc/quic_sal_stub.h
  src/inc/quic_toeplitz.h
  src/inc/quic_trace.h
  src/manifest/MsQuicEtw.man
  src/manifest/clog.sidecar
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw_dummy.c
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
  src/platform/inline.c
  src/platform/toeplitz.c
  src/platform/unittest/CMakeLists.txt
  src/platform/unittest/ToeplitzTest.cpp
  src/rs/ffi/linux_bindings.rs
  src/rs/ffi/win_bindings.rs
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/quic_gtest.h
  src/test/bin/winkernel/control.cpp
  src/test/bin/winkernel/driver.cpp
  src/test/lib/ApiTest.cpp
  src/test/lib/HandshakeTest.cpp
  src/test/lib/TestHelpers.h
  src/tools/lb/loadbalancer.cpp
  src/tools/sample/sample.c
Labels: Area: Performance, Area: API

#4947 Update send buffering documentation
  docs/Streams.md
Labels: Area: Documentation

#4949 Avoid calling QuicSendWriteFrames whith only the path challenge flag
  src/core/send.c
Labels: Area: Testing, Area: Core

#4954 Document Supported Architectures
  docs/Release.md
Labels: Area: Documentation

#4950 Rust: Support linking pre-installed msquic lib
  .github/workflows/cargo.yml
  Cargo.toml
  scripts/build.rs
Labels: Language: Rust

#4803 Add support for both Qtip and UDP traffic for Server Listeners.
  .github/workflows/test.yml
  src/core/binding.c
  src/core/binding.h
  src/core/connection.c
  src/core/connection.h
  src/core/connection_pool.c
  src/core/library.c
  src/core/library.h
  src/core/listener.c
  src/core/listener.h
  src/core/path.c
  src/core/quicdef.h
  src/core/settings.c
  src/core/settings.h
  src/core/unittest/SettingsTest.cpp
  src/cs/lib/msquic_generated.cs
  src/generated/linux/datapath_xplat.c.clog.h
  src/generated/linux/datapath_xplat.c.clog.h.lttng.h
  src/generated/linux/settings.c.clog.h
  src/generated/linux/settings.c.clog.h.lttng.h
  src/inc/msquic.h
  src/inc/msquic.hpp
  src/inc/quic_datapath.h
  src/manifest/clog.sidecar
  src/perf/lib/PerfClient.cpp
  src/perf/lib/PerfClient.h
  src/perf/lib/SecNetPerfMain.cpp
  src/platform/datapath_kqueue.c
  src/platform/datapath_raw.c
  src/platform/datapath_raw.h
  src/platform/datapath_raw_dpdk.c
  src/platform/datapath_raw_dummy.c
  src/platform/datapath_raw_linux.c
  src/platform/datapath_raw_socket.c
  src/platform/datapath_raw_win.c
  src/platform/datapath_raw_xdp_linux.c
  src/platform/datapath_raw_xdp_win.c
  src/platform/datapath_win.c
  src/platform/datapath_winuser.c
  src/platform/datapath_xplat.c
  src/platform/platform_internal.h
  src/rs/ffi/linux_bindings.rs
  src/rs/ffi/win_bindings.rs
  src/test/MsQuicTests.h
  src/test/bin/quic_gtest.cpp
  src/test/bin/winkernel/control.cpp
  src/test/lib/DataTest.cpp
  src/tools/attack/attack.cpp
Labels: Area: API, Area: Lola, Partner: SQL

#4956 Fix data corruption in receive buffer
  src/core/recv_buffer.c
  src/core/unittest/RecvBufferTest.cpp
Labels: Bug: Core, Area: Core
